import Link from "next/link";
import { Save } from "lucide-react";
import { ActionButton } from "@/components/action-feedback";
import { PageHeader } from "@/components/page-header";

export const metadata = { title: "Settings" };
export default async function SettingsPage({ params }: { params: Promise<{ organisationSlug: string }> }) {
  const { organisationSlug } = await params;
  return <main className="page"><PageHeader title="Practice settings" description="Manage the details clients see and the defaults your team uses." /><div className="settings-grid"><nav className="settings-nav" aria-label="Settings"><Link className="active" href={`/app/${organisationSlug}/settings`}>Practice details</Link><Link href={`/app/${organisationSlug}/settings/billing`}>Billing</Link><Link href={`/app/${organisationSlug}/team`}>Security</Link></nav><section className="panel"><form><div className="form-section"><h2>Practice identity</h2><p>Used throughout your workspace and future client communications.</p><div className="form-grid"><div className="field"><label htmlFor="tradingName">Trading name</label><input id="tradingName" className="input" defaultValue="North Star Surveying" /></div><div className="field"><label htmlFor="email">Support email</label><input id="email" className="input" type="email" defaultValue="hello@northstarsurveying.co.uk" /></div><div className="field"><label htmlFor="region">Primary region</label><select id="region" className="input" defaultValue="South West England"><option>South West England</option><option>London</option><option>South East England</option><option>Midlands</option><option>North of England</option><option>Wales</option><option>Scotland</option><option>Northern Ireland</option></select></div><div className="field"><label>Brand colour</label><div className="colour-swatch"><i /><span>#2563EB</span></div></div></div></div><div className="form-section"><h2>Default services</h2><p>Initial fee guidance can be adjusted on each job.</p><div className="form-grid"><div className="field"><label htmlFor="service1">Service</label><input id="service1" className="input" defaultValue="Level 2 Home Survey" /></div><div className="field"><label htmlFor="fee1">Default fee</label><input id="fee1" className="input" defaultValue="£895" /></div><div className="field"><label htmlFor="service2">Service</label><input id="service2" className="input" defaultValue="Level 3 Building Survey" /></div><div className="field"><label htmlFor="fee2">Default fee</label><input id="fee2" className="input" defaultValue="£1,295" /></div></div></div><div className="form-section" style={{ display: "flex", justifyContent: "flex-end" }}><ActionButton className="button button-primary" message="Practice settings saved"><Save size={15} />Save changes</ActionButton></div></form></section></div></main>;
}
