"use client";
import { PersonalCalendars } from "./personal-calendars";
import { PersonalAvailability } from "./personal-availability";
import { DeviceNotificationSettings } from "./device-notifications";
import { emptyProfessionalDetails, type ProfessionalDetails } from "@/lib/professional-details";
import { useEffect, useState } from "react";
import dynamic from "next/dynamic";
import { PageHeader } from "./page-header";
import { useAppearance } from "./appearance-provider";
import { ReportIdentitySettings } from "./report-identity-settings";
const Identity = dynamic(() => import("@clerk/nextjs").then((m)=>m.UserProfile), {ssr:false,loading:()=> <p>Loading secure account controls…</p>});
const LiveProfile = dynamic(() => import("./personal-profile").then(m=>m.LivePersonalProfile), {ssr:false,loading:()=> <div className="settings-section" role="status">Loading your editable profile…</div>});
const PreviewProfile = dynamic(() => import("./personal-profile").then(m=>m.PreviewPersonalProfile), {ssr:false,loading:()=> <div className="settings-section" role="status">Loading your editable profile…</div>});
type Work={timezone:string;workingHours:Record<string,{start:string;end:string;closed?:boolean}>;routeOrigin:string|null;latitude:number|null;longitude:number|null};
export function AccountSettings(){const {value,update}=useAppearance();const [section,setSection]=useState("Profile");const [rics,setRics]=useState("");const [professional,setProfessional]=useState<ProfessionalDetails>(emptyProfessionalDetails);const [preview,setPreview]=useState(false);const [notifications,setNotifications]=useState<Record<string,boolean>>({});const [work,setWork]=useState<Work>({timezone:"Europe/London",workingHours:{},routeOrigin:null,latitude:null,longitude:null});const [status,setStatus]=useState("");const [busy,setBusy]=useState(false);const [loaded,setLoaded]=useState(false);
  useEffect(()=>{let active=true;fetch("/api/v1/me",{cache:"no-store"}).then(async(r)=>{const p=await r.json();if(!r.ok)throw new Error(p.error?.message??"Could not load your account.");if(active){setPreview(Boolean(p.data.preview));if(p.data.preview){try{p.data={...p.data,...JSON.parse(localStorage.getItem("surveynt:preview-account")??"{}")};}catch{}}setProfessional({...emptyProfessionalDetails,...p.data.professionalDetails});setRics(p.data.ricsNumber??"");setNotifications(p.data.notifications??{});if(p.data.work)setWork(p.data.work);setLoaded(true);if(new URLSearchParams(window.location.search).get("section")==="connections")setSection("Calendar connections");}}).catch((e)=>{if(active)setStatus(e.message);});return()=>{active=false;};},[]);
  async function save(){setBusy(true);setStatus("");try{const r=await fetch("/api/v1/me",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(section==="Professional details"?{ricsNumber:rics||null,professionalDetails:professional}:section==="Availability & location"?{work}:section==="Notifications"?{notifications}:{appearance:value})});const p=await r.json();if(!r.ok)throw new Error(p.error?.message??"Could not save settings.");if(p.meta?.persisted===false){const previous=JSON.parse(localStorage.getItem("surveynt:preview-account")??"{}");localStorage.setItem("surveynt:preview-account",JSON.stringify({...previous,...p.data}));}setStatus(p.meta?.persisted===false?"Saved on this device for preview. Sign in for cross-device settings.":"Your settings are saved.");}catch(e){setStatus((e as Error).message);}finally{setBusy(false);}}
  return <main className="page"><PageHeader title="Your account" description="Your identity, working preferences and accessibility settings."/><div className="account-grid"><nav className="account-nav" aria-label="Account sections">{["Profile","Security","Professional details","Availability & location","Appearance & accessibility","Calendar connections","Notifications"].map((s)=><button key={s} onClick={()=>setSection(s)} aria-current={s===section?"page":undefined}>{s}</button>)}</nav><section className="panel">
    {section==="Profile"?(process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY?<LiveProfile/>:<PreviewProfile/>):null}
    {section==="Security"?<div className="settings-section"><h2>Security</h2><p>Manage verified email, passwords, multi-factor authentication and active sessions. Provider-managed accounts may not have a Surveynt password.</p>{process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY?<Identity routing="hash" __experimental_startPath="/security" appearance={{elements:{navbar:{display:"none"},rootBox:{width:"100%"},cardBox:{width:"100%",boxShadow:"none"}}}}/>:<p>Live security controls require Clerk authentication. The isolated demo does not create passwords, verification emails or MFA credentials.</p>}</div>:null}
    {section==="Professional details"?<><div className="settings-section"><h2>Professional details</h2><p>Your RICS number is self-declared until separately verified.{preview?" Demo credentials are stored only on this device.":""}</p><label className="field"><span>RICS membership number</span><input value={rics} onChange={(e)=>setRics(e.target.value)} maxLength={40} autoComplete="off"/></label><h3>Drone credentials</h3><p>Self-declared references only; these entries do not verify qualification or permission to fly.</p><div className="form-grid">{([["droneOperatorId","Drone operator ID"],["droneFlyerId","Drone flyer ID"],["droneQualification","Drone qualification / licence reference"],["droneExpiry","Stated expiry date"]] as const).map(([key,label])=><label className="field" key={key}><span>{label}</span><input type={key==="droneExpiry"?"date":"text"} value={professional[key]} maxLength={key==="droneQualification"?160:100} onChange={event=>setProfessional({...professional,[key]:event.target.value})}/></label>)}</div></div><ReportIdentitySettings personal/></>:null}
    {section==="Availability & location"?<PersonalAvailability work={work} onChange={setWork}/>:null}
    {section==="Appearance & accessibility"?<div className="settings-section"><h2>Make Surveynt comfortable for you</h2><div className="form-grid"><label className="field"><span>Theme</span><select value={value.theme} onChange={(e)=>update({theme:e.target.value as typeof value.theme})}><option value="system">Use device setting</option><option value="light">Light</option><option value="dark">Dark</option></select></label><label className="field"><span>Contrast</span><select value={value.contrast} onChange={(e)=>update({contrast:e.target.value as typeof value.contrast})}><option value="standard">Standard</option><option value="high">Increased</option></select></label><label className="field"><span>Text size</span><select value={value.textSize} onChange={(e)=>update({textSize:e.target.value as typeof value.textSize})}><option value="standard">Standard</option><option value="large">Larger</option></select></label><label className="field"><span>Table density</span><select value={value.density} onChange={(e)=>update({density:e.target.value as typeof value.density})}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label></div><label className="switch-row"><input type="checkbox" checked={value.reducedMotion} onChange={(e)=>update({reducedMotion:e.target.checked})}/>Reduce non-essential motion</label><p>Survey forms retain their standard presentation and condition-rating colours.</p></div>:null}
    {section==="Calendar connections"?<PersonalCalendars/>:null}
    {section==="Notifications"?<div className="settings-section"><h2>Notifications</h2><DeviceNotificationSettings/>{["Assigned jobs","Report reviews","Appointment changes","Payment updates"].map((key)=><label className="switch-row" key={key}><input type="checkbox" checked={notifications[key]!==false} onChange={(e)=>setNotifications({...notifications,[key]:e.target.checked})}/>{key}</label>)}</div>:null}
    <div className="settings-actions"><span role="status">{status}</span>{!["Profile","Security","Calendar connections"].includes(section)?<button className="button button-primary" disabled={busy||!loaded} onClick={()=>void save()}>{busy?"Saving…":"Save preferences"}</button>:null}</div></section></div></main>;
}
