"use client";
import {WorkspaceAnchor} from "@/components/workspace-anchor";

import {workspaceFetch} from "@/lib/workspace-request";
import { useEffect,useState } from "react";
import { ShieldCheck } from "lucide-react";
import type { Capability } from "@/lib/capabilities";
export function CapabilityPanel({scope="payments"}:{scope?:"platform"|"payments"|"personal"}){
  const [rows,setRows]=useState<Capability[]>([]),[error,setError]=useState("");
  useEffect(()=>{let active=true;workspaceFetch(scope==="platform"?"/api/platform/integration-readiness":"/api/v1/capabilities",{cache:"no-store"}).then(async response=>{const payload=await response.json();if(!response.ok)throw new Error(payload.error?.message??"Readiness unavailable");if(active)setRows(payload.data.filter((row:Capability)=>scope==="platform"||scope==="personal"&&["google","microsoft"].includes(row.key)||scope==="payments"&&row.key==="payments"));}).catch(error=>{if(active)setError(error.message);});return()=>{active=false;};},[scope]);
  return <section className="settings-section"><h2><ShieldCheck size={20}/>{scope==="platform"?"Platform integration readiness":scope==="personal"?"Calendar providers":"Client payment readiness"}</h2><p>These surfaces remain in place when approved providers are activated. No credentials are displayed.</p>{error?<p role="alert">{error}</p>:null}{!rows.length&&!error?<p role="status">Checking approved capabilities…</p>:null}<div className="capability-grid">{rows.map(row=><article className="capability" key={row.key}>
    <span className="status status-blue">{row.state}</span><h3>{row.label}</h3><p>{row.detail}</p>
    {row.coverage?<p>Registered coverage: {row.coverage.length?row.coverage.join(", "):"Unknown"}</p>:null}
    {row.versions?.length?<ul>{row.versions.map(version=><li key={`${version.version}-${version.layer}`}><strong>{version.version}</strong>{version.layer?` · ${version.layer}`:""} · {version.records.toLocaleString("en-GB")} records{version.activatedAt?` · Active since ${new Date(version.activatedAt).toLocaleDateString("en-GB")}`:""}</li>)}</ul>:row.versions?<p>No active imported release. Absence of a layer is not evidence that a constraint is absent.</p>:null}
    {row.sync?<div><p>Latest import: {row.sync.status} · {row.sync.records.toLocaleString("en-GB")} records · Started {new Date(row.sync.startedAt).toLocaleDateString("en-GB")}</p><p>Capacity review: {row.sync.capacityReviewPassed?"Recorded as passed":"Not recorded as passed"}. Activation is an operator-controlled action.</p></div>:null}
    {row.connectHref?<WorkspaceAnchor className="button button-secondary" href={row.connectHref}>{row.action}</WorkspaceAnchor>:<details><summary>{row.action}</summary><p>{row.key==="hmlr"||row.key==="epc"?"Ask the Surveynt operator to verify the source, permissions and capacity. Firms cannot activate national datasets from this screen.":row.key==="payments"?"Surveynt administrators configure the separate payment provider and launch approvals. Practice owners/admins enable client payments here after approval. Subscription billing stays separate.":row.key==="quotes"?"An operator must securely configure the quote secret. A practice administrator then enables public quotes in operations settings.":row.key==="routing"?"An operator configures the production endpoint and attribution. Until then, daily routes retain visibly approximate distance and navigation links.":"Surveynt administrators configure the OAuth application, encryption key and webhook secret. Connect or reconnect appears here when setup is complete."}</p></details>}
  </article>)}</div></section>;
}
