"use client";
import {workspaceFetch} from "@/lib/workspace-request";
import {useEffect,useState} from "react";
import {useUnsavedChanges} from "./unsaved-changes";
import type {PropertyIntelligence} from "@/lib/intelligence";
type Information={label:string;value:string;source:string;retrievedAt:string|null};type Evidence={title:string;summary:string;source:string};
/** Only curated excerpts are published. Raw provider payloads never become public by default. */
export function CasePublicationEditor({jobId,propertyId,canEdit}:{jobId:string;propertyId:string;canEdit:boolean}){const [info,setInfo]=useState<Information[]>([]),[evidence,setEvidence]=useState<Evidence[]>([]),[version,setVersion]=useState(0),[intelligence,setIntelligence]=useState<PropertyIntelligence|null>(null),[status,setStatus]=useState(""),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false);useUnsavedChanges(dirty);
useEffect(()=>{let active=true;Promise.all([workspaceFetch(`/api/v1/jobs/${jobId}/client-publication`),workspaceFetch(`/api/v1/properties/${propertyId}/intelligence`)]).then(async([r,i])=>{const p=await r.json(),data=await i.json();if(active){if(r.ok&&p.data){setInfo(p.data.propertyInformation);setEvidence(p.data.evidence);setVersion(p.data.version);}if(i.ok)setIntelligence(data.data);}}).catch(()=>{if(active)setStatus("Client publication or property intelligence is unavailable.");});return()=>{active=false;};},[jobId,propertyId]);
function importContext(){const categories=intelligence?.categories??[];const information=categories.filter(c=>!c.stale&&c.fresh&&["Open Government Licence v3.0","Open Database License (ODbL) 1.0"].includes(String(c.licence.name))).map(c=>({label:c.category.replaceAll("_"," "),value:c.status==="matched"?c.records.map(r=>{const d=r.data;return Object.entries(d).filter(([key,value])=>["currentRating","potentialRating","constructionAgeBand","propertyType","name","label","price","transferDate","tenureLabel"].includes(key)&&["string","number"].includes(typeof value)).map(([key,value])=>`${key.replace(/([A-Z])/g," $1")}: ${value}`).join(" · ");}).filter(Boolean).join("; ")||"Source record available; review the property intelligence record for detail.":`${c.status.replaceAll("_"," ")}${c.message?`: ${c.message}`:""}`,source:`${c.sourceKey}${c.datasetVersion?` · dataset ${c.datasetVersion}`:""} · ${String(c.licence.attribution??c.licence.name)}`,retrievedAt:c.retrievedAt}));setInfo(information);setDirty(true);}
async function release(e:React.FormEvent){e.preventDefault();setBusy(true);try{const r=await workspaceFetch(`/api/v1/jobs/${jobId}/client-publication`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({version,propertyInformation:info,evidence})});const p=await r.json();if(!r.ok)throw Error(p.error?.message??"Release failed.");if(p.meta?.persisted===false){setStatus("Preview only. No client publication saved.");return;}setVersion(p.data.version);setDirty(false);setStatus("Reviewed information released to this client’s case link.");}catch(e){setStatus((e as Error).message);}finally{setBusy(false);}}
return <section className="panel"><header className="panel-header"><div><h2>Client-visible case record</h2><p>Review property information and evidence excerpts before releasing them to the linked client.</p></div></header><form className="panel-body stack" onSubmit={release}>{canEdit?<div className="row-actions"><button type="button" className="button button-secondary" disabled={!intelligence} onClick={importContext}>Prepare from property intelligence</button><button type="button" className="button button-quiet" onClick={()=>{setInfo(v=>[...v,{label:"",value:"",source:"",retrievedAt:null}]);setDirty(true);}}>Add information</button><button type="button" className="button button-quiet" onClick={()=>{setEvidence(v=>[...v,{title:"",summary:"",source:""}]);setDirty(true);}}>Add evidence excerpt</button></div>:null}{info.map((item,i)=><div className="form-grid" key={i}>{(["label","value","source"] as const).map(k=><label className="field" key={k}><span>{k}</span><input disabled={!canEdit} required value={item[k]} onChange={e=>{setInfo(v=>v.map((r,n)=>n===i?{...r,[k]:e.target.value}:r));setDirty(true);}}/></label>)}{canEdit?<button type="button" className="button button-quiet" onClick={()=>{setInfo(v=>v.filter((_,n)=>n!==i));setDirty(true);}}>Remove information</button>:null}</div>)}{evidence.map((item,i)=><div className="form-grid" key={i}>{(["title","summary","source"] as const).map(k=><label className="field" key={k}><span>{k}</span><textarea disabled={!canEdit} required value={item[k]} onChange={e=>{setEvidence(v=>v.map((r,n)=>n===i?{...r,[k]:e.target.value}:r));setDirty(true);}}/></label>)}{canEdit?<button type="button" className="button button-quiet" onClick={()=>{setEvidence(v=>v.filter((_,n)=>n!==i));setDirty(true);}}>Remove excerpt</button>:null}</div>)}{!info.length&&!evidence.length?<p className="muted">No information or evidence has been selected for release.</p>:null}<p className="form-help">Confirm source rights and required attribution before release. Preparation includes only fresh snapshots under recognised open licences; source restrictions still require review. Only these reviewed excerpts are shared. Professional conclusions belong in the existing report approval and issue workflow.</p><div className="form-actions"><span role="status">{status}</span>{canEdit?<button className="button button-primary" disabled={busy}>{busy?"Releasing…":"Release reviewed case information"}</button>:null}</div></form></section>;}
