"use client";
import { useCallback, useEffect, useState } from "react";
import { CalendarDays, CreditCard, FileCheck2, ShieldCheck } from "lucide-react";

type Quote = { id: string; reference: string; status: string; firstName: string | null; propertyAddress: string | null; currency: string; totalMinor: number; depositMinor: number; balanceMinor: number; balancePaid: boolean; expiresAt: string; converted: boolean; pricing: Record<string, unknown> };
const money = (minor: number, currency: string) => new Intl.NumberFormat("en-GB", { style: "currency", currency }).format(minor / 100);

export function CustomerQuotePortal({ id }: { id: string }) {
  const [token, setToken] = useState(""); const [quote, setQuote] = useState<Quote | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const request = useCallback(async (path = "", init?: RequestInit) => {
    const response = await fetch(`/api/v1/public/quotes/${id}${path}`, { ...init, headers: { "content-type": "application/json", "x-quote-token": token, ...init?.headers } });
    const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message ?? "The request could not be completed."); return payload.data;
  }, [id, token]);
  useEffect(() => { const timer = window.setTimeout(() => { const value = decodeURIComponent(location.hash.slice(1)) || sessionStorage.getItem(`surveynt:quote:${id}`) || ""; if (value) { sessionStorage.setItem(`surveynt:quote:${id}`, value); setToken(value); } else setError("Use the complete secure link from your quote email."); }, 0); return () => window.clearTimeout(timer); }, [id]);
  useEffect(() => { if (!token) return; let active = true; request().then((data) => { if (active) setQuote(data); }).catch((reason) => { if (active) setError(reason.message); }); return () => { active = false; }; }, [request, token]);
  useEffect(() => { if (!token || new URLSearchParams(location.search).get("payment") !== "pending" || quote?.converted) return; let attempts = 0; const timer = window.setInterval(() => { attempts += 1; request().then(setQuote).catch(() => undefined); if (attempts >= 15) window.clearInterval(timer); }, 2_000); return () => window.clearInterval(timer); }, [quote?.converted, request, token]);
  async function address(form: FormData) { setBusy(true); setError(""); try { setQuote(await request("", { method: "PATCH", body: JSON.stringify({ line1: form.get("line1"), city: form.get("city"), postcode: form.get("postcode") }) })); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } }
  async function checkout(purpose: "deposit" | "balance" = "deposit") { setBusy(true); setError(""); try { const result = await request("/checkout", { method: "POST", body: JSON.stringify({ purpose }) }); if (result.url) location.assign(result.url); else setQuote(await request()); } catch (reason) { setError((reason as Error).message); setBusy(false); } }
  async function appointment(form: FormData) { setBusy(true); setError(""); try { await request("/appointments", { method: "POST", body: JSON.stringify({ startsAt: new Date(String(form.get("startsAt"))).toISOString() }) }); setQuote(await request()); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } }
  if (error && !quote) return <main className="public-quote"><section className="quote-card"><ShieldCheck /><h1>Quote unavailable</h1><p>{error}</p></section></main>;
  if (!quote) return <main className="public-quote"><section className="quote-card"><p>Loading your secure quote…</p></section></main>;
  return <main className="public-quote"><section className="quote-card"><div className="quote-kicker"><FileCheck2 /> {quote.reference}</div><h1>{String(quote.pricing.service ?? "Property survey")}</h1><p className="quote-total">{money(quote.totalMinor, quote.currency)}</p><p>Deposit: <strong>{money(quote.depositMinor, quote.currency)}</strong> · Valid until {new Date(quote.expiresAt).toLocaleString("en-GB", { timeZone: "Europe/London" })}</p>{error ? <p className="form-error" role="alert">{error}</p> : null}
    {!quote.propertyAddress && quote.status !== "expired" ? <form action={address} className="quote-form"><h2>Property address</h2><label>Address<input name="line1" required maxLength={300} autoComplete="street-address" /></label><label>Town or city<input name="city" required maxLength={120} autoComplete="address-level2" /></label><label>Postcode<input name="postcode" required maxLength={12} autoComplete="postal-code" /></label><button className="button button-primary" disabled={busy}>Accept quote</button></form> : null}
    {quote.propertyAddress && !quote.converted ? <div className="quote-action"><CreditCard /><div><h2>Pay the deposit</h2><p>{quote.propertyAddress}</p></div><button className="button button-primary" onClick={() => void checkout("deposit")} disabled={busy}>Pay securely</button></div> : null}
    {quote.converted ? <><div className="quote-action"><CreditCard /><div><h2>{quote.balancePaid ? "Balance paid" : "Pay remaining balance"}</h2><p>{money(quote.balanceMinor, quote.currency)}</p></div>{quote.balancePaid ? <ShieldCheck aria-label="Payment verified" /> : <button className="button button-primary" type="button" onClick={() => void checkout("balance")} disabled={busy || quote.balanceMinor === 0}>Pay balance</button>}</div><form action={appointment} className="quote-form"><h2><CalendarDays /> Choose an appointment</h2><label>Date and time<input name="startsAt" type="datetime-local" required /></label><button className="button button-primary" disabled={busy}>Confirm appointment</button></form></> : null}
  </section></main>;
}
