"use client";
import { useEffect,useState } from "react";
import type { ComposedReport } from "@surveynt/assistant";
type Invoice={id:string;number:string;status:string;currency:string;totalMinor:number;creditedMinor?:number};
export function CustomerRecords({id,token,invoices}:{id:string;token:string;invoices:Invoice[]}){
  const [reports,setReports]=useState<{id:string;version:number;approvedAt:string;content:ComposedReport}[]>([]),[error,setError]=useState("");
  useEffect(()=>{let active=true;fetch(`/api/v1/public/quotes/${id}/reports`,{headers:{"x-quote-token":token},cache:"no-store"}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error?.message??"Reports unavailable.");if(active)setReports(p.data);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[id,token]);
  return <><section className="quote-form"><h2>Your invoices</h2>{invoices.map(i=><div className="action-row" key={i.id}><strong>{i.number}</strong><span>{new Intl.NumberFormat("en-GB",{style:"currency",currency:i.currency}).format((i.totalMinor-Number(i.creditedMinor??0))/100)} · {i.status.replaceAll("_"," ")}{Number(i.creditedMinor??0)>0?` · Credit notes ${new Intl.NumberFormat("en-GB",{style:"currency",currency:i.currency}).format(Number(i.creditedMinor)/100)}`:""}</span></div>)}{!invoices.length?<p>No invoices issued yet.</p>:null}</section><section className="quote-form"><h2>Your issued reports</h2>{error?<p role="alert">{error}</p>:null}{!reports.length?<p>Only issued, approved reports appear here. Draft inspection notes are never disclosed.</p>:null}{reports.map(r=><details key={r.id}><summary>Approved report · version {r.version} · {new Date(r.approvedAt).toLocaleDateString("en-GB")}</summary><div className="survey-workspace"><article className="report-preview"><header><h3>{r.content.title}</h3><p>{r.content.property.line1} · {r.content.jobReference}</p></header>{r.content.ratingSummary.map(g=><div className="report-ratings" key={g.rating}><strong>{g.label}</strong><span>{g.elements.map(e=>e.title).join(", ")}</span></div>)}{r.content.sections.map(s=><section key={s.key}><h4>{s.title}</h4>{s.blocks.map(b=><p key={b.id}>{b.text}</p>)}{s.elements.map(e=><div key={e.key}><h5>{e.title}</h5>{e.blocks.map(b=><p key={b.id}>{b.text}</p>)}</div>)}</section>)}{r.content.recommendations.map(b=><p key={b.id}>{b.text}</p>)}</article></div></details>)}</section></>;
}
