"use client";
import { useCallback,useEffect,useState } from "react";
import { CalendarDays,CreditCard,FileCheck2,ShieldCheck } from "lucide-react";
import { BrandMark } from "@surveynt/ui";
import dynamic from "next/dynamic";
const CustomerRecords=dynamic(()=>import("./customer-records").then(m=>m.CustomerRecords),{loading:()=> <p>Loading your records…</p>});
const PreinspectionQuestionnaire=dynamic(()=>import("./preinspection-questionnaire").then(m=>m.PreinspectionQuestionnaire),{loading:()=> <p>Loading pre-inspection information…</p>});
type Quote={id:string;reference:string;status:string;propertyAddress:string|null;city?:string|null;postcode?:string|null;address?:{line1:string;line2:string;city:string;postcode:string}|null;currency:string;totalMinor:number;depositMinor:number;balanceMinor:number;balancePaid:boolean;depositPaid:boolean;converted:boolean;demo?:boolean;expiresAt:string;pricing:Record<string,unknown>;appointment?:{startsAt:string;status:string}|null;invoices?:{id:string;number:string;status:string;currency:string;totalMinor:number}[]};
const money=(n:number,c:string)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:c}).format(n/100);
export function CustomerQuotePortal({id}:{id:string}){
  const [token,setToken]=useState("");const [quote,setQuote]=useState<Quote|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [booking,setBooking]=useState("");const [verificationPending,setVerificationPending]=useState(false);const [verificationPurpose,setVerificationPurpose]=useState("deposit");const [slots,setSlots]=useState<{startsAt:string;label:string}[]>([]);
  const request=useCallback(async(path="",init?:RequestInit)=>{const r=await fetch(`/api/v1/public/quotes/${id}${path}`,{...init,headers:{"content-type":"application/json","x-quote-token":token,...init?.headers}});const p=await r.json();if(!r.ok)throw new Error(p.error?.message??"This request could not be completed.");return p.data;},[id,token]);
  useEffect(()=>{const timer=setTimeout(()=>{const value=decodeURIComponent(location.hash.slice(1))||sessionStorage.getItem(`surveynt:quote:${id}`)||"";if(value){sessionStorage.setItem(`surveynt:quote:${id}`,value);setToken(value);history.replaceState(null,"",location.pathname+location.search);}else setError("Use your complete secure customer link.");},0);return()=>clearTimeout(timer);},[id]);
  useEffect(()=>{if(!token)return;let active=true;request().then(q=>{if(active)setQuote(q);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[token,request]);
  const appointmentStatus=quote?.appointment?.status;
  useEffect(()=>{if(!quote?.converted||!quote.depositPaid||["expired","cancelled"].includes(quote.status)||appointmentStatus&&appointmentStatus!=="cancelled")return;let active=true;request("/appointments").then(s=>{if(active)setSlots(s);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[quote?.converted,quote?.depositPaid,quote?.status,appointmentStatus,request]);
  useEffect(()=>{if(!token||(!verificationPending&&new URLSearchParams(location.search).get("payment")!=="pending"))return;let attempts=0;const timer=setInterval(()=>{attempts++;request().then(q=>{setQuote(q);if(verificationPending&&(verificationPurpose==="balance"?q.balancePaid:q.depositPaid))setVerificationPending(false);}).catch(()=>undefined);if(attempts>=15)clearInterval(timer);},2000);return()=>clearInterval(timer);},[token,request,verificationPending,verificationPurpose]);
  async function run(path:string,body:unknown){setBusy(true);setError("");try{const result=await request(path,{method:path?"POST":"PATCH",body:JSON.stringify(body)});if(result.url)location.assign(result.url);else{if(result.pending){setVerificationPurpose((body as {purpose?:string}).purpose==="balance"?"balance":"deposit");setVerificationPending(true);}if(path==="/appointments")setBooking(new Date(result.startsAt).toLocaleString("en-GB",{timeZone:"Europe/London"}));setQuote(await request());}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  if(!quote)return <main className="public-quote"><section className="quote-card"><BrandMark/><ShieldCheck/><h1>{error?"Customer link unavailable":"Loading your secure customer area…"}</h1><p role={error?"alert":"status"}>{error||"Checking your access."}</p></section></main>;
  const closed=["expired","cancelled"].includes(quote.status);
  const accepted = ["accepted", "converted"].includes(quote.status);
  const confirmedBooking=booking||(quote.appointment&&quote.appointment.status!=="cancelled"?new Date(quote.appointment.startsAt).toLocaleString("en-GB",{timeZone:"Europe/London"}):"");
  return <main className="public-quote"><section className="quote-card"><BrandMark/>{quote.demo?<p className="demo-banner">Stakeholder demo · fictional property · no real charges or external messages</p>:null}<div className="quote-kicker"><FileCheck2/>{quote.reference}</div><h1>{String(quote.pricing.service??"Property survey")}</h1><p className="quote-total">{money(quote.totalMinor,quote.currency)}</p><p>Deposit {money(quote.depositMinor,quote.currency)} · Valid until {new Date(quote.expiresAt).toLocaleDateString("en-GB")}</p><ol className="customer-progress"><li>Quote {accepted?"accepted":"ready"}</li><li>Deposit {quote.converted?(quote.depositPaid?"verified":"refund recorded"):"awaiting payment"}</li><li>{confirmedBooking?"Appointment confirmed":"Appointment selection"}</li><li>Report review and issue</li></ol>{verificationPending?<p role="status">Payment is awaiting secure verification. No further checkout has been created. Your payment status updates when the verified provider event arrives.</p>:null}{error?<p className="form-error" role="alert">{error}</p>:null}{closed?<p role="status">This quote is {quote.status}. Contact your practice for a new quote.</p>:null}
    {!closed&&!accepted?<form className="quote-form" action={form=>run("",{line1:form.get("line1"),city:form.get("city"),postcode:form.get("postcode")})}><h2>Confirm your property</h2><label>Address<input name="line1" defaultValue={[quote.address?.line1, quote.address?.line2].filter(Boolean).join(", ")} required maxLength={300} autoComplete="street-address"/></label><label>Town or city<input name="city" defaultValue={quote.city ?? quote.address?.city ?? ""} required maxLength={120} autoComplete="address-level2"/></label><label>Postcode<input name="postcode" defaultValue={quote.postcode ?? quote.address?.postcode ?? ""} required maxLength={12} autoComplete="postal-code"/></label><button className="button button-primary" disabled={busy}>Accept quote</button></form>:null}
    {!closed&&accepted&&quote.propertyAddress&&!quote.converted?<div className="quote-action"><CreditCard/><div><h2>{quote.demo?"Simulate deposit":"Pay the deposit"}</h2><p>{quote.propertyAddress}</p></div><button className="button button-primary" disabled={busy} onClick={()=>void run("/checkout",{purpose:"deposit"})}>{quote.demo?"Simulate success":"Pay securely"}</button>{quote.demo?<button className="button button-quiet" disabled={busy} onClick={()=>void run("/checkout",{purpose:"deposit",scenario:"failure"})}>Test failure</button>:null}</div>:null}
    {quote.converted&&!closed?<><div className="quote-action"><CreditCard/><div><h2>{quote.balancePaid?"Balance paid":"Remaining balance"}</h2><p>{money(quote.balanceMinor,quote.currency)}</p></div>{quote.balancePaid?<ShieldCheck aria-label="Payment verified"/>:<button className="button button-primary" disabled={busy} onClick={()=>void run("/checkout",{purpose:"balance"})}>{quote.demo?"Simulate balance payment":"Pay balance"}</button>}</div><form className="quote-form" action={form=>run("/appointments",{startsAt:form.get("startsAt")})}><h2><CalendarDays/>Choose a visit</h2>{confirmedBooking?<p role="status">Your visit is confirmed: {confirmedBooking}</p>:<><label>Available appointments<select name="startsAt" required defaultValue=""><option value="" disabled>Select a bookable time</option>{slots.map(s=><option key={s.startsAt} value={s.startsAt}>{s.label}</option>)}</select></label><p>Europe/London times. Availability is rechecked when you book.</p><button className="button button-primary" disabled={busy||!slots.length}>Confirm appointment</button></>}</form></>:null}
    {quote.converted?<><PreinspectionQuestionnaire quoteId={id} token={token}/><CustomerRecords id={id} token={token} invoices={quote.invoices??[]}/></>:null}
  </section></main>;
}
