"use client";
import { londonDayLabel } from "@/lib/day-label";
import { useEffect, useState } from "react";
import dynamic from "next/dynamic";
import Link from "next/link";
import { Navigation, RefreshCw, Route, ArrowRight } from "lucide-react";
import { PropertyArtwork } from "./property-artwork";
import { IntelligencePanel } from "./intelligence-panel";
import { legForVisit, plannedArrival, type FieldworkRoute } from "@/lib/fieldwork";
import type { PropertyMapView } from "@/lib/property-map";
import "./fieldwork.css";
const FieldworkMap=dynamic(()=>import("./fieldwork-map").then(m=>m.FieldworkMap),{ssr:false,loading:()=> <div className="fieldwork-map-loading" role="status">Loading fieldwork map…</div>});
const time=(date:string)=>new Date(date).toLocaleTimeString("en-GB",{timeZone:"Europe/London",hour:"2-digit",minute:"2-digit"});
export function DailyRoutes({slug}:{slug:string}){
 const [date,setDate]=useState(()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/London"}).format(new Date()));
 const [surveyor,setSurveyor]=useState(""),[data,setData]=useState<FieldworkRoute|null>(null),[selected,setSelected]=useState(""),[error,setError]=useState(""),[refresh,setRefresh]=useState(0),[loading,setLoading]=useState(true),[journey,setJourney]=useState(false),[layers,setLayers]=useState<PropertyMapView|null>(null);
 useEffect(()=>{
  const controller=new AbortController();
  fetch(`/api/v1/routes/daily?date=${date}${surveyor?`&surveyor=${encodeURIComponent(surveyor)}`:""}`,{cache:"no-store",signal:controller.signal}).then(async r=>{const p=await r.json();if(!r.ok)throw Error(p.error?.message??"Fieldwork could not be loaded.");return p.data as FieldworkRoute;}).then(d=>{setData(d);setSelected(old=>d.stops.some(s=>s.id===old)?old:d.stops[0]?.id??"");setError("");setLoading(false);}).catch(e=>{if(!controller.signal.aborted){setData(null);setError(e.message);setLoading(false);}});
  return()=>controller.abort();
 },[date,surveyor,refresh]);
 const stop=data?.stops.find(s=>s.id===selected),index=data?.stops.findIndex(s=>s.id===selected)??-1;
 const propertyId=stop?.propertyId;
 useEffect(()=>{if(!propertyId)return;const controller=new AbortController();fetch(`/api/v1/properties/${encodeURIComponent(propertyId)}/map`,{cache:"no-store",signal:controller.signal}).then(async r=>{if(!r.ok)throw Error();const payload=await r.json();return payload.meta?.demo?{...payload.data,layers:[],notChecked:[{label:"Reference overlays",reason:"Local demonstration; no live flood, title or heritage geometries"}]}:payload.data;}).then(setLayers).catch(()=>{if(!controller.signal.aborted)setLayers(null);});return()=>controller.abort();},[propertyId,date,surveyor,refresh]);
 function select(id:string){if(data?.stops.find(s=>s.id===id)?.propertyId!==propertyId)setLayers(null);setSelected(id);}
 const leg=data&&index>=0?legForVisit(data,index):null;
 return <section className="fieldwork" aria-label="Fieldwork planner">
  <div className="fieldwork-heading"><div><span className="eyebrow">FIELD OPERATIONS</span><h2><Route size={21}/>Inspection day</h2><p>Your inspections, travel and property evidence in one place.</p></div><div className="fieldwork-filters"><label className="field"><span>Visit date</span><input type="date" value={date} onChange={e=>{setLoading(true);setData(null);setLayers(null);setDate(e.target.value);}}/></label>{data?.surveyors.length?<label className="field"><span>Surveyor</span><select value={data.selectedSurveyorId??""} onChange={e=>{setLoading(true);setData(null);setLayers(null);setSurveyor(e.target.value);}}>{data.surveyors.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>:null}<button className="button button-secondary" aria-label="Refresh fieldwork" onClick={()=>{setLoading(true);setData(null);setLayers(null);setRefresh(n=>n+1);}}><RefreshCw size={16}/></button></div></div>
  {error?<div className="panel-body" role="alert">{error}</div>:null}{loading?<p role="status">Loading your visits…</p>:null}
  {data?<><div className="fieldwork-summary"><div><span>Confirmed visits</span><strong>{data.stops.length}</strong></div><div><span>Road distance</span><strong>{data.provider.distanceMetres!=null?`${(data.provider.distanceMetres/1609.344).toFixed(1)} mi`:"Not available"}</strong></div><div><span>Estimated driving</span><strong>{data.provider.durationSeconds!=null?`${Math.ceil(data.provider.durationSeconds/60)} min`:"Not available"}</strong></div><div><span>Routing</span><strong>{data.provider.status.replaceAll("_"," ")}</strong><small>{data.provider.attribution??"Provider setup required"}</small></div></div>
   <div className="fieldwork-mode"><div><button aria-pressed={!journey} onClick={()=>setJourney(false)}>Day overview</button><button aria-pressed={journey} onClick={()=>setJourney(true)}>Journey</button></div><span>Live traffic <strong>Setup required</strong></span></div>
   {!data.stops.length?<div className="panel empty-state"><strong>No confirmed inspections on this date</strong><span>Book and assign an appointment in Calendar to add it to fieldwork.</span><Link className="button button-secondary" href={`/app/${slug}/calendar`}>Open calendar</Link></div>:<div className="fieldwork-grid">
    <aside className="panel fieldwork-itinerary" aria-label="Inspection itinerary"><header><span className="eyebrow">YOUR ITINERARY</span><h3>{londonDayLabel(`${date}T12:00:00Z`, "long")}</h3><small>Appointment order is preserved</small></header>{data.stops.map((s,i)=><button className="fieldwork-stop" key={s.id} aria-pressed={s.id===selected} onClick={()=>select(s.id)}><span className="fieldwork-number">{i+1}</span><span><small>{time(s.startsAt)}–{time(s.endsAt)}</small><strong>{s.address}</strong><span>{s.serviceName}</span><small>{s.clientName} · {s.reference}</small>{!s.coordinates?<small>Location not resolved</small>:null}</span></button>)}</aside>
    <FieldworkMap route={data} selected={selected} onSelect={select} journey={journey} evidence={layers}/>
    {stop?<aside className="panel fieldwork-detail" aria-label="Selected inspection"><header><span className="eyebrow">SELECTED INSPECTION</span><small>{index+1} / {data.stops.length}</small></header><PropertyArtwork propertyType={stop.propertyType}/><div className="fieldwork-detail-body"><span className="eyebrow">{stop.serviceName}</span><h3>{stop.address}</h3><strong>{stop.clientName}</strong><p>{time(stop.startsAt)}–{time(stop.endsAt)} · {stop.surveyorName}</p><dl><dt>Location precision</dt><dd>{stop.precision.replaceAll("_"," ")}</dd><dt>Drive from previous stop</dt><dd>{leg?`${Math.ceil(leg.durationSeconds/60)} min · ${(leg.distanceMetres/1609.344).toFixed(1)} mi estimate`:"Not available"}</dd></dl><div className="fieldwork-links"><Link className="button button-primary" href={`/app/${slug}/jobs/${stop.jobId}`}>Open job <ArrowRight size={16}/></Link><Link className="button button-secondary" href={`/app/${slug}/properties/${stop.propertyId}`}>Property record</Link><a className="button button-secondary" href={stop.openInMapsUrl} target="_blank" rel="noopener noreferrer"><Navigation size={15}/>Navigate</a></div><p className="form-help">External records are context, not inspection findings. Nothing is applied to the survey automatically.</p></div><IntelligencePanel key={stop.propertyId} propertyId={stop.propertyId} canRefresh={false} title="Property intelligence"/></aside>:null}
   </div>}
   {data.stops.length>1?<section className="panel fieldwork-travel" aria-label="Travel between inspections"><header><h3>Travel between inspections</h3><small>Based on scheduled finishes · not live traffic</small></header><div>{data.stops.map((s,i)=>{const leg=legForVisit(data,i),arrival=plannedArrival(data,i);if(i===0&&!data.origin)return null;return <button key={s.id} aria-pressed={s.id===selected} onClick={()=>select(s.id)}><strong>{i===0?"Base":data.stops[i-1].reference} → {s.reference}</strong><span>{leg?`${Math.ceil(leg.durationSeconds/60)} min · ${(leg.distanceMetres/1609.344).toFixed(1)} mi`:"Road estimate unavailable"}</span><small>{arrival?`Planned arrival ${time(arrival)}`:i===0?"Departure time not recorded":"No ETA available"}</small></button>;})}</div></section>:null}
   <p className="form-help">Road estimates are not live traffic. Journey playback is a planning animation, not GPS tracking. Approximate positions, building heights and indicative boundaries are not surveyed measurements.</p>
  </>:null}
 </section>;
}
