"use client";
import { useState } from "react";
import { Upload } from "lucide-react";
import { useRouter } from "next/navigation";
export function DocumentUploader({replaceId,expectedChecksum}:{replaceId?:string;expectedChecksum?:string}={}){
  const router=useRouter(),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  async function upload(formData:FormData){setBusy(true);setMessage("");try{const response=await fetch("/api/v1/documents",{method:"POST",body:formData}),payload=await response.json();if(!response.ok)throw new Error(payload.error?.message??"Upload failed.");setMessage(replaceId?"Replacement saved. The previous original is retained.":"Document uploaded with practice retention policy.");router.refresh();}catch(error){setMessage((error as Error).message??"Connection lost. Check the document register before retrying.");}finally{setBusy(false);}}
  return <form action={upload} className="panel-body form-grid">{replaceId?<><input type="hidden" name="replaceId" value={replaceId}/><input type="hidden" name="expectedChecksum" value={expectedChecksum}/><p>The previous original remains retained. Job/report links, access classification and retention are preserved. Legal-held files cannot be replaced.</p></>:<label className="field"><span>Category</span><select name="category"><option value="legal">Legal file</option><option value="retained_report">Retained report</option><option value="compliance">Compliance record</option><option value="correspondence">Correspondence</option></select></label>}<label className="field"><span>{replaceId?"Replacement file":"File"}</span><input type="file" name="file" required accept=".pdf,.docx,.txt,.jpg,.jpeg,.png"/></label><button className="button button-primary" disabled={busy}><Upload size={16}/>{busy?"Uploading…":replaceId?"Save retained replacement":"Upload securely"}</button><span role="status">{message}</span></form>;
}
