import Link from "next/link";
import { CalendarDays, CirclePoundSterling, FileCheck2, FolderLock, Map, SearchCheck, TrendingUp, Users } from "lucide-react";
import { PageHeader } from "./page-header";
import type { FirmOperationsData } from "@/lib/firm-operations";
import { DocumentUploader } from "./document-uploader";
import { OperationsCalendar } from "./operations-calendar";

type Section = "calendar" | "customers" | "routes" | "finance" | "performance" | "report-templates" | "documents";
const money = (minor: number, currency = "GBP") => new Intl.NumberFormat("en-GB", { style: "currency", currency }).format(minor / 100);
const dateTime = (value: Date) => value.toLocaleString("en-GB", { dateStyle: "medium", timeStyle: "short", timeZone: "Europe/London" });

const copy: Record<Section, { title: string; description: string; icon: typeof CalendarDays }> = {
  calendar: { title: "Calendar & scheduling", description: "Appointments, availability and external calendar conflicts.", icon: CalendarDays },
  customers: { title: "Customers & quotes", description: "Secure quotes, customer details, acceptance and deposit status.", icon: Users },
  routes: { title: "Mission control", description: "Daily visits in appointment order with location confidence and navigation links.", icon: Map },
  finance: { title: "Finance & ledger", description: "Invoices, verified payments, refunds and firm liabilities.", icon: CirclePoundSterling },
  performance: { title: "Performance", description: "Conversion, workload and revenue indicators from audited operational records.", icon: TrendingUp },
  "report-templates": { title: "Report templates", description: "Approved wording and report assembly resources used by Surveynt reports.", icon: FileCheck2 },
  documents: { title: "Documents", description: "Retained reports, legal records, retention dates and legal holds.", icon: FolderLock },
};

export function FirmOperationsView({ section, slug, data }: { section: Section; slug: string; data: FirmOperationsData }) {
  const heading = copy[section];
  const paid = data.finance.filter(({ payment }) => payment?.status === "succeeded").reduce((sum, { payment }) => sum + (payment?.amountMinor ?? 0), 0);
  const outstanding = data.finance.filter(({ invoice }) => invoice.status === "open" || invoice.status === "part_paid" || invoice.status === "overdue").reduce((sum, { invoice, payment }) => sum + Math.max(0, invoice.totalMinor - (payment?.status === "succeeded" ? payment.amountMinor - payment.refundedMinor : 0)), 0);
  const converted = data.quotes.filter((quote) => quote.status === "converted").length;
  return <main className="page"><PageHeader eyebrow="Firm operations" title={heading.title} description={heading.description} />
    {section === "customers" ? <section className="panel"><div className="panel-header"><div><h2>Quote register</h2><p>Customer statements remain unverified until reviewed by a surveyor.</p></div></div>{data.quotes.length ? <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Reference</th><th>Customer</th><th>Total</th><th>Status</th><th>Expires</th></tr></thead><tbody>{data.quotes.map((quote) => <tr key={quote.id}><td><strong>{quote.reference}</strong></td><td>{[quote.firstName, quote.lastName].filter(Boolean).join(" ") || quote.email || "Details pending"}</td><td>{money(quote.totalMinor, quote.currency)}</td><td><span className="status-dot blue">{quote.status.replaceAll("_", " ")}</span></td><td>{quote.expiresAt.toLocaleDateString("en-GB")}</td></tr>)}</tbody></table></div> : <Empty icon={SearchCheck} title="No customer quotes" text="Quotes created through the public adviser will appear here." />}</section> : null}
    {section === "calendar" ? <OperationsCalendar appointments={data.appointments} slug={slug} /> : null}
    {section === "finance" ? <><section className="metric-grid"><Metric label="Verified receipts" value={money(paid)} /><Metric label="Outstanding" value={money(outstanding)} /><Metric label="Invoices" value={String(data.finance.length)} /></section><section className="panel"><div className="panel-header"><div><h2>Invoice ledger</h2><p>Stripe events—not browser redirects—confirm payments.</p></div></div>{data.finance.length ? <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Invoice</th><th>Total</th><th>Invoice status</th><th>Payment</th></tr></thead><tbody>{data.finance.map(({ invoice, payment }) => <tr key={invoice.id}><td><strong>{invoice.number}</strong></td><td>{money(invoice.totalMinor, invoice.currency)}</td><td>{invoice.status}</td><td>{payment?.status ?? "Not received"}</td></tr>)}</tbody></table></div> : <Empty icon={CirclePoundSterling} title="No financial records" text="Invoices and verified client payments will appear here." />}</section></> : null}
    {section === "performance" ? <><section className="metric-grid"><Metric label="Quotes" value={String(data.quotes.length)} /><Metric label="Converted" value={String(converted)} /><Metric label="Conversion" value={data.quotes.length ? `${Math.round(converted / data.quotes.length * 100)}%` : "—"} /><Metric label="Verified receipts" value={money(paid)} /></section><section className="panel"><Empty icon={TrendingUp} title="Auditable practice indicators" text="Performance is calculated from native quotes, jobs and verified payment records; no data is inferred from missing events." /></section></> : null}
    {section === "routes" ? <section className="panel"><div className="panel-header"><div><h2>Scheduled stops</h2><p>Route calculations require a configured production routing provider. Property coordinates remain visibly approximate until verified.</p></div></div>{data.appointments.length ? <ol className="queue-list">{data.appointments.map((appointment, index) => <li className="queue-item" key={appointment.id}><span className="queue-line" /><div><strong>{index + 1}. {dateTime(appointment.startsAt)}</strong><span>Job {appointment.jobId} · location verification required</span></div></li>)}</ol> : <Empty icon={Map} title="No route to calculate" text="Confirmed appointments will be ordered here by visit time." />}</section> : null}
    {section === "report-templates" ? <section className="panel"><Empty icon={FileCheck2} title="Templates use the existing report engine" text="Manage approved clauses in the wording library; assembled report versions retain their approvals and evidence." /><div className="panel-body"><Link className="button button-primary" href={`/app/${slug}/wording`}>Open wording library</Link></div></section> : null}
    {section === "documents" ? <section className="panel"><div className="panel-header"><div><h2>Protected document register</h2><p>Checksummed private originals with retention and legal-hold controls.</p></div></div><DocumentUploader />{data.documents.length ? <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Name</th><th>Category</th><th>Size</th><th>Protection</th></tr></thead><tbody>{data.documents.map((document) => <tr key={document.id}><td><a href={`/api/v1/documents/${document.id}`}><strong>{document.name}</strong></a><span className="cell-sub">SHA-256 {document.checksum.slice(0, 12)}…</span></td><td>{document.category.replaceAll("_", " ")}</td><td>{Math.ceil(document.sizeBytes / 1024)} KB</td><td>{document.legalHold ? "Legal hold" : document.retentionUntil ? `Retain to ${document.retentionUntil.toLocaleDateString("en-GB")}` : "Practice policy"}</td></tr>)}</tbody></table></div> : <Empty icon={FolderLock} title="No retained documents" text="Survey evidence remains in its existing media store." />}</section> : null}
  </main>;
}

function Empty({ icon: Icon, title, text }: { icon: typeof CalendarDays; title: string; text: string }) { return <div className="empty-state"><Icon size={28} color="#3b82f6" /><strong>{title}</strong><span>{text}</span></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="metric"><div className="metric-head"><span>{label}</span></div><div className="metric-value">{value}</div></div>; }
