"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
type Payment={id:string;amountMinor:number;refundedMinor:number;status:string;stripeCheckoutSessionId:string|null};
export function InvoiceActions({id,status:invoiceStatus,currency,payments,canManage}:{id:string;status:string;currency:string;payments:Payment[];canManage:boolean}){
  const router=useRouter(),[status,setStatus]=useState(""),[busy,setBusy]=useState(false),[lines,setLines]=useState<{id:string;description:string;quantity:number;unitAmountMinor:number;vatBasisPoints:number}[]|null>(null);
  const money=(minor:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency}).format(minor/100);
  async function detail(){try{const response=await fetch("/api/v1/finance/invoices/"+id,{cache:"no-store"}),payload=await response.json();if(!response.ok)throw new Error(payload.error?.message);setLines(payload.data.lines);}catch(error){setStatus((error as Error).message);}}
  async function act(path:string,body:unknown){setBusy(true);try{const response=await fetch(path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),payload=await response.json();if(!response.ok)throw new Error(payload.error?.message??"Action could not be completed.");setStatus(payload.meta?.pendingWebhookConfirmation?"Refund requested. Awaiting verified payment event.":"Change recorded in the ledger.");router.refresh();}catch(error){setStatus((error as Error).message);}finally{setBusy(false);}}
  return <details onToggle={event=>{if(event.currentTarget.open&&lines===null)void detail();}}><summary>Invoice & payments</summary>{lines?<ul>{lines.map(line=><li key={line.id}>{line.description} · {line.quantity} × {money(line.unitAmountMinor)} · VAT {(line.vatBasisPoints/100).toFixed(2)}%</li>)}</ul>:<p>Expand to load invoice lines.</p>}<p>{payments.length} payment records</p>{payments.map(payment=><div key={payment.id}><p>{payment.status.replaceAll("_"," ")} · Received {money(payment.amountMinor)} · Refunded {money(payment.refundedMinor)}</p>{canManage&&["succeeded","partially_refunded"].includes(payment.status)&&payment.amountMinor>payment.refundedMinor?<form action={form=>{const amountMinor=Math.round(Number(form.get("amount"))*100);if(confirm("Record a refund of "+money(amountMinor)+"?"))void act(payment.stripeCheckoutSessionId?.startsWith("demo_")?"/api/v1/demo":"/api/v1/finance/payments/"+payment.id+"/refund",payment.stripeCheckoutSessionId?.startsWith("demo_")?{action:"refund",requestId:crypto.randomUUID(),paymentId:payment.id,amountMinor}:{amountMinor});}}><label className="field"><span>Refund amount ({currency})</span><input name="amount" type="number" min="0.01" max={(payment.amountMinor-payment.refundedMinor)/100} step="0.01" required/></label><button className="button button-secondary" disabled={busy}>{payment.stripeCheckoutSessionId?.startsWith("demo_")?"Simulate refund":"Request refund"}</button></form>:null}</div>)}
  {canManage&&invoiceStatus==="draft"?<button className="button button-primary" disabled={busy} onClick={()=>{if(confirm("Issue this reviewed invoice? Its amounts will remain immutable."))void act("/api/v1/finance/invoices/"+id,{action:"issue"});}}>Issue reviewed invoice</button>:null}
  {canManage&&invoiceStatus!=="void"&&!payments.some(payment=>["succeeded","partially_refunded","refunded"].includes(payment.status))?<button className="button button-quiet" disabled={busy} onClick={()=>{if(confirm("Void this unpaid invoice?"))void act("/api/v1/finance/invoices/"+id,{action:"void"});}}>Void unpaid invoice</button>:null}<p role="status">{status}</p></details>;
}
type LedgerEntry={id:string;currency:string;amountMinor:number;entryType:string;createdAt:string};
export function SettlementControl(){
  const router=useRouter();const [status,setStatus]=useState(""),[busy,setBusy]=useState(false),[ledger,setLedger]=useState<LedgerEntry[]|null>(null),[selected,setSelected]=useState<string[]>([]);
  const rows=ledger?.filter(row=>selected.includes(row.id))??[],currency=rows[0]?.currency??ledger?.[0]?.currency??"GBP",total=rows.reduce((sum,row)=>sum+row.amountMinor,0);
  const money=(minor:number,code=currency)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:code}).format(minor/100);
  async function review(){setBusy(true);setStatus("");try{const response=await fetch("/api/v1/finance/settlements",{cache:"no-store"}),payload=await response.json();if(!response.ok)throw new Error(payload.error?.message);const entries=payload.data as LedgerEntry[];setLedger(entries);setSelected(entries.filter(row=>row.currency===entries[0]?.currency).slice(0,1000).map(row=>row.id));if(!entries.length)setStatus("No unsettled entries.");}catch(error){setStatus((error as Error).message);}finally{setBusy(false);}}
  async function settle(form:FormData){setBusy(true);try{
    const amountMinor=Math.round(Number(form.get("amount"))*100);
    if(!rows.length||rows.length>1000||new Set(rows.map(row=>row.currency)).size!==1||amountMinor!==total||total<=0)throw new Error("The completed amount must match a positive, single-currency selection of up to 1,000 entries.");
    if(!confirm("Record this externally completed settlement of "+money(total)+"? No money will be transferred."))return;
    const response=await fetch("/api/v1/finance/settlements",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({reference:form.get("reference"),settledAt:new Date(String(form.get("date"))+"T12:00:00Z").toISOString(),expectedTotalMinor:total,ledgerEntryIds:selected,evidence:{note:form.get("evidence")}})}),payload=await response.json();
    if(!response.ok)throw new Error(payload.error?.message);setStatus("Externally completed settlement recorded. No funds were transferred.");setLedger(null);setSelected([]);router.refresh();
  }catch(error){setStatus((error as Error).message);}finally{setBusy(false);}}
  return <details className="panel action-panel"><summary>Record an externally completed settlement</summary><p>No automated payouts are initiated. Review the exact ledger entries against the external settlement evidence before recording.</p><button className="button button-secondary" disabled={busy} onClick={()=>void review()}>Review unsettled entries</button>{ledger?.length?<><p>Selected: {rows.length} entries · {money(total)}</p><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Select</th><th>Entry</th><th>Currency</th><th>Amount</th></tr></thead><tbody>{ledger.map(row=><tr key={row.id}><td><input type="checkbox" aria-label={"Select "+row.entryType+" "+row.id} checked={selected.includes(row.id)} onChange={event=>setSelected(ids=>event.target.checked?[...ids,row.id]:ids.filter(id=>id!==row.id))}/></td><td>{row.entryType.replaceAll("_"," ")}<span className="cell-sub">{new Date(row.createdAt).toLocaleDateString("en-GB")}</span></td><td>{row.currency}</td><td>{money(row.amountMinor,row.currency)}</td></tr>)}</tbody></table></div><form action={settle}><div className="form-grid"><label className="field"><span>Bank or settlement reference</span><input name="reference" required minLength={3} maxLength={120}/></label><label className="field"><span>Completion date</span><input name="date" type="date" required/></label><label className="field"><span>Completed amount ({currency})</span><input name="amount" type="number" min="0.01" step="0.01" required/></label><label className="field"><span>Supporting evidence reference</span><input name="evidence" required maxLength={1000}/></label></div><button className="button button-primary" disabled={busy||total<=0}>Record completed settlement</button></form></>:null}<p role="status">{status}</p></details>;
}
