"use client";
import {workspaceFetch} from "@/lib/workspace-request";
import { useState } from "react";
import { useRouter } from "next/navigation";
type Line={id:string;description:string;quantity:number;amount:string;vat:number};
const newLine=():Line=>({id:crypto.randomUUID(),description:"",quantity:1,amount:"",vat:2000});
export function InvoiceCreator(){
  const router=useRouter(),[open,setOpen]=useState(false),[lines,setLines]=useState<Line[]>(()=>[newLine()]),[requestId,setRequestId]=useState(()=>crypto.randomUUID()),[busy,setBusy]=useState(false),[status,setStatus]=useState("");
  function update(id:string,changes:Partial<Line>){setLines(rows=>rows.map(row=>row.id===id?{...row,...changes}:row));}
  async function create(form:FormData){setBusy(true);setStatus("");try{
    const due=String(form.get("due")),response=await workspaceFetch("/api/v1/finance/invoices",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({requestId,currency:form.get("currency"),dueAt:due?new Date(due+"T12:00:00Z").toISOString():null,lines:lines.map(line=>({description:line.description,quantity:line.quantity,unitAmountMinor:Math.round(Number(line.amount)*100),vatBasisPoints:line.vat}))})}),payload=await response.json();
    if(!response.ok)throw new Error(payload.error?.message??"Invoice could not be created.");setStatus("Draft invoice created. Review its lines before issuing; no checkout or payment was initiated.");setOpen(false);router.refresh();
  }catch(error){setStatus((error as Error).message);}finally{setBusy(false);}}
  return <section className="panel action-panel"><button className="button button-primary" onClick={()=>{if(!open){setRequestId(crypto.randomUUID());setLines([newLine()]);setStatus("");}setOpen(!open);}}>{open?"Close invoice form":"Create invoice"}</button>{open?<form action={create}><h2>New draft invoice</h2><p>Amounts are stored in integer minor units. VAT is calculated per line; review treatment before issue.</p><div className="form-grid"><label className="field"><span>Currency</span><select name="currency"><option>GBP</option><option>EUR</option><option>USD</option></select></label><label className="field"><span>Due date</span><input type="date" name="due"/></label></div>{lines.map((line,index)=><fieldset className="form-grid" key={line.id}><legend>Line {index+1}</legend><label className="field"><span>Description</span><input value={line.description} maxLength={500} required onChange={event=>update(line.id,{description:event.target.value})}/></label><label className="field"><span>Quantity</span><input type="number" min={1} max={1000} step={1} value={line.quantity} required onChange={event=>update(line.id,{quantity:Number(event.target.value)})}/></label><label className="field"><span>Unit amount</span><input type="number" min="0.01" max="1000000" step="0.01" value={line.amount} required onChange={event=>update(line.id,{amount:event.target.value})}/></label><label className="field"><span>VAT rate</span><select value={line.vat} onChange={event=>update(line.id,{vat:Number(event.target.value)})}><option value={2000}>20%</option><option value={500}>5%</option><option value={0}>0% — check treatment</option></select></label>{lines.length>1?<button type="button" className="button button-quiet" onClick={()=>setLines(rows=>rows.filter(row=>row.id!==line.id))}>Remove this line</button>:null}</fieldset>)}<div className="action-row"><button type="button" className="button button-secondary" disabled={lines.length>=50} onClick={()=>setLines(rows=>[...rows,newLine()])}>Add line</button><button className="button button-primary" disabled={busy}>Save draft invoice</button></div></form>:null}<p role="status">{status}</p></section>;
}
