"use client";
import {workspaceFetch} from "@/lib/workspace-request";
import {useState} from "react";
import Link from "@/components/workspace-link";
import type {businessLocations} from "@surveynt/db";
import {useUnsavedChanges} from "./unsaved-changes";
type Location=typeof businessLocations.$inferSelect;
export function LocationsManager({initial,canEdit,slug}:{initial:Location[];canEdit:boolean;slug:string}){const [locations,setLocations]=useState(initial),[draft,setDraft]=useState({id:"",name:"",address:"",latitude:"",longitude:"",active:true,version:1}),[dirty,setDirty]=useState(false),[status,setStatus]=useState("");useUnsavedChanges(dirty);async function save(e:React.FormEvent){e.preventDefault();try{const r=await workspaceFetch("/api/v1/locations",{method:draft.id?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...draft,latitude:draft.latitude?Number(draft.latitude):null,longitude:draft.longitude?Number(draft.longitude):null})});const p=await r.json();if(!r.ok)throw Error(p.error?.message??"Location could not be saved.");if(p.meta?.persisted===false){setStatus("Demo only: location was not persisted.");return;}setLocations(v=>[...v.filter(l=>l.id!==p.data.id),p.data]);setDirty(false);setDraft({id:"",name:"",address:"",latitude:"",longitude:"",active:true,version:1});setStatus("Location saved.");}catch(e){setStatus((e as Error).message);}}
return <div className="workspace-grid"><section className="panel"><header className="panel-header"><h2>Business locations</h2><Link href={`/app/${slug}/routes`}>Open route planner</Link></header><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Location</th><th>Mapping</th><th>Status</th><th/></tr></thead><tbody>{locations.map(l=><tr key={l.id}><td><strong>{l.name}</strong><span className="cell-sub">{l.address}</span></td><td>{l.latitude!=null?`${l.latitude}, ${l.longitude}`:"Coordinates required"}</td><td>{l.active?"Active":"Inactive"}</td><td>{canEdit?<button className="button button-quiet" onClick={()=>{setDraft({...l,latitude:String(l.latitude??""),longitude:String(l.longitude??"")});setDirty(false);}}>Edit</button>:null}</td></tr>)}</tbody></table></div>{!locations.length?<div className="empty-state"><strong>No business locations configured</strong><span>Add the office or operating site, then assign coverage from staff profiles.</span></div>:null}</section>{canEdit?<form className="panel" onSubmit={save}><header className="panel-header"><h2>{draft.id?"Edit location":"New location"}</h2></header><div className="form-section stack">{(["name","address","latitude","longitude"] as const).map(k=><label className="field" key={k}><span>{k}</span><input required={k==="name"||k==="address"} type={k==="latitude"||k==="longitude"?"number":"text"} step="any" value={draft[k]} onChange={e=>{setDraft({...draft,[k]:e.target.value});setDirty(true);}}/></label>)}<label><input type="checkbox" checked={draft.active} onChange={e=>{setDraft({...draft,active:e.target.checked});setDirty(true);}}/> Active operating site</label><p role="status">{status}</p><button className="button button-primary">Save location</button></div></form>:null}</div>;}
