"use client";
import { useEffect,useMemo,useState } from "react";
import Link from "next/link";
import { CalendarDays,ChevronLeft,ChevronRight,Download,Plus } from "lucide-react";

import { useSearchParams } from "next/navigation";
type Appointment={id:string;jobId:string;surveyorId?:string|null;version?:number;status:string;startsAt:Date|string;endsAt:Date|string;reference?:string;address?:string};
type Directory={jobs:{id:string;reference:string}[];members:{id:string;name:string|null;lastName:string|null}[]};
const dateKey=(v:Date|string)=>new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/London"}).format(new Date(v));
const deviceDateTime=(value:Date|string)=>{const date=new Date(value);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);};
const time=(v:Date|string)=>new Date(v).toLocaleTimeString("en-GB",{timeZone:"Europe/London",hour:"2-digit",minute:"2-digit"});
export function OperationsCalendar({appointments,slug,canEdit=false,canManage=false}:{appointments:Appointment[];slug:string;canEdit?:boolean;canManage?:boolean}){
  const searchParams=useSearchParams();
  const [view,setView]=useState<"day"|"week"|"month">("week"),[anchor,setAnchor]=useState(()=>dateKey(new Date())),[rows,setRows]=useState(appointments),[directory,setDirectory]=useState<Directory>({jobs:[],members:[]}),[error,setError]=useState(""),[busy,setBusy]=useState(false),[editing,setEditing]=useState<Appointment|null|undefined>(undefined),[availability,setAvailability]=useState(false);
  const days=useMemo(()=>{const chosen=new Date(`${anchor}T12:00:00Z`);if(view==="month")chosen.setUTCDate(1);if(view!=="day")chosen.setUTCDate(chosen.getUTCDate()-(chosen.getUTCDay()+6)%7);return Array.from({length:view==="day"?1:view==="week"?7:42},(_,i)=>new Date(chosen.getTime()+i*86400000));},[anchor,view]);
  useEffect(()=>{let active=true;const first=new Date(days[0].getTime()-12*3600000),last=new Date(days.at(-1)!.getTime()+12*3600000);fetch(`/api/v1/calendar/appointments?from=${first.toISOString()}&to=${last.toISOString()}`,{cache:"no-store"}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error?.message??"Could not load appointments.");if(active){setRows(p.data.appointments);setDirectory(p.data);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[days]);
  function move(direction:number){const date=new Date(`${anchor}T12:00:00Z`);if(view==="month"){date.setUTCDate(1);date.setUTCMonth(date.getUTCMonth()+direction);}else date.setUTCDate(date.getUTCDate()+direction*(view==="week"?7:1));setAnchor(dateKey(date));}
  async function save(form:FormData,cancel=false){setBusy(true);setError("");try{const startsAt=cancel?new Date(editing!.startsAt).toISOString():new Date(String(form.get("startsAt"))).toISOString();const durationMinutes=cancel?(new Date(editing!.endsAt).getTime()-new Date(editing!.startsAt).getTime())/60000:Number(form.get("duration"));const r=await fetch("/api/v1/calendar/appointments",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...(editing?{id:editing.id,version:editing.version}:{}),jobId:cancel?editing!.jobId:form.get("jobId"),surveyorId:cancel?editing!.surveyorId:form.get("surveyorId"),startsAt,durationMinutes,cancel})});const p=await r.json();if(!r.ok)throw new Error(p.error?.message??"Could not save appointment.");setRows(current=>[...current.filter(v=>v.id!==p.data.id),p.data]);setEditing(undefined);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <><section className="panel"><div className="panel-header"><div><h2>Practice calendar</h2><p>Visit times: Europe/London. External changes are reviewed, not silently applied.</p></div><div className="action-row"><a className="button button-quiet" href="/api/v1/calendar/ical"><Download size={16}/>iCal</a><button className="button button-secondary" onClick={()=>setAvailability(!availability)}>Availability</button>{canEdit?<button className="button button-primary" onClick={()=>setEditing(null)}><Plus size={16}/>Appointment</button>:null}</div></div><div className="calendar-toolbar"><div role="group" aria-label="Calendar view">{(["day","week","month"] as const).map(v=><button key={v} aria-pressed={view===v} onClick={()=>setView(v)}>{v}</button>)}</div><div className="action-row"><button className="icon-button" aria-label="Previous period" onClick={()=>move(-1)}><ChevronLeft size={16}/></button><button className="button button-quiet" onClick={()=>setAnchor(dateKey(new Date()))}>Today</button><label><span className="sr-only">Calendar date</span><input type="date" value={anchor} onChange={e=>setAnchor(e.target.value)}/></label><button className="icon-button" aria-label="Next period" onClick={()=>move(1)}><ChevronRight size={16}/></button></div></div>{error?<p className="form-error" role="alert">{error}</p>:null}<div className={`calendar-board calendar-${view==="day"?"agenda":view}`} aria-label={`${view} calendar`}>{days.map(d=>{const key=dateKey(d),visits=rows.filter(v=>dateKey(v.startsAt)===key&&v.status!=="cancelled");return <section className="calendar-day" key={key}><h3>{d.toLocaleDateString("en-GB",{weekday:"short",day:"numeric",month:"short",timeZone:"Europe/London"})}</h3>{visits.map(v=><article key={v.id}><time>{time(v.startsAt)}–{time(v.endsAt)}</time><strong>{v.reference??v.status}</strong>{v.address?<p>{v.address}</p>:null}<Link href={`/app/${slug}/jobs/${v.jobId}`}>Open job</Link><Link className="button button-primary" href={`/app/${slug}/jobs/${v.jobId}/survey`}>Open survey</Link>{canEdit?<button className="button button-quiet" onClick={()=>setEditing(v)}>Manage visit</button>:null}</article>)}{!visits.length?<span className="muted">No visits</span>:null}</section>;})}</div></section>
    {editing!==undefined?<section className="panel action-panel"><h2>{editing?"Manage appointment":"New appointment"}</h2><form key={editing?.id??"new"} action={form=>save(form)}><div className="form-grid"><label className="field"><span>Job</span><select name="jobId" required defaultValue={editing?.jobId??""}><option value="">Choose a job</option>{directory.jobs.map(j=><option key={j.id} value={j.id}>{j.reference}</option>)}</select></label><label className="field"><span>Surveyor</span><select name="surveyorId" required defaultValue={editing?.surveyorId??""}><option value="">Choose a member</option>{directory.members.map(m=><option key={m.id} value={m.id}>{[m.name,m.lastName].filter(Boolean).join(" ")}</option>)}</select></label><label className="field"><span>Start (your device timezone)</span><input name="startsAt" type="datetime-local" defaultValue={editing?deviceDateTime(editing.startsAt):undefined} required/></label><label className="field"><span>Duration (minutes)</span><input type="number" name="duration" min={15} max={480} step={15} defaultValue={editing?(new Date(editing.endsAt).getTime()-new Date(editing.startsAt).getTime())/60000:180} required/></label></div><div className="action-row"><button className="button button-primary" disabled={busy}>Save appointment</button><button type="button" className="button button-quiet" onClick={()=>setEditing(undefined)}>Close</button>{editing?<button type="button" className="button button-danger" disabled={busy} onClick={()=>{if(confirm("Cancel this Surveynt visit?"))void save(new FormData(),true);}}>Cancel visit</button>:null}</div></form></section>:null}
    {availability||searchParams.get("view")==="availability"?<><AvailabilityControls canEdit={canManage}/><p>Connect your personal Google or Microsoft calendar in <Link href={`/app/${slug}/account?section=connections`}>Your account → Calendar connections</Link>.</p></>:null}
  </>;
}
function AvailabilityControls({canEdit}:{canEdit:boolean}){
  const [data,setData]=useState<{blocks:{id:string;startsAt:string;endsAt:string;reason:string;source:string}[];conflicts:{id:string;kind:string}[];connections:{id:string;provider:string;status:string;lastSyncedAt:string|null}[]}>({blocks:[],conflicts:[],connections:[]});
  const [status,setStatus]=useState("");
  const load=async()=>{const response=await fetch("/api/v1/calendar/availability",{cache:"no-store"});const payload=await response.json();if(!response.ok)throw new Error(payload.error?.message??"Could not load availability.");setData(payload.data);};
  useEffect(()=>{let active=true;fetch("/api/v1/calendar/availability",{cache:"no-store"}).then(async response=>{const payload=await response.json();if(!response.ok)throw new Error(payload.error?.message??"Could not load availability.");if(active)setData(payload.data);}).catch(error=>{if(active)setStatus(error.message);});return()=>{active=false;};},[]);
  async function mutate(url:string,method:string,body?:unknown){try{const response=await fetch(url,{method,headers:{"content-type":"application/json"},...(body?{body:JSON.stringify(body)}:{})});const payload=await response.json();if(!response.ok)throw new Error(payload.error?.message??"Action failed.");await load();setStatus("Calendar updated. No external calendar was changed.");}catch(error){setStatus((error as Error).message);}}
  async function save(form:FormData){try{await mutate("/api/v1/calendar/availability","POST",{startsAt:new Date(String(form.get("start"))).toISOString(),endsAt:new Date(String(form.get("end"))).toISOString(),reason:form.get("reason"),userId:null});}catch(error){setStatus((error as Error).message);}}
  return <section className="panel action-panel"><h2><CalendarDays size={18}/>Availability and sync health</h2><p>Practice closures apply to every surveyor; personal hours are managed in Your account.</p>{data.blocks.map(row=><div className="action-row" key={row.id}><p>{new Date(row.startsAt).toLocaleString("en-GB")}–{new Date(row.endsAt).toLocaleString("en-GB")} · {row.reason} · {row.source}</p>{canEdit&&row.source==="manual"?<button className="button button-quiet" onClick={()=>{if(confirm("Remove this availability block?"))void mutate(`/api/v1/calendar/availability?id=${row.id}`,"DELETE");}}>Remove block</button>:null}</div>)}{canEdit?<form action={save}><div className="form-grid"><label className="field"><span>Start (device timezone)</span><input name="start" type="datetime-local" required/></label><label className="field"><span>End (device timezone)</span><input name="end" type="datetime-local" required/></label><label className="field"><span>Reason</span><input name="reason" required maxLength={500}/></label></div><button className="button button-primary">Block practice availability</button></form>:null}<h3>Connections</h3>{data.connections.length?data.connections.map(row=><p key={row.id}>{row.provider} · {row.status} · {row.lastSyncedAt?`Last sync ${new Date(row.lastSyncedAt).toLocaleString("en-GB")}`:"Not yet synchronised"}</p>):<p>No calendar connections. Provider setup is shown below.</p>}<h3>Conflicts requiring review</h3>{data.conflicts.length?data.conflicts.map(row=><div className="action-row" key={row.id}><p>{row.kind.replaceAll("_"," ")}</p>{canEdit?<button className="button button-secondary" onClick={()=>void mutate(`/api/v1/calendar/conflicts/${row.id}`,"POST",{decision:"keep_surveynt"})}>Keep Surveynt time</button>:null}<p>To choose a different time, reschedule the visit above before resolving this conflict.</p></div>):<p>No unresolved conflicts.</p>}<p role="status">{status}</p></section>;
}
