"use client";
import { useState } from "react";
import { CalendarDays, MapPin, ShieldCheck } from "lucide-react";

type Settings = { timezone: string; officeAddress: string | null; workingDays: string[]; workingHours: Record<string, { start: string; end: string }>; holidayDates: string[]; customerBranding: { displayName?: string; logoUrl?: string; accentColour?: string }; notificationPreferences: Record<string, boolean>; bookingHorizonDays: number; travelBufferMinutes: number; mileageRatePence: number; documentRetentionDays: number; publicQuotesEnabled: boolean; clientPaymentsEnabled: boolean };
const weekdays = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"];
export function OperationsSettingsForm({ initial, canEdit, canConfigurePayments=false }: { initial: Settings; canEdit: boolean; canConfigurePayments?:boolean }) {
  const [value, setValue] = useState(initial); const [status, setStatus] = useState(""); const [busy, setBusy] = useState(false);
  const set = <K extends keyof Settings>(key: K, next: Settings[K]) => setValue((current) => ({ ...current, [key]: next }));
  async function save(event: React.FormEvent) { event.preventDefault(); setBusy(true); setStatus(""); const response = await fetch("/api/v1/operations/settings", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(value) }); const payload = await response.json(); setBusy(false); setStatus(response.ok ? "Operational settings saved." : payload.error?.message ?? "Settings could not be saved."); }
  return <form className="panel" onSubmit={save}><section className="form-section"><h2><MapPin size={17} /> Office and routing</h2><p>Used as the route origin and for travel estimates.</p><div className="form-grid"><label className="field"><span>Office address</span><input value={value.officeAddress ?? ""} disabled={!canEdit} onChange={(event) => set("officeAddress", event.target.value || null)} /></label><label className="field"><span>Mileage rate (pence)</span><input type="number" min="0" max="1000" value={value.mileageRatePence} disabled={!canEdit} onChange={(event) => set("mileageRatePence", Number(event.target.value))} /></label><label className="field"><span>Travel buffer (minutes)</span><input type="number" min="0" max="240" value={value.travelBufferMinutes} disabled={!canEdit} onChange={(event) => set("travelBufferMinutes", Number(event.target.value))} /></label></div></section>
    <section className="form-section"><h2>Working hours and customer identity</h2><div className="form-grid"><label className="field"><span>Practice timezone</span><input value={value.timezone} disabled={!canEdit} onChange={event=>set("timezone",event.target.value)} placeholder="Europe/London" /></label><label className="field"><span>Customer-facing practice name</span><input value={value.customerBranding.displayName??""} disabled={!canEdit} maxLength={160} onChange={event=>set("customerBranding",{...value.customerBranding,displayName:event.target.value})} /></label></div>{weekdays.filter(day=>value.workingDays.includes(day)).map(day=><div className="form-grid" key={day}><label className="field"><span>{day} opening time</span><input type="time" value={value.workingHours[day]?.start??"09:00"} disabled={!canEdit} onChange={event=>set("workingHours",{...value.workingHours,[day]:{start:event.target.value,end:value.workingHours[day]?.end??"17:00"}})} /></label><label className="field"><span>{day} closing time</span><input type="time" value={value.workingHours[day]?.end??"17:00"} disabled={!canEdit} onChange={event=>set("workingHours",{...value.workingHours,[day]:{start:value.workingHours[day]?.start??"09:00",end:event.target.value}})} /></label></div>)}</section>
    <section className="form-section"><h2><CalendarDays size={17} /> Booking availability</h2><p>External busy events and explicit blocks are applied in addition to these days.</p><div className="checkbox-grid">{weekdays.map((day) => <label key={day}><input type="checkbox" checked={value.workingDays.includes(day)} disabled={!canEdit} onChange={(event) => set("workingDays", event.target.checked ? [...value.workingDays, day] : value.workingDays.filter((item) => item !== day))} /> {day}</label>)}</div><div className="form-grid"><label className="field"><span>Booking horizon (days)</span><input type="number" min="1" max="365" value={value.bookingHorizonDays} disabled={!canEdit} onChange={(event) => set("bookingHorizonDays", Number(event.target.value))} /></label><label className="field"><span>Retention (days)</span><input type="number" min="30" max="36500" value={value.documentRetentionDays} disabled={!canEdit} onChange={(event) => set("documentRetentionDays", Number(event.target.value))} /></label><label className="field"><span>Holiday dates (YYYY-MM-DD, one per line)</span><textarea value={value.holidayDates.join("\n")} disabled={!canEdit} onChange={(event) => set("holidayDates", event.target.value.split(/\s+/).filter(Boolean))} /></label></div></section>
    <section className="form-section"><h2><ShieldCheck size={17} /> Public services</h2><p>Client payments also require the production legal and accounting launch gate.</p><div className="checkbox-grid"><label><input type="checkbox" checked={value.publicQuotesEnabled} disabled={!canEdit} onChange={(event) => set("publicQuotesEnabled", event.target.checked)} /> Enable public quotes</label><label><input type="checkbox" checked={value.clientPaymentsEnabled} disabled={!canEdit||!canConfigurePayments} onChange={(event) => set("clientPaymentsEnabled", event.target.checked)} /> Enable client payments</label></div></section>
    {canEdit ? <div className="form-section form-actions"><span className="form-success" role="status">{status}</span><button className="button button-primary" disabled={busy}>{busy ? "Saving…" : "Save operations"}</button></div> : null}</form>;
}
