"use client";
import { useEffect,useState } from "react";
import type { Capability } from "@/lib/capabilities";
type Connection={id:string;provider:string;status:string;lastSyncedAt:string|null};
export function PersonalCalendars(){
  const [rows,setRows]=useState<Connection[]>([]),[providers,setProviders]=useState<Capability[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[preview,setPreview]=useState(false);
  async function load(){const [cr,pr]=await Promise.all([fetch("/api/v1/me/calendar-connections",{cache:"no-store"}),fetch("/api/v1/capabilities",{cache:"no-store"})]);const [connections,capabilities]=await Promise.all([cr.json(),pr.json()]);if(!cr.ok||!pr.ok)throw new Error("Calendar settings could not load.");let rows=connections.data;if(connections.meta?.demo){try{rows=JSON.parse(localStorage.getItem("surveynt:preview-calendars")??"[]");}catch{rows=[];}}setRows(rows);setPreview(Boolean(connections.meta?.demo));setProviders(capabilities.data.filter((row:Capability)=>["google","microsoft"].includes(row.key)));setReady(true);}
  useEffect(()=>{let active=true;Promise.resolve().then(async()=>{if(active)try{await load();const result=new URLSearchParams(location.search).get("calendar");if(result)setMessage(result==="connected"?"Your calendar is connected. First sync is queued.":"Calendar authorisation did not complete. Please reconnect.");}catch(error){setMessage((error as Error).message);}});return()=>{active=false;};},[]);
  function simulate(provider:string){const connection={id:`demo-${provider}`,provider,status:"demo",lastSyncedAt:null};const next=[...rows.filter(row=>row.provider!==provider),connection];localStorage.setItem("surveynt:preview-calendars",JSON.stringify(next));setRows(next);setMessage("Demo calendar linked on this device. No external calendar or OAuth account was changed.");}
  async function action(id:string,action:"sync"|"disconnect"){if(preview){const next=rows.map(row=>row.id===id?{...row,status:action==="disconnect"?"revoked":"demo",lastSyncedAt:action==="sync"?new Date().toISOString():row.lastSyncedAt}:row);localStorage.setItem("surveynt:preview-calendars",JSON.stringify(next));setRows(next);setMessage(action==="sync"?"Demo sync completed. No external events imported or changed.":"Demo calendar disconnected on this device.");return;}setBusy(true);try{const response=await fetch("/api/v1/me/calendar-connections",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id,action})});const payload=await response.json();if(!response.ok)throw new Error(payload.error?.message??"Calendar action failed.");await load();setMessage(action==="sync"?"Sync queued. Refresh to see its completion.":"Surveynt syncing stopped and local credentials removed. Existing external events and cached busy periods are retained; you can revoke provider consent in Google/Microsoft.");}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}}
  return <div className="settings-section"><h2>Your calendar connections</h2><p>Only your own connections appear here. OAuth keys and token-encryption secrets are managed by Surveynt administrators.</p>{!ready&&!message?<p role="status">Loading calendar providers…</p>:null}<div className="capability-grid">{providers.map(provider=><article className="capability" key={provider.key}><h3>{provider.label}</h3><span className="status status-blue">{provider.state}</span>{provider.connectHref?<a className="button button-primary" href={provider.connectHref}>{provider.action}</a>:<p>{preview?"Live calendar linking is unavailable in this isolated demo. Test the simulated flow below.":"Surveynt must configure this provider before you can grant access."}</p>}{preview?<button className="button button-secondary" onClick={()=>simulate(provider.key)}>Connect demo calendar</button>:null}{rows.filter(row=>row.provider===provider.key).map(row=><div key={row.id}><p>{row.status} · {row.lastSyncedAt?`Last sync ${new Date(row.lastSyncedAt).toLocaleString("en-GB")}`:"Not yet synced"}</p><button className="button button-secondary" disabled={busy||!["active","demo"].includes(row.status)} onClick={()=>void action(row.id,"sync")}>Sync now</button><button className="button button-quiet" disabled={busy||row.status==="revoked"} onClick={()=>{if(confirm("Stop Surveynt syncing this calendar? External events will not be deleted."))void action(row.id,"disconnect");}}>Disconnect</button></div>)}</article>)}</div><button className="button button-secondary" disabled={busy} onClick={()=>void load().catch(error=>setMessage(error.message))}>Refresh connection status</button><p role="status">{message}</p></div>;
}
