import Link from "./workspace-link";
import {Building2,Users,Settings,ShieldCheck,MapPin,Wrench,CreditCard} from "lucide-react";
import {PageHeader} from "./page-header";
import {ConnectionsPanel} from "./connections-panel";
import {loadMembers,loadOrganisationSettings} from "@/lib/data";
import {requireFirmAccess} from "@/lib/access";
export async function PracticeAdministration({slug}:{slug:string}){const [access,members,settings]=await Promise.all([requireFirmAccess(slug),loadMembers(slug),loadOrganisationSettings(slug)]);
 const sections=[{title:"Practice identity",text:`${settings.tradingName} · ${settings.region}`,href:"settings",icon:Building2,action:"Manage identity & branding"},{title:"Staff access & permissions",text:`${members.filter(m=>m.status==="Active").length} active members · ${members.filter(m=>m.status==="Invited").length} invitations`,href:"team",icon:Users,action:"Manage practice access"},{title:"Services offered",text:`${settings.services.length} active service definitions`,href:"services",icon:Wrench,action:"Configure services"},{title:"Locations & coverage",text:"Operating bases, business sites and staff coverage assignments.",href:"locations",icon:MapPin,action:"Manage locations"},{title:"Operational settings",text:"Dedicated sections for working hours, booking, notifications and evidence release.",href:"settings/operations",icon:Settings,action:"Open tenancy settings"},{title:"AI governance",text:"Approved uses, case consent, risk reviews and professional oversight.",href:"settings/ai",icon:ShieldCheck,action:"Review assistant governance"},...(access.actorRole==="owner"?[{title:"Subscription & billing",text:"Owner-controlled subscription and payment arrangements.",href:"settings/billing",icon:CreditCard,action:"Open billing controls"}]:[])];
 return <main className="page"><PageHeader eyebrow="Your practice tenancy" title="Practice administration" description={`Govern ${access.organisationName}, its people and the capabilities available to the business.`}/><div className="administration-grid">{sections.map(s=><section className="panel" key={s.href}><header className="panel-header"><s.icon size={20}/><h2>{s.title}</h2></header><div className="panel-body"><p>{s.text}</p><Link className="button button-secondary" href={`/app/${slug}/${s.href}`}>{s.action}</Link></div></section>)}</div><section className="panel"><header className="panel-header"><h2>Enabled integrations</h2><p>Connections are approved by the platform; this practice sees their availability.</p></header><div className="panel-body"><ConnectionsPanel scope="practice"/></div></section></main>;
}
