"use client";
import {workspaceFetch} from "@/lib/workspace-request";
import { useEffect, useState } from "react";
import { FileCheck2, SearchCheck, ShieldCheck } from "lucide-react";
import { useRouter } from "next/navigation";
type Service = { id: string; name: string; currency: string; baseAmountMinor: number; vatBasisPoints: number; depositBasisPoints: number; surcharges: Record<string, { label: string; amountMinor: number }> };
export function PublicQuoteAdviser({ organisationSlug }: { organisationSlug: string }) {
  const router = useRouter();
  const [services, setServices] = useState<Service[]>([]); const [practice, setPractice] = useState(""); const [selected, setSelected] = useState(""); const [adviserEnabled, setAdviserEnabled] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { let active = true; workspaceFetch(`/api/v1/public/services?organisationSlug=${encodeURIComponent(organisationSlug)}`).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error?.message); if (active) { setPractice(body.data.organisation.name); setServices(body.data.services); setAdviserEnabled(body.data.adviserEnabled); setSelected(body.data.services[0]?.id ?? ""); } }).catch((reason) => { if (active) setError(reason.message); }); return () => { active = false; }; }, [organisationSlug]);
  async function submit(form: FormData) { setBusy(true); setError(""); const requestId = crypto.randomUUID(); const alterations = form.getAll("alterations").map(String); const response = await workspaceFetch("/api/v1/public/quotes", { method: "POST", headers: { "content-type": "application/json", "idempotency-key": requestId }, body: JSON.stringify({ organisationSlug, serviceId: adviserEnabled ? undefined : selected, firstName: form.get("firstName"), lastName: form.get("lastName"), email: form.get("email"), surchargeKeys: alterations, answers: { purpose: form.get("purpose"), propertyAge: form.get("propertyAge"), propertyType: form.get("propertyType"), extensions: alterations.length > 0, alterationTypes: alterations, concerns: form.get("concerns") } }) }); const payload = await response.json(); setBusy(false); if (!response.ok) return setError(payload.error?.message ?? "A quote could not be created."); router.push(`/quote/${payload.data.quote.id}#${payload.data.token}`); }
  return <main className="public-quote"><section className="quote-card"><div className="quote-kicker"><SearchCheck /> Survey adviser</div><h1>Find the right survey</h1><p>{practice ? `${practice} uses your answers to prepare a transparent quote.` : "Loading available survey services…"}</p>{error ? <p className="form-error" role="alert">{error}</p> : null}<form action={submit} className="quote-form">{!adviserEnabled ? <label>Service<select required value={selected} onChange={(event) => setSelected(event.target.value)}>{services.map((service) => <option key={service.id} value={service.id}>{service.name}</option>)}</select></label> : null}<div className="form-grid"><label>First name<input name="firstName" required maxLength={80} autoComplete="given-name" /></label><label>Last name<input name="lastName" required maxLength={80} autoComplete="family-name" /></label></div><label>Email<input name="email" type="email" required autoComplete="email" /></label><label>What do you need?<select name="purpose" required><option value="condition-survey">A condition survey</option><option value="survey-and-valuation">Survey and valuation</option><option value="formal-valuation">Formal valuation only</option><option value="roof-only">Roof or high-level inspection</option></select></label><div className="form-grid"><label>Property type<select name="propertyType"><option value="house">House</option><option value="flat">Apartment / flat</option><option value="bungalow">Bungalow</option><option value="other">Other</option></select></label><label>Approximate age<select name="propertyAge"><option value="pre-1950">Pre 1950</option><option value="1950-1989">1950–1989</option><option value="post-1990">Post 1990</option><option value="listed-historic">Listed / historic</option><option value="unknown">Not sure</option></select></label></div><fieldset><legend>Major alterations</legend><div className="checkbox-grid"><label><input type="checkbox" name="alterations" value="loft-conversion" /> Loft conversion</label><label><input type="checkbox" name="alterations" value="single-storey-extension" /> Single-storey extension</label><label><input type="checkbox" name="alterations" value="double-storey-extension" /> Double-storey extension</label><label><input type="checkbox" name="alterations" value="conservatory" /> Conservatory</label></div></fieldset><label>Main concerns<textarea name="concerns" rows={3} maxLength={2000} placeholder="For example damp, cracks, roof or chimney concerns" /></label><p><ShieldCheck size={16} /> Your answers are customer statements and will be reviewed by the surveyor.</p><button className="button button-primary" disabled={busy || (!adviserEnabled && !selected)}><FileCheck2 size={16} /> {busy ? "Preparing…" : "Prepare my quote"}</button></form></section></main>;
}
