"use client";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
type Quote={id:string;version:number;reference:string;jobId:string|null;status:string;firstName:string|null;lastName:string|null;email:string|null;phone:string|null;propertyAddress:string|null;expiresAt:Date};
type Delivery={id:string;recipient:string;status:string;attempts:number;sentAt:string|null;createdAt:string};
export function QuoteControls({quote,slug}:{quote:Quote;slug:string}){
  const router=useRouter(),[status,setStatus]=useState(""),[busy,setBusy]=useState(false),[url,setUrl]=useState(""),[deliveries,setDeliveries]=useState<Delivery[]|null>(null);
  async function load(){try{const response=await fetch("/api/v1/quotes/"+quote.id,{cache:"no-store"}),payload=await response.json();if(!response.ok)throw new Error(payload.error?.message);setDeliveries(payload.data.deliveries);}catch(error){setStatus((error as Error).message);}}
  async function action(value:string,extra:Record<string,unknown>={}){setBusy(true);try{const response=await fetch("/api/v1/quotes/"+quote.id,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({version:quote.version,action:value,...extra})}),payload=await response.json();if(!response.ok)throw new Error(payload.error?.message);setUrl(payload.data.url??"");setStatus(payload.data.previousLinkRevoked?"Contact updated. The previous link was revoked; issue a fresh link for this recipient.":payload.data.url?"Fresh link created. The previous link no longer works. This does not extend quote expiry.":"Quote updated.");router.refresh();}catch(error){setStatus((error as Error).message);}finally{setBusy(false);}}
  async function email(){setBusy(true);try{const token=url.split("#")[1];if(!token)throw new Error("Issue a fresh link first.");const response=await fetch("/api/v1/public/quotes/"+quote.id+"/email",{method:"POST",headers:{"x-quote-token":token}}),payload=await response.json();if(!response.ok)throw new Error(payload.error?.message);setStatus(payload.data.simulated?"Demo delivery recorded. No external email was sent.":payload.data.queued?"Delivery queued; awaiting provider result.":"This version already has a queued delivery.");await load();}catch(error){setStatus((error as Error).message);}finally{setBusy(false);}}
  return <details onToggle={event=>{if(event.currentTarget.open&&deliveries===null)void load();}}><summary>Details & actions</summary><p>{quote.email??"Email not provided"}</p><p>{quote.propertyAddress??"Address awaiting customer confirmation"}</p><p>Expires {new Date(quote.expiresAt).toLocaleString("en-GB")}</p>{quote.jobId?<><a className="button button-quiet" href={"/app/"+slug+"/jobs/"+quote.jobId}>Open converted job</a><p>Contact changes for a converted customer belong in the customer register, not the accepted quote snapshot.</p></>:quote.status!=="cancelled"?<form key={quote.version} action={form=>action("update_contact",{firstName:form.get("firstName"),lastName:form.get("lastName")||null,email:form.get("email"),phone:form.get("phone")||null})}><div className="form-grid"><label className="field"><span>First name</span><input name="firstName" defaultValue={quote.firstName??""} maxLength={80} required/></label><label className="field"><span>Last name</span><input name="lastName" defaultValue={quote.lastName??""} maxLength={80}/></label><label className="field"><span>Email</span><input type="email" name="email" defaultValue={quote.email??""} required/></label><label className="field"><span>Phone</span><input name="phone" defaultValue={quote.phone??""} maxLength={40}/></label></div><button className="button button-secondary" disabled={busy}>Save contact details</button></form>:null}
  {quote.status!=="cancelled"?<div className="action-row"><button className="button button-quiet" disabled={busy} onClick={()=>void action("revoke_link")}>Revoke customer link</button><button className="button button-secondary" disabled={busy} onClick={()=>{if(confirm("Issue a new customer link and invalidate the previous link?"))void action("reissue_link");}}>Issue fresh customer link</button>{!quote.jobId?<button className="button button-danger" disabled={busy} onClick={()=>{if(confirm("Cancel this quote and revoke its link?"))void action("cancel");}}>Cancel quote</button>:null}</div>:null}
  {url?<div className="action-row"><a className="button button-secondary" href={url} target="_blank" rel="noopener noreferrer">Open secure customer link</a><button className="button button-secondary" disabled={busy} onClick={()=>{if(confirm("Deliver this quote link to "+quote.email+"? Demo delivery is simulated."))void email();}}>Email this link</button></div>:null}
  <h4>Latest delivery attempts</h4>{deliveries===null?<p>Loading delivery history…</p>:deliveries.length?<ul>{deliveries.map(delivery=><li key={delivery.id}>{delivery.recipient} · {delivery.status} · {delivery.attempts} attempts · {new Date(delivery.sentAt??delivery.createdAt).toLocaleString("en-GB")}</li>)}</ul>:<p>No delivery attempts recorded.</p>}<p role="status">{status}</p></details>;
}
export function QuoteCreator(){const router=useRouter();const [services,setServices]=useState<{service:{id:string;name:string}}[]>([]),[open,setOpen]=useState(false),[status,setStatus]=useState(""),[url,setUrl]=useState(""),[busy,setBusy]=useState(false),[requestId,setRequestId]=useState(()=>crypto.randomUUID());useEffect(()=>{fetch("/api/v1/service-catalogue").then(r=>r.json()).then(p=>setServices(p.data??[])).catch(()=>setStatus("Service catalogue could not be loaded."));},[]);async function submit(form:FormData){setBusy(true);try{const r=await fetch("/api/v1/quotes",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({requestId,serviceId:form.get("serviceId"),firstName:form.get("firstName"),lastName:form.get("lastName"),email:form.get("email"),answers:{purpose:"survey-only",propertyAge:form.get("age"),concerns:form.get("concerns")}})});const p=await r.json();if(!r.ok)throw new Error(p.error?.message);setUrl(p.data.url);setOpen(false);setStatus("Quote created. Customer statements remain unverified.");router.refresh();}catch(e){setStatus((e as Error).message);}finally{setBusy(false);}}return <section className="panel action-panel"><button className="button button-primary" onClick={()=>{if(!open){setRequestId(crypto.randomUUID());setUrl("");setStatus("");}setOpen(!open);}}>{open?"Close quote form":"Create quote"}</button>{open?<form action={submit}><h2>New customer quote</h2><div className="form-grid"><label className="field"><span>First name</span><input name="firstName" required maxLength={80}/></label><label className="field"><span>Last name</span><input name="lastName" maxLength={80}/></label><label className="field"><span>Email</span><input name="email" type="email" required/></label><label className="field"><span>Service</span><select name="serviceId" required defaultValue=""><option value="" disabled>Choose service</option>{services.map(s=><option key={s.service.id} value={s.service.id}>{s.service.name}</option>)}</select></label><label className="field"><span>Property age</span><select name="age"><option value="pre-1950">Before 1950</option><option value="1950-1990">1950–1990</option><option value="post-1990">After 1990</option><option value="listed-historic">Historic or listed</option></select></label><label className="field"><span>Customer concerns</span><textarea name="concerns" maxLength={1000}/></label></div><button className="button button-primary" disabled={busy||!services.length}>Create secure quote</button></form>:null}<p role="status">{status}</p>{url?<a className="button button-secondary" href={url} target="_blank" rel="noopener noreferrer">Open customer journey</a>:null}</section>;}
