"use client";
import Link from "./workspace-link";
import {useWorkspace} from "./workspace-provider";
import {workspaceLabels} from "@/lib/workspace-mode";
import {workspaceFetch} from "@/lib/workspace-request";
import {useEffect,useRef,useState} from "react";
import {usePathname} from "next/navigation";
import {Bot,Send,X,FileCheck2} from "lucide-react";
type Message={role:string;content:string;citations?:{id:string;label:string;href:string}[]};
export function SurveyantOverlay({mode,slug,quoteId,token,name}:{mode:"firm"|"platform"|"case";slug?:string;quoteId?:string;token?:string;name:string}){
 const workspace=useWorkspace();const audience=workspace?.workspaceMode;
 const pathname=usePathname();const jobId=mode==="firm"?pathname.match(/\/jobs\/([\da-f-]{36})(?:\/|$)/i)?.[1]:undefined;
 const supportId=mode==="platform"?pathname.match(/\/platform\/support\/([\da-f-]{36})(?:\/|$)/i)?.[1]:undefined;
 const scope=mode==="case"?`Case ${name}`:mode==="platform"?supportId?"Surveynt · active support session (read only)":"Surveynt · platform operations":jobId?`${name} · current case`:`${name} · ${audience?workspaceLabels[audience]:"business records"}${audience==="surveyor"?" · your assignments":""}`;
 const contextKey=`${audience}:${endpointPlaceholder(mode,quoteId,supportId)}:${jobId??""}:${token??""}`;
 const [messageContext,setMessageContext]=useState(contextKey);const [open,setOpen]=useState(false),[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);const dialog=useRef<HTMLDialogElement>(null),trigger=useRef<HTMLButtonElement>(null),requestId=useRef(0),historyController=useRef<AbortController|null>(null);
 const endpoint=mode==="platform"?supportId?`/api/platform/support/${supportId}/surveyant`:"/api/platform/surveyant":mode==="case"?`/api/v1/public/quotes/${quoteId}/assistant`:"/api/v1/surveyant";const storageKey=`surveynt:overlay:${mode}:${slug??quoteId??"platform"}`;
 useEffect(()=>{const timer=setTimeout(()=>setOpen(sessionStorage.getItem(storageKey)==="open"),0);return()=>clearTimeout(timer);},[storageKey]);
 useEffect(()=>{if(open&&!dialog.current?.open)dialog.current?.show();if(!open&&dialog.current?.open)dialog.current?.close();},[open,storageKey]);
 useEffect(()=>{requestId.current++;const reset=setTimeout(()=>{setMessageContext(contextKey);setMessages([]);setError("");setBusy(false);setText("");},0);if(mode==="case"&&!token)return()=>clearTimeout(reset);let active=true;const controller=new AbortController();historyController.current=controller;workspaceFetch(`${endpoint}${jobId?`?jobId=${jobId}`:""}`,{headers:{...(token?{"x-quote-token":token}:{}),...(slug?{"x-demo-organisation-slug":slug}:{})},signal:controller.signal}).then(async r=>{const p=await r.json();if(!r.ok)throw Error(p.error?.message??"Conversation unavailable.");if(active){setMessageContext(contextKey);setMessages(p.data.messages??[]);}}).catch(e=>{if(active&&e.name!=="AbortError")setError(e.message);});return()=>{active=false;controller.abort();clearTimeout(reset);};},[endpoint,jobId,token,slug,mode,audience,contextKey]);
 async function send(e:React.FormEvent){e.preventDefault();historyController.current?.abort();const turn=++requestId.current;const question=text.trim();if(!question||busy)return;setBusy(true);setError("");setMessages(v=>[...v,{role:"user",content:question}]);setText("");try{const r=await workspaceFetch(endpoint,{method:"POST",headers:{"content-type":"application/json",...(token?{"x-quote-token":token}:{}),...(slug?{"x-demo-organisation-slug":slug}:{})},body:JSON.stringify({message:question,...(jobId?{jobId}:{})})});const p=await r.json();if(!r.ok)throw Error(p.error?.message??"Surveyant is unavailable.");if(requestId.current===turn)setMessages(v=>[...v,p.data.message]);}catch(e){if(requestId.current===turn)setError((e as Error).message);}finally{if(requestId.current===turn)setBusy(false);}}
 function close(){sessionStorage.setItem(storageKey,"closed");setOpen(false);trigger.current?.focus();}
 return <><button ref={trigger} className="surveyant-toggle" aria-haspopup="dialog" aria-expanded={open} onClick={()=>{sessionStorage.setItem(storageKey,"open");setOpen(true);}}><Bot size={18}/>Surveyant</button><dialog ref={dialog} className="surveyant-overlay" aria-labelledby="surveyant-heading" onKeyDown={e=>{if(e.key==="Escape"){e.preventDefault();close();}}} onCancel={e=>{e.preventDefault();close();}} onClose={()=>setOpen(false)}><header><div><h2 id="surveyant-heading"><Bot size={19}/>Surveyant</h2><small>{scope}</small></div><button autoFocus className="icon-button" aria-label="Close Surveyant" onClick={close}><X size={19}/></button></header><div className="surveyant-messages" aria-live="polite"><div className="surveyant-welcome"><FileCheck2 size={23}/><h3>Work with a clearer picture.</h3><p>Ask about the records available in this workspace. Answers include their sources. Changes and professional findings require human approval.</p></div>{(messageContext===contextKey?messages:[]).map((m,i)=><div key={i} className={`surveyant-message ${m.role}`}><strong>{m.role==="user"?"You":"Surveyant"}</strong><p>{m.content}</p>{m.citations?.map(c=><Link key={c.id} href={!c.href.startsWith("/")&&!c.href.startsWith("#")?`/app/${slug}/${c.href}`:c.href}>{c.label}</Link>)}</div>)}{busy&&messageContext===contextKey?<p role="status">Reviewing permitted records…</p>:null}{error&&messageContext===contextKey?<p className="form-error" role="alert">{error}</p>:null}</div><form onSubmit={send}><label className="sr-only" htmlFor="surveyant-message">Message Surveyant</label><textarea id="surveyant-message" value={text} onChange={e=>setText(e.target.value)} required maxLength={4000} rows={2} placeholder="Ask about this workspace…"/><button className="button button-primary" disabled={busy||!text.trim()} aria-label="Send message"><Send size={18}/></button></form><footer>Context is limited to your authorised records.</footer></dialog></>;
}

function endpointPlaceholder(mode:string,quoteId?:string,supportId?:string){return `${mode}:${quoteId??supportId??""}`;}
