"use client";
import { useEffect, useId, useRef, useState, type CSSProperties } from "react";
import Image from "next/image";
import { ArrowLeft, ArrowRight, FileCheck2, ShieldCheck } from "lucide-react";
import { artworkForPropertyType, propertyTypeOptions } from "@/lib/property-artwork";
import { formSubmissionSchema, type FormContext, type FormSubmission } from "@/lib/website-form-config";
import { formDecision } from "@/lib/website-form-decision";
import "./website-form.css";

type Result = { kind: "enquiry"; reference: string; demo?: boolean } | { kind: "quote"; quote: { id: string; reference: string; currency: string; subtotalMinor: number; vatMinor: number; totalMinor: number; depositMinor: number; pricing: { service: string }; recommendation: { reason: string }; expiresAt: string }; token: string };
const labels = ["Property", "Details", "Contact", "Review"];
const alterations = [{ value: "loft-conversion", label: "Loft conversion" }, { value: "single-storey-extension", label: "Single-storey extension" }, { value: "double-storey-extension", label: "Double-storey extension" }, { value: "conservatory", label: "Conservatory" }] as const;
export function WebsiteCustomerForm({ context, preview = false, previewUnavailable = false }: { context: FormContext; preview?: boolean; previewUnavailable?: boolean }) {
  const { config } = context, id = useId();
  const [step, setStep] = useState(0), [error, setError] = useState(""), [busy, setBusy] = useState(false), [result, setResult] = useState<Result | null>(null);
  const [answers, setAnswers] = useState<FormSubmission["answers"]>({ path: config.paths[0], purpose: "condition-survey", propertyType: "Detached house", propertyAge: "unknown", alterationTypes: [], concerns: "" });
  const [serviceId, setServiceId] = useState(""), [contact, setContact] = useState({ firstName: "", lastName: "", email: "", phone: "" });
  const [address, setAddress] = useState({ line1: "", line2: "", city: "", postcode: "", country: "ENG" as FormSubmission["address"]["country"] });
  const [privacy, setPrivacy] = useState(false), [website, setWebsite] = useState("");
  const [previewDate] = useState(() => Date.now());
  const submission = useRef<{ signature: string; requestId: string } | null>(null), heading = useRef<HTMLHeadingElement>(null);
  const effectiveAnswers = { ...answers, path: config.paths.includes(answers.path) ? answers.path : config.paths[0], concerns: config.questions.includes("concerns") ? answers.concerns : "", alterationTypes: config.questions.includes("alterations") ? answers.alterationTypes : [] };
  const availableServices = context.services.filter(s => !config.serviceIds.length || config.serviceIds.includes(s.id));
  const effectiveContext = { ...context, services: availableServices }, selectedService = availableServices.some(s => s.id === serviceId) ? serviceId : undefined;
  const decision = formDecision(effectiveContext, effectiveAnswers, selectedService), artwork = artworkForPropertyType(answers.propertyType);
  const money = (value: number, currency = decision.service?.currency ?? "GBP") => new Intl.NumberFormat("en-GB", { style: "currency", currency }).format(value / 100);
  const enabled = preview ? !previewUnavailable : config.enabled;
  useEffect(() => {
    if (preview || window.parent === window) return;
    const params = new URLSearchParams(window.location.search), parentOrigin = params.get("parentOrigin");
    if (!parentOrigin || (() => { try { return new URL(parentOrigin).origin !== parentOrigin || new URL(document.referrer).origin !== parentOrigin; } catch { return true; } })()) return;
    const surface = document.querySelector(".website-form"); if (!surface) return;
    const send = () => window.parent.postMessage({ type: "surveynt:resize", height: Math.max(200, Math.ceil(surface.getBoundingClientRect().height)) }, parentOrigin);
    const observer = new ResizeObserver(send); observer.observe(surface); send(); return () => observer.disconnect();
  }, [preview]);
  function move(next: number) { setStep(next); setError(""); requestAnimationFrame(() => heading.current?.focus()); }
  async function submit() {
    const data = { organisationSlug: context.slug, versionId: context.versionId ?? "00000000-0000-4000-8000-000000000001", requestId: crypto.randomUUID(), ...contact, phone: config.questions.includes("phone") ? contact.phone : "", address, answers: effectiveAnswers, ...(selectedService ? { serviceId: selectedService } : {}), privacyAcknowledged: privacy, website };
    const parsed = formSubmissionSchema.safeParse(data);
    if (!parsed.success) { setError(parsed.error.issues.map(i => `${i.path.join(" ")}: ${i.message}`).join(". ")); return; }
    if (preview) {
      if (decision.service && decision.money && context.quotesReady) setResult({ kind: "quote", quote: { id: "preview", reference: "PREVIEW — nothing submitted", currency: decision.service.currency, ...decision.money, pricing: { service: decision.service.name }, recommendation: { reason: decision.reason }, expiresAt: new Date(previewDate + decision.service.validityDays * 86_400_000).toISOString() }, token: "" });
      else setResult({ kind: "enquiry", reference: "PREVIEW — nothing submitted" });
      return;
    }
    const signature = JSON.stringify({ ...parsed.data, requestId: "" });
    if (submission.current?.signature !== signature) submission.current = { signature, requestId: data.requestId };
    setBusy(true); setError("");
    try {
      const response = await fetch("/api/v1/public/website-form/submissions", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...parsed.data, requestId: submission.current!.requestId }) });
      const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message ?? "Your request could not be submitted."); setResult(payload.data);
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Connection unavailable. Please try again."); } finally { setBusy(false); }
  }
  return <section className={`website-form wf-${config.density}`} style={{ "--wf-accent": config.accentColour } as CSSProperties} aria-label={`${config.displayName} survey adviser`}>
    <header className="wf-header">{config.logoUrl ? <Image unoptimized src={config.logoUrl} width={120} height={48} alt={`${config.displayName} logo`} /> : <span className="wf-symbol" aria-hidden="true"><FileCheck2 size={22}/></span>}<strong>{config.displayName}</strong>{preview ? <span className="wf-badge">Interactive preview</span> : context.demo ? <span className="wf-badge">Simulated demo</span> : null}</header>
    <h1 ref={heading} tabIndex={-1}>{config.heading}</h1><p className="wf-introduction">{config.introduction}</p>
    {!enabled ? <p role="status">Online enquiries are currently unavailable. Please contact the practice below.</p> : result ? <div className="wf-success" role="status"><ShieldCheck/><h2>{result.kind === "quote" ? "Your quote is ready" : preview ? "Preview complete" : "Enquiry received"}</h2><p>{result.kind === "quote" ? result.quote.reference : result.reference}</p>{result.kind === "quote" ? <><h3>{result.quote.pricing.service}</h3><p>{result.quote.recommendation.reason}</p><dl><div><dt>Before VAT</dt><dd>{money(result.quote.subtotalMinor, result.quote.currency)}</dd></div><div><dt>VAT</dt><dd>{money(result.quote.vatMinor, result.quote.currency)}</dd></div><div><dt>Total</dt><dd>{money(result.quote.totalMinor, result.quote.currency)}</dd></div><div><dt>Deposit</dt><dd>{money(result.quote.depositMinor, result.quote.currency)}</dd></div></dl><p>Valid until {new Date(result.quote.expiresAt).toLocaleDateString("en-GB")}.</p><a className="wf-primary" href={preview ? undefined : `/quote/${result.quote.id}#${result.token}`} aria-disabled={preview} target="_blank" rel="noopener noreferrer">Continue securely in Surveynt <ArrowRight size={16}/></a><p>{preview ? "Preview only: secure continuation is disabled. No records or external actions were created." : "Acceptance, verified payment and booking continue in a new tab."}</p></> : <p>{preview ? "No records, emails, payments or appointments were created." : "The practice will review your customer-provided information and contact you. No payment has been taken or appointment reserved."}</p>}{preview ? <button type="button" onClick={() => { setResult(null); move(0); }}>Restart preview</button> : null}</div> : <>
      <ol className="wf-steps" aria-label="Form progress">{labels.map((label, index) => <li key={label} aria-current={step === index ? "step" : undefined}><span>{index + 1}</span>{label}</li>)}</ol>
      {config.showArtwork && step === 0 ? <figure className="wf-artwork"><Image src={artwork.src} alt={artwork.alt} width={960} height={960} sizes="(max-width: 600px) 100vw, 280px"/><figcaption>Illustrative only — not this property, measured evidence or legal boundaries.</figcaption></figure> : null}
      <form onSubmit={event => { event.preventDefault(); if (step < 3) move(step + 1); else void submit(); }}>
        {step === 0 ? <div className="wf-fields"><label>What are you enquiring about?<select value={effectiveAnswers.path} onChange={e => { const path = e.target.value as FormSubmission["answers"]["path"]; setAnswers(a => ({ ...a, path, purpose: path === "residential" ? "condition-survey" : "bespoke", propertyType: path === "residential" ? "Detached house" : path === "commercial" ? "Office building" : "Agricultural / rural land" })); setServiceId(""); }} >{config.paths.map(path => <option key={path} value={path}>{path === "residential" ? "Residential property" : path === "commercial" ? "Commercial property" : "Land"}</option>)}</select></label>
        <label>What do you need?<select value={answers.purpose} onChange={e => setAnswers(a => ({ ...a, purpose: e.target.value as FormSubmission["answers"]["purpose"] }))}>{effectiveAnswers.path === "residential" ? <><option value="condition-survey">Condition survey</option><option value="survey-and-valuation">Survey and valuation</option><option value="formal-valuation">Formal valuation</option><option value="roof-only">Roof / high-level inspection</option></> : null}<option value="bespoke">Advice / bespoke enquiry</option></select></label>
        <label>Property / land type<select value={answers.propertyType} onChange={e => setAnswers(a => ({ ...a, propertyType: e.target.value }))}>{propertyTypeOptions.filter(o => effectiveAnswers.path === "residential" ? !["office", "warehouse", "commercial", "land", "woodland", "developmentLand", "coastalWetland"].includes(o.artwork) : effectiveAnswers.path === "commercial" ? ["office", "warehouse", "commercial"].includes(o.artwork) : ["land", "woodland", "developmentLand", "coastalWetland"].includes(o.artwork)).map(o => <option key={o.label}>{o.label}</option>)}<option>Other</option></select></label>
        <label>Approximate property age<select value={answers.propertyAge} onChange={e => setAnswers(a => ({ ...a, propertyAge: e.target.value as FormSubmission["answers"]["propertyAge"] }))}><option value="unknown">Unknown / not applicable</option><option value="pre-1950">Before 1950</option><option value="1950-1989">1950–1989</option><option value="post-1990">1990 onwards</option><option value="listed-historic">Listed / historic</option></select></label></div> : null}
        {step === 1 ? <div className="wf-fields">{config.questions.filter(q => q !== "phone").map(q => q === "concerns" ? <label key={q}>Main concerns<textarea maxLength={2000} rows={4} value={answers.concerns} onChange={e => setAnswers(a => ({ ...a, concerns: e.target.value }))}/></label> : <fieldset key={q}><legend>Known major alterations (optional)</legend>{alterations.map(o => <label className="wf-check" key={o.value}><input type="checkbox" checked={answers.alterationTypes.includes(o.value)} onChange={e => setAnswers(a => ({ ...a, alterationTypes: e.target.checked ? [...a.alterationTypes, o.value] : a.alterationTypes.filter(v => v !== o.value) }))}/>{o.label}</label>)}</fieldset>)}{effectiveAnswers.path === "residential" && !availableServices.some(s => s.adviser) ? <label>Service (optional)<select value={selectedService ?? ""} onChange={e => setServiceId(e.target.value)}><option value="">Ask the practice to recommend</option>{availableServices.map(s => <option value={s.id} key={s.id}>{s.name}</option>)}</select></label> : null}<p>{config.helpText || "No additional details are required. Continue to contact information."}</p></div> : null}
        {step === 2 ? <div className="wf-fields"><div className="wf-row"><label>First name<input required autoComplete="given-name" maxLength={80} value={contact.firstName} onChange={e => setContact(c => ({ ...c, firstName: e.target.value }))}/></label><label>Last name<input required autoComplete="family-name" maxLength={80} value={contact.lastName} onChange={e => setContact(c => ({ ...c, lastName: e.target.value }))}/></label></div><label>Email<input required type="email" autoComplete="email" value={contact.email} onChange={e => setContact(c => ({ ...c, email: e.target.value }))}/></label>{config.questions.includes("phone") ? <label>Phone (optional)<input type="tel" autoComplete="tel" maxLength={40} value={contact.phone} onChange={e => setContact(c => ({ ...c, phone: e.target.value }))}/></label> : null}<label>Property address / land location<input required autoComplete="address-line1" maxLength={200} value={address.line1} onChange={e => setAddress(a => ({ ...a, line1: e.target.value }))}/></label><label>Address line 2 (optional)<input autoComplete="address-line2" maxLength={200} value={address.line2} onChange={e => setAddress(a => ({ ...a, line2: e.target.value }))}/></label><div className="wf-row"><label>Town / nearest town<input required autoComplete="address-level2" maxLength={100} value={address.city} onChange={e => setAddress(a => ({ ...a, city: e.target.value }))}/></label><label>Postcode / nearest postcode<input required autoComplete="postal-code" minLength={3} maxLength={12} value={address.postcode} onChange={e => setAddress(a => ({ ...a, postcode: e.target.value.toUpperCase() }))}/></label></div><label>Country<select value={address.country} onChange={e => setAddress(a => ({ ...a, country: e.target.value as FormSubmission["address"]["country"] }))}><option value="ENG">England</option><option value="WLS">Wales</option><option value="SCT">Scotland</option><option value="NIR">Northern Ireland</option></select></label></div> : null}
        {step === 3 ? <div className="wf-fields"><h2>{decision.service && context.quotesReady ? decision.service.name : "Bespoke enquiry"}</h2><p>{decision.reason}</p>{decision.service && context.quotesReady && decision.money ? <><p>{decision.service.description || "The practice will confirm the agreed scope. This is not an inspection or professional finding."}</p><dl><div><dt>Base price</dt><dd>{money(decision.service.baseAmountMinor)}</dd></div>{decision.surcharges.map((s, i) => <div key={i}><dt>{s.label}</dt><dd>{money(s.amountMinor)}</dd></div>)}<div><dt>VAT</dt><dd>{money(decision.money.vatMinor)}</dd></div><div><dt>Total</dt><dd>{money(decision.money.totalMinor)}</dd></div><div><dt>Deposit</dt><dd>{money(decision.money.depositMinor)}</dd></div></dl><p>Quote valid for {decision.service.validityDays} days. No payment is taken here.</p></> : <p>No price is assumed. {config.enquiriesEnabled || preview ? "Your enquiry will be reviewed by the practice." : "Contact the practice below; online enquiries are not enabled."}</p>}<p><strong>{contact.firstName} {contact.lastName}</strong><br/>{contact.email}<br/>{[address.line1, address.line2, address.city, address.postcode].filter(Boolean).join(", ")}</p><p>{answers.propertyType} · {answers.propertyAge}<br/>{answers.concerns}</p><button type="button" onClick={() => move(0)}>Edit property answers</button><button type="button" onClick={() => move(2)}>Edit contact details</button><label className="wf-check"><input type="checkbox" required checked={privacy} onChange={e => setPrivacy(e.target.checked)}/>I have read the {config.privacyUrl ? <a href={config.privacyUrl} target="_blank" rel="noopener noreferrer">privacy notice</a> : "privacy notice (setup required)"} and understand how my enquiry is handled.</label><p><ShieldCheck size={16}/> Customer statements only. The surveyor must verify information before using it in a report.</p></div> : null}
        <label className="wf-honeypot" aria-hidden="true" htmlFor={`${id}-website`}>Leave this empty<input id={`${id}-website`} tabIndex={-1} autoComplete="off" value={website} onChange={e => setWebsite(e.target.value)}/></label>
        {error ? <p role="alert" className="wf-error">{error}</p> : null}<div className="wf-actions">{step > 0 ? <button type="button" disabled={busy} onClick={() => move(step - 1)}><ArrowLeft size={16}/>Back</button> : null}<button className="wf-primary" disabled={busy || (step === 3 && !preview && (!config.privacyUrl || (!context.quotesReady || !decision.service) && !config.enquiriesEnabled))}>{busy ? "Submitting…" : step === 3 ? config.buttonLabel : "Continue"}<ArrowRight size={16}/></button></div>
      </form></>}
    <footer className="wf-footer">{config.contactEmail ? <a href={`mailto:${config.contactEmail}`}>{config.contactEmail}</a> : null}{config.contactPhone ? <a href={`tel:${config.contactPhone.replace(/[^+\d]/g, "")}`}>{config.contactPhone}</a> : null}<span>Securely supported by Surveynt</span></footer>
  </section>;
}
