"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { Copy, Eye, Save, Upload, Smartphone, Tablet, Monitor } from "lucide-react";
import { brandColours, formPaths, optionalQuestions, publicationWarnings, websiteFormSchema, type WebsiteFormConfig } from "@/lib/website-form-config";
import type { StudioData } from "@/lib/website-form-studio-data";
import "./website-form.css";
export function WebsiteFormStudio({ initial, canEdit }: { initial: StudioData; canEdit: boolean }) {
  const [previewMode, setPreviewMode] = useState("configured");
  const [saved, setSaved] = useState(initial), [config, setConfig] = useState<WebsiteFormConfig>(initial.config), [view, setView] = useState("edit"), [width, setWidth] = useState(390), [status, setStatus] = useState(""), [error, setError] = useState(""), [busy, setBusy] = useState(false), [origin, setOrigin] = useState("");
  const frame = useRef<HTMLIFrameElement>(null), draft = useRef({ config, mode: previewMode });
  const dirty = JSON.stringify(config) !== JSON.stringify(saved.config), warnings = publicationWarnings(config);
  function update<K extends keyof WebsiteFormConfig>(key: K, value: WebsiteFormConfig[K]) { setConfig(c => ({ ...c, [key]: value })); setStatus(""); }
  useEffect(() => {
    queueMicrotask(() => setOrigin(window.location.origin));
    const receive = (event: MessageEvent) => { if (event.origin === window.location.origin && event.source === frame.current?.contentWindow && event.data?.type === "surveynt:preview-ready") frame.current.contentWindow?.postMessage({ type: "surveynt:preview", ...draft.current }, window.location.origin); };
    window.addEventListener("message", receive); return () => window.removeEventListener("message", receive);
  }, []);
  useEffect(() => { draft.current = { config, mode: previewMode }; frame.current?.contentWindow?.postMessage({ type: "surveynt:preview", config, mode: previewMode }, window.location.origin); }, [config, previewMode]);
  useEffect(() => {
    const warn = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); };
    const navigate = (event: MouseEvent) => { const link = (event.target as HTMLElement).closest("a[href]") as HTMLAnchorElement | null; if (!dirty || !link || link.target === "_blank" || link.hasAttribute("download")) return; const destination = new URL(link.href); if (destination.origin === location.origin && destination.pathname !== location.pathname && !window.confirm("Leave without saving your form changes?")) { event.preventDefault(); event.stopPropagation(); } };
    window.addEventListener("beforeunload", warn); document.addEventListener("click", navigate, true); return () => { window.removeEventListener("beforeunload", warn); document.removeEventListener("click", navigate, true); };
  }, [dirty]);
  function tabKey(event: React.KeyboardEvent) {
    if (!["ArrowLeft", "ArrowRight", "Home", "End"].includes(event.key)) return;
    event.preventDefault(); const next = event.key === "Home" ? "edit" : event.key === "End" ? "preview" : view === "edit" ? "preview" : "edit"; setView(next); requestAnimationFrame(() => document.getElementById(`studio-tab-${next}`)?.focus());
  }
  async function change(action: "save" | "publish" | "restore", versionId?: string) {
    const parsed = websiteFormSchema.safeParse(config); if (!parsed.success) { setError(parsed.error.issues.map(i => i.message).join(" ")); return; }
    setBusy(true); setError("");
    try {
      const response = await fetch("/api/v1/operations/website-form", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ revision: saved.revision, action, ...(action === "restore" ? { versionId } : { config: parsed.data }) }) });
      const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message ?? "The form could not be saved.");
      const reload = await fetch("/api/v1/operations/website-form", { cache: "no-store" }); const body = await reload.json(); if (!reload.ok) throw new Error("Saved, but refresh failed. Reload this page before editing further.");
      setSaved(s => ({ ...s, ...body.data })); setConfig(body.data.config); setStatus(action === "save" ? "Draft saved. Your live form is unchanged." : action === "restore" ? "Previous configuration republished as a new version." : "Published. Your website embed now uses this version.");
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Save failed."); } finally { setBusy(false); }
  }
  const embedUrl = `${origin}/embed/${initial.slug}`, standaloneUrl = `${origin}/quote/start/${initial.slug}`;
  const snippet = `<iframe src="${embedUrl}?parentOrigin=${config.approvedOrigins[0] ?? "https://your-website.example"}" title="${config.displayName.replace(/[<>"&]/g, "")} survey enquiry" data-surveynt-embed style="width:100%;height:1100px;border:0" loading="lazy"></iframe>\n<script src="${origin}/surveynt-embed.js" defer></script>`;
  return <><div className="action-row studio-breadcrumb"><Link href={`/app/${initial.slug}/settings`}>Practice settings</Link><span>Website form</span></div><header className="studio-heading"><h1>Website form studio</h1><p>Customise your website enquiry journey. The preview is the actual embedded form in its own viewport.</p></header>
    <div className="studio-status" role="status">{initial.previewOnly ? "Local preview only — changes cannot be saved or published." : saved.activeVersionId ? "Published version available" : "Not published"} · Draft revision {saved.revision} · {dirty ? "Unsaved changes" : "Draft saved"}{status ? <p>{status}</p> : null}</div>
    {error ? <p className="form-error" role="alert">{error}</p> : null}<div className="action-row"><button className="button" disabled={!dirty || busy} onClick={() => { setConfig(saved.config); setError(""); setStatus("Unsaved changes discarded."); }}>Discard unsaved changes</button><button className="button" disabled={!canEdit || busy || !dirty} onClick={() => void change("save")}><Save size={16}/>Save draft</button><button className="button button-primary" disabled={!canEdit || busy || !!warnings.length} onClick={() => void change("publish")}><Upload size={16}/>Publish form</button></div>
<details className="panel studio-panel studio-readiness"><summary><h2>Readiness</h2><span>{warnings.length ? `${warnings.length} setup items to review` : "Configuration ready"}</span></summary><div>{warnings.length ? <ul>{warnings.map(w => <li key={w}>{w}</li>)}</ul> : <p>Configuration is ready to publish.</p>}<p>{initial.quotesReady ? "Instant quoting is configured." : "Instant quotes require secure quote links and public quote enablement. Bespoke enquiries can be enabled independently."} Payments and calendars retain their existing approval/configuration gates.</p></div></details>
    <div className="studio-tabs" role="tablist" aria-label="Studio view"><button role="tab" id="studio-tab-edit" tabIndex={view === "edit" ? 0 : -1} onKeyDown={tabKey} aria-selected={view === "edit"} aria-controls="studio-controls" className="button" onClick={() => setView("edit")}>Edit</button><button role="tab" id="studio-tab-preview" tabIndex={view === "preview" ? 0 : -1} onKeyDown={tabKey} aria-selected={view === "preview"} aria-controls="studio-preview" className="button" onClick={() => setView("preview")}><Eye size={16}/>Preview</button></div>
    <div className="form-studio" data-view={view}><div id="studio-controls" className="studio-controls">
      <fieldset><legend>Brand and content</legend>{(["displayName", "logoUrl", "heading", "introduction", "helpText", "buttonLabel", "contactEmail", "contactPhone", "privacyUrl"] as const).map(key => <label key={key}>{({ displayName: "Practice display name", logoUrl: "Logo HTTPS URL", heading: "Heading", introduction: "Introduction", helpText: "Help text", buttonLabel: "Submission button label", contactEmail: "Contact email", contactPhone: "Contact telephone", privacyUrl: "Privacy notice HTTPS URL" })[key]}<input className="input" value={config[key]} maxLength={["introduction", "helpText"].includes(key) ? 600 : key.endsWith("Url") ? 500 : 120} onChange={e => update(key, e.target.value)}/></label>)}<label>Approved accent colour<select className="input" value={config.accentColour} onChange={e => update("accentColour", e.target.value as WebsiteFormConfig["accentColour"])}>{brandColours.map((colour, i) => <option key={colour} value={colour}>{["Surveynt blue", "Deep blue", "Slate"][i]}</option>)}</select></label></fieldset>
      <fieldset><legend>Journey and appearance</legend>{formPaths.map(path => <label className="studio-check" key={path}><input type="checkbox" disabled={config.paths.length === 1 && config.paths.includes(path)} checked={config.paths.includes(path)} onChange={e => update("paths", e.target.checked ? [...config.paths, path] : config.paths.filter(p => p !== path))}/>{path}</label>)}{optionalQuestions.map(q => <div key={q} className="action-row"><label className="studio-check"><input type="checkbox" checked={config.questions.includes(q)} onChange={e => update("questions", e.target.checked ? [...config.questions, q] : config.questions.filter(p => p !== q))}/>{q}</label>{config.questions.includes(q) ? <button className="button" disabled={config.questions.indexOf(q) === 0} onClick={() => { const questions = [...config.questions], index = questions.indexOf(q); [questions[index - 1], questions[index]] = [questions[index], questions[index - 1]]; update("questions", questions); }}>Move earlier</button> : null}</div>)}<label className="studio-check"><input type="checkbox" checked={config.showArtwork} onChange={e => update("showArtwork", e.target.checked)}/>Show illustrative property artwork</label><label>Spacing<select className="input" value={config.density} onChange={e => update("density", e.target.value as WebsiteFormConfig["density"])}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label><p>Required fields, privacy acknowledgement and evidence labels cannot be removed. Phone remains in the contact step.</p></fieldset>
      <fieldset><legend>Available services</legend><p>No selection means all active catalogue services. Prices are managed in Operations, not this editor.</p>{initial.services.map(service => <label className="studio-check" key={service.id}><input type="checkbox" checked={config.serviceIds.includes(service.id)} onChange={e => update("serviceIds", e.target.checked ? [...config.serviceIds, service.id] : config.serviceIds.filter(id => id !== service.id))}/>{service.name}</label>)}</fieldset>
      <fieldset><legend>Website installation</legend><label className="studio-check"><input type="checkbox" checked={config.enabled} onChange={e => update("enabled", e.target.checked)}/>Enable public form</label><label className="studio-check"><input type="checkbox" checked={config.enquiriesEnabled} onChange={e => update("enquiriesEnabled", e.target.checked)}/>Accept bespoke enquiries</label><label>Approved website origins (one per line)<textarea className="input" rows={4} value={config.approvedOrigins.join("\n")} onChange={e => update("approvedOrigins", e.target.value.split("\n").filter(Boolean))}/></label><p>Exact HTTPS origins, such as https://www.yourpractice.co.uk. Include each website domain separately. No wildcards.</p></fieldset>
</div><section id="studio-preview" className="studio-preview" aria-label="Live form preview"><div className="studio-preview-title"><Eye size={18}/><h2>Live preview</h2></div><div className="studio-toolbar">{[{ label: "Phone", width: 390, icon: Smartphone }, { label: "Tablet", width: 768, icon: Tablet }, { label: "Desktop", width: 960, icon: Monitor }].map(preset => <button className="button" aria-pressed={width === preset.width} key={preset.label} onClick={() => setWidth(preset.width)}><preset.icon size={16}/>{preset.label}</button>)}<label>Preview scenario<select value={previewMode} onChange={e => setPreviewMode(e.target.value)}><option value="configured">Current readiness</option><option value="quote">Quote available (simulation)</option><option value="enquiry">Quotes unavailable / enquiry</option><option value="unavailable">Form unavailable</option></select></label><label>Viewport width <input type="number" min={320} max={1920} value={width} onChange={e => setWidth(Math.min(1920, Math.max(320, Number(e.target.value) || 390)))}/></label></div><p>{width}px viewport · 1:1, no scaling. Scroll horizontally if needed. Preview actions never submit.</p><div className="studio-preview-inner" style={{ width }}><iframe ref={frame} title="Interactive website form preview" src={`/website-form-preview/${initial.slug}`} style={{ width, height: 1300, border: 0, background: "white" }}/></div></section></div>
    <section className="panel studio-panel"><h2>Install on your website</h2><p>Publish first, then paste this code into an HTML block. The URL remains stable when you publish changes.</p><pre className="studio-code">{snippet}</pre><button className="button" onClick={() => { navigator.clipboard.writeText(snippet).then(() => setStatus("Embed code copied.")).catch(() => setError("Copy unavailable. Select the code above and copy it manually.")); }}><Copy size={16}/>Copy embed code</button><p>Standalone form: <a href={standaloneUrl} target="_blank" rel="noopener noreferrer">{standaloneUrl}</a></p><p>Optional resize script adjusts the iframe height. If your website blocks scripts, retain the iframe and fixed height. Website builders may require a paid HTML/embed block.</p></section>
    <section className="panel studio-panel"><h2>Published versions</h2>{!saved.versions.length ? <p>No versions published yet.</p> : saved.versions.map(version => <div className="action-row" key={version.id}><span>{version.id === saved.activeVersionId ? "Active · " : ""}{new Date(version.createdAt).toLocaleString("en-GB")} · Publisher {version.publishedByUserId ?? "Unknown"}</span><button className="button" disabled={!canEdit || busy || dirty || version.id === saved.activeVersionId} onClick={() => void change("restore", version.id)}>Restore and publish</button></div>)}</section>
  </>;
}
