"use client";
import { useEffect, useState } from "react";
type Enquiry = { id: string; reference: string; firstName: string; lastName: string; email: string; phone: string | null; status: string; reason: string; isDemo: boolean; createdAt: string; address: Record<string, unknown>; answers: Record<string, unknown> };
export function WebsiteEnquiries({ canEdit }: { canEdit: boolean }) {
  const [rows, setRows] = useState<Enquiry[]>([]), [error, setError] = useState(""), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false);
  useEffect(() => { let active = true; fetch("/api/v1/operations/website-enquiries", { cache: "no-store" }).then(async r => { const p = await r.json(); if (!r.ok) throw new Error(p.error?.message); if (active) setRows(p.data); }).catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  async function update(id: string, status: string) { setBusy(true); setError(""); try { const r = await fetch("/api/v1/operations/website-enquiries", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, status }) }); const p = await r.json(); if (!r.ok) throw new Error(p.error?.message); setRows(rows => rows.map(row => row.id === id ? p.data : row)); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <section className="panel"><h2>Website enquiries</h2><p>Bespoke requests and enquiries awaiting a supported quote. Customer statements are not survey findings. Showing the latest 100.</p>{error ? <p role="alert">{error}</p> : null}{loading ? <p role="status">Loading enquiries…</p> : !rows.length ? <p>No website enquiries yet.</p> : rows.map(row => <details key={row.id}><summary>{row.reference} · {row.firstName} {row.lastName} · {row.status}{row.isDemo ? " · Simulated" : ""}</summary><p>{row.reason}</p><a href={`mailto:${row.email}`}>{row.email}</a><p>{row.phone}</p><dl>{Object.entries({ ...row.address, ...row.answers }).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{typeof value === "string" ? value : JSON.stringify(value)}</dd></div>)}</dl><label>Status<select className="input" value={row.status} disabled={!canEdit || busy} onChange={e => void update(row.id, e.target.value)}><option value="new">New</option><option value="contacted">Contacted</option><option value="closed">Closed</option></select></label></details>)}</section>;
}
