import { z } from "zod";
import { and, eq } from "drizzle-orm";
import { auditEvents, createDatabase, customerQuotes, quoteSnapshots, withTenant } from "@surveynt/db";
import { canMutateOperations } from "@surveynt/domain";
import { apiContext, canWriteWorkspace } from "@/lib/access";
import { ok, parseBody, problem } from "@/lib/api";

const schema = z.object({ version: z.number().int().positive(), action: z.enum(["cancel", "revoke_link", "reissue_link"]) });
export async function GET(request: Request, route: RouteContext<"/api/v1/quotes/[id]">) { const context = await apiContext(request); if (!context) return problem(401, "unauthorised", "Authentication is required."); const { id } = await route.params; if (!z.uuid().safeParse(id).success) return problem(404, "not_found", "Quote not found."); if (context.demo) return problem(404, "not_found", "Quote not found."); const rows = await withTenant(createDatabase(), context.organisationId, (tx) => tx.select().from(customerQuotes).where(and(eq(customerQuotes.id, id), eq(customerQuotes.organisationId, context.organisationId))).limit(1)); return rows[0] ? ok(rows[0]) : problem(404, "not_found", "Quote not found."); }
export async function PATCH(request: Request, route: RouteContext<"/api/v1/quotes/[id]">) { const context = await apiContext(request); if (!context) return problem(401, "unauthorised", "Authentication is required."); if (!canWriteWorkspace(context)) return problem(402, "workspace_read_only", "Restore billing before changing quotes."); if (!canMutateOperations(context.role)) return problem(403, "forbidden", "Only owners and administrators can manage customer quote access."); const parsed = await parseBody(request, schema); if (!parsed.success) return problem(400, "invalid_request", "The quote update is invalid."); const { id } = await route.params; if (!z.uuid().safeParse(id).success) return problem(404, "not_found", "Quote not found."); if (context.demo) return ok({ id, version: parsed.data.version + 1 }, { demo: true, persisted: false });
  const result = await withTenant(createDatabase(), context.organisationId, async (tx) => { const [quote] = await tx.update(customerQuotes).set({ ...(parsed.data.action === "cancel" ? { status: "cancelled" as const } : {}), tokenRevokedAt: parsed.data.action === "reissue_link" ? null : new Date(), version: parsed.data.version + 1, updatedAt: new Date() }).where(and(eq(customerQuotes.id, id), eq(customerQuotes.organisationId, context.organisationId), eq(customerQuotes.version, parsed.data.version))).returning(); if (!quote) return null; await tx.insert(quoteSnapshots).values({ organisationId: context.organisationId, quoteId: quote.id, event: parsed.data.action, snapshot: { status: quote.status, version: quote.version, tokenRevokedAt: quote.tokenRevokedAt?.toISOString() ?? null } }); await tx.insert(auditEvents).values({ organisationId: context.organisationId, actorUserId: context.internalUserId, action: `quote.${parsed.data.action}`, resourceType: "quote", resourceId: quote.id, metadata: { version: quote.version } }); return quote; }); return result ? ok(result) : problem(409, "quote_changed", "The quote changed or was not found. Reload and try again."); }
