import Link from "next/link";
import { requireWorkspacePageAccess } from "@/lib/workspace-page-access";
import { and,desc,eq } from "drizzle-orm";
import { createDatabase,jobs,reportApprovals,reportVersions,surveys,withTenant } from "@surveynt/db";
import { defaultTemplate } from "@surveynt/assistant";
import { hasProfessionalPermission } from "@surveynt/domain";
import { requireFirmAccess } from "@/lib/access";
import { canAuthorWording,listWording } from "@/lib/wording";
import { demoClauses } from "@/lib/demo-wording";
import { WordingLibrary,type LibraryClause } from "@/components/wording-library";
import { PageHeader } from "@/components/page-header";
export const metadata={title:"Reports library"};export const dynamic="force-dynamic";
export default async function Page({params,searchParams}:PageProps<"/app/[organisationSlug]/reports">){
  const {organisationSlug}=await params,access=await requireFirmAccess(organisationSlug),view=(await searchParams).view??"versions",base=`/app/${organisationSlug}/reports`;
  await requireWorkspacePageAccess(organisationSlug, "reports");
  const rows=view==="versions"&&access.userId!=="demo_user"?await withTenant(createDatabase(),access.organisationId,tx=>tx.select({id:reportVersions.id,version:reportVersions.versionNumber,jobId:reportVersions.jobId,reference:jobs.reference,surveyId:surveys.id,surveyStatus:surveys.status,approvedAt:reportApprovals.createdAt,createdAt:reportVersions.createdAt}).from(reportVersions).innerJoin(jobs,and(eq(jobs.id,reportVersions.jobId),eq(jobs.organisationId,access.organisationId))).innerJoin(surveys,and(eq(surveys.id,reportVersions.surveyId),eq(surveys.organisationId,access.organisationId))).leftJoin(reportApprovals,eq(reportApprovals.reportVersionId,reportVersions.id)).where(and(eq(reportVersions.organisationId,access.organisationId),access.userRole==="surveyor"?eq(jobs.assignedSurveyorId,access.internalUserId!):undefined)).orderBy(desc(reportVersions.createdAt)).limit(100)):[];
  const clauses=view==="wording"?(access.userId==="demo_user"?demoClauses:await listWording(access)) as LibraryClause[]:[];
  const elements=defaultTemplate.sections.flatMap(s=>s.elements.map(e=>({key:`${s.key}.${e.key}`,label:`${s.label}: ${e.label}`})));
  return <main className="page"><PageHeader title="Reports library" description="Reviewed versions, the protected survey template and approved practice wording."/><nav className="section-tabs" aria-label="Reports views">{[["versions","Report versions"],["templates","Templates"],["wording","Wording"]].map(([key,label])=><Link key={key} className={view===key?"active":""} href={`${base}?view=${key}`}>{label}</Link>)}</nav>{view==="versions"?<section className="panel"><div className="panel-header"><h2>Report versions</h2><p>Approval belongs to one immutable version, not a job label.</p></div>{rows.length?<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Job</th><th>Version</th><th>Review</th><th>Created</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><Link href={`/app/${organisationSlug}/jobs/${r.jobId}`}>{r.reference}</Link></td><td>Version {r.version}</td><td>{r.approvedAt?"Approved":"Draft — review required"}</td><td>{r.createdAt.toLocaleDateString("en-GB")}</td></tr>)}</tbody></table></div>:<div className="empty-state"><strong>No report versions yet</strong><span>Compose a report from a job’s inspection workspace.</span></div>}</section>:null}{view==="templates"?<section className="panel action-panel"><h2>{defaultTemplate.title}</h2><p>Version {defaultTemplate.version} · {defaultTemplate.sections.length} sections</p><p>Template structure, question wording, section order and rating presentation remain protected. Assistance sits alongside the inspection.</p><ol>{defaultTemplate.sections.map(s=><li key={s.key}>{s.label} · {s.elements.length} elements</li>)}</ol><Link className="button button-primary" href={`/app/${organisationSlug}/jobs`}>Open an inspection workspace</Link></section>:null}{view==="wording"?<WordingLibrary clauses={clauses} elements={elements} canAuthor={access.accessLevel==="full"&&canAuthorWording(access.userRole, access.canRecordSurvey)} canApprove={access.accessLevel==="full"&&hasProfessionalPermission(access.userRole, "approve_reports", access.canApproveReports)} demo={access.userId==="demo_user"}/>:null}</main>;
}
