import { OTHER_OVERRIDE, type RuleSet } from "./types";

// Surveynt-authored completion rules for surveynt-residential@1.0.0. They are
// product defaults that a qualified surveyor must review before production use.

export const residentialRulesV1: RuleSet = {
  key: "surveynt-residential-rules",
  version: "1.0.0",
  templateKey: "surveynt-residential",
  templateVersions: ["1.0.0"],
  reviewStatus: "draft_requires_surveyor_review",
  rules: [
    {
      id: "FLAT-COMMUNAL",
      title: "Flats and maisonettes: communal areas and tenure",
      scope: "survey",
      when: { type: "field_in", path: "about.property.property_type", values: ["flat", "maisonette"] },
      require: [{ type: "element_status_recorded", element: "grounds.communal_areas" }, { type: "field_answered", path: "about.property.tenure" }],
      severity: "hard_gate",
      justification: "A flat depends on shared structure and services. The report must say what communal parts were and were not seen, and the reported tenure.",
      overrideReasons: ["Communal areas excluded by the instructions", "Access to communal areas not available", OTHER_OVERRIDE],
    },
    {
      id: "EXTENSION-APPROVALS",
      title: "Extensions or alterations: approvals for legal advisers",
      scope: "survey",
      when: { type: "field_in", path: "about.property.extensions_present", values: [true] },
      require: [{ type: "field_provided", path: "matters.legal.approvals" }],
      severity: "hard_gate",
      justification: "Observed alterations may need planning permission, building regulation approval or other consents that legal advisers should check.",
      overrideReasons: ["Alterations predate any approval requirement", OTHER_OVERRIDE],
    },
    {
      id: "LIMITATION-RECORDED",
      title: "Limited inspection: record the limitation",
      scope: "each_element",
      when: { type: "element_status_in", element: "$element", statuses: ["partially_inspected", "not_inspected", "inaccessible"] },
      require: [{ type: "limitation_recorded", element: "$element" }],
      severity: "hard_gate",
      justification: "The client must be told what could not be seen and why. This cannot be overridden.",
      overrideReasons: [],
    },
    {
      id: "SERIOUS-RATING-COMMENTARY",
      title: "Serious defect rating: commentary required",
      scope: "each_element",
      when: { type: "rating_in", element: "$element", ratings: ["3"] },
      require: [{ type: "field_provided", path: "$element.commentary" }],
      severity: "hard_gate",
      justification: "A serious or urgent rating must be explained in the surveyor's own words, at every service level.",
      overrideReasons: [],
    },
    {
      id: "DEFECT-DETAIL",
      title: "Defect: location, evidence and next action",
      scope: "each_observation",
      when: { type: "observation_is_defect" },
      require: [{ type: "observation_location" }, { type: "observation_evidence", min: 1 }, { type: "observation_next_action" }],
      severity: "hard_gate",
      justification: "Each defect needs a location, supporting evidence and a recommended next action so it can be acted on and traced.",
      overrideReasons: ["Evidence could not be captured safely", OTHER_OVERRIDE],
    },
    {
      id: "LISTED-GRADE",
      title: "Listed building: record the grade or category",
      scope: "survey",
      when: { type: "field_in", path: "about.property.listed_status", values: ["listed"] },
      require: [{ type: "field_answered", path: "about.property.listing_grade" }],
      severity: "advisory",
      justification: "Recording the grade or category from the list entry helps legal advisers check consent requirements.",
      overrideReasons: [],
    },
    {
      id: "ROOF-SPACE-GENERAL-LIMITATION",
      title: "Roof space not seen: general limitation",
      scope: "survey",
      when: { type: "element_status_in", element: "inside.roof_structure", statuses: ["not_inspected", "inaccessible"] },
      require: [{ type: "field_provided", path: "inspection.visit.general_limitations" }],
      severity: "advisory",
      justification: "Not seeing the roof space limits the inspection of several elements; say so in the general limitations.",
      overrideReasons: [],
    },
  ],
};
