import {resolveWorkspace,workspaceRoute} from "@/lib/workspace-mode";
import { auth, currentUser } from "@clerk/nextjs/server";
import { and, eq, sql } from "drizzle-orm";
import { auditEvents, createDatabase, memberWorkProfiles, organisationMemberships, organisations, userProfiles, users } from "@surveynt/db";
import { z } from "zod";
import { isClerkConfigured } from "@/lib/access";
import { defaultAppearance } from "@/lib/appearance";
import { professionalDetailsSchema } from "@/lib/professional-details";
import { ok, parseBody, problem } from "@/lib/api";
const hour = z.object({ closed: z.boolean().optional(), start: z.string().regex(/^(?:[01]\d|2[0-3]):[0-5]\d$/), end: z.string().regex(/^(?:[01]\d|2[0-3]):[0-5]\d$/) }).refine((v) => v.closed || v.start < v.end);
const schema = z.object({ professionalDetails:professionalDetailsSchema.optional(), ricsNumber: z.string().trim().max(40).nullable().optional(), appearance: z.object({ theme: z.enum(["system", "light", "dark"]), reducedMotion: z.boolean(), contrast: z.enum(["standard", "high"]), density: z.enum(["comfortable", "compact"]), textSize: z.enum(["standard", "large"]) }).optional(), notifications: z.record(z.string(), z.boolean()).optional(), work: z.object({ timezone: z.string().refine((v) => { try { new Intl.DateTimeFormat("en", { timeZone:v }); return true; } catch { return false; } }), workingHours: z.partialRecord(z.enum(["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]), hour), routeOrigin: z.string().trim().max(500).nullable(), latitude: z.number().min(-90).max(90).nullable(), longitude: z.number().min(-180).max(180).nullable() }).refine((v) => (v.latitude === null) === (v.longitude === null)).optional() });
async function identity(request?:Request) { const session = await auth(); if (!session.userId) return null; const db=createDatabase(); const [user]=await db.select().from(users).where(eq(users.clerkUserId,session.userId)).limit(1); if (!user) return null; const [membership]=session.orgId ? await db.select({org:organisations.id,role:organisationMemberships.role}).from(organisations).innerJoin(organisationMemberships,and(eq(organisationMemberships.organisationId,organisations.id),eq(organisationMemberships.userId,user.id),eq(organisationMemberships.active,true))).where(eq(organisations.clerkOrganisationId,session.orgId)).limit(1):[]; const requested=request?(workspaceRoute(new URL(request.url).pathname).requested??request.headers.get("x-surveynt-workspace-mode")):null;const instance=membership?resolveWorkspace(membership.role,requested):null;if(requested&&requested!=="default"&&!instance)return null;return {db,user,organisationId:membership?.org,workspaceMode:instance?.workspaceMode,actorRole:membership?.role}; }
export async function GET(request:Request) {
  if(!isClerkConfigured()) return ok({appearance:defaultAppearance,ricsNumber:null,notifications:{},work:null,displayName:"Maya Patel",preview:true});
  const context=await identity(request); if(!context) return problem(401,"unauthorised","Sign in to manage your account.");
  const profile=await context.db.transaction(async(tx)=>{await tx.execute(sql`select set_config('app.current_user_id',${context.user.id},true)`); if(context.organisationId) await tx.execute(sql`select set_config('app.current_organisation_id',${context.organisationId},true)`); const [own]=await tx.select().from(userProfiles).where(eq(userProfiles.userId,context.user.id)).limit(1); const [work]=context.organisationId ? await tx.select().from(memberWorkProfiles).where(and(eq(memberWorkProfiles.userId,context.user.id),eq(memberWorkProfiles.organisationId,context.organisationId))).limit(1):[];return {appearance:own?.appearance??defaultAppearance,ricsNumber:own?.ricsNumber??null,professionalDetails:own?.professionalDetails??{},notifications:own?.notifications??{},work:work??null};});
  const reportProfile = await context.db.transaction(async tx => { await tx.execute(sql`select set_config('app.current_user_id',${context.user.id},true)`); const [own] = await tx.select({ reportName: userProfiles.reportName, reportContact: userProfiles.reportContact }).from(userProfiles).where(eq(userProfiles.userId, context.user.id)).limit(1); return own ?? { reportName: null, reportContact: {} }; });
  const clerk=await currentUser(); return ok({...profile,...reportProfile,displayName:[context.user.firstName,context.user.lastName].filter(Boolean).join(" "),imageUrl:clerk?.imageUrl});
}
export async function PATCH(request:Request){const parsed=await parseBody(request,schema.extend({reportName:z.string().trim().max(160).nullable().optional(),reportContact:z.object({email:z.union([z.email(),z.literal("")]).optional(),phone:z.string().trim().max(80).optional()}).optional()}));if(!parsed.success)return problem(400,"invalid_request","Check your profile settings.",parsed.error.flatten());if(!isClerkConfigured())return ok(parsed.data,{demo:true,persisted:false});const context=await identity(request);if(!context)return problem(401,"unauthorised","Sign in to manage your account.");if(parsed.data.work&&!context.organisationId)return problem(409,"organisation_required","Select a practice before changing availability.");await context.db.transaction(async(tx)=>{await tx.execute(sql`select set_config('app.current_user_id',${context.user.id},true)`);if(context.organisationId)await tx.execute(sql`select set_config('app.current_organisation_id',${context.organisationId},true)`);const {work,...profile}=parsed.data;if(Object.keys(profile).length)await tx.insert(userProfiles).values({userId:context.user.id,...profile}).onConflictDoUpdate({target:userProfiles.userId,set:{...profile,updatedAt:new Date()}});if(work&&context.organisationId)await tx.insert(memberWorkProfiles).values({organisationId:context.organisationId,userId:context.user.id,...work}).onConflictDoUpdate({target:[memberWorkProfiles.organisationId,memberWorkProfiles.userId],set:{...work,updatedAt:new Date()}});if(Object.keys(parsed.data).length)await tx.insert(auditEvents).values({organisationId:context.organisationId??null,actorUserId:context.user.id,action:"account.settings_updated",resourceType:"user",resourceId:context.user.id,metadata:{changed:Object.keys(parsed.data),...(context.workspaceMode?{workspaceMode:context.workspaceMode,actorRole:context.actorRole}:{})}});});return ok({saved:true});}
