import * as Location from "expo-location";
import * as TaskManager from "expo-task-manager";
import * as SecureStore from "expo-secure-store";
export const TASK="surveynt-workday-location",KEY="surveynt-tracking-session";
const STOP_KEY="surveynt-pending-stops";
export type Session={id:string;token:string;expiresAt:string;endpoint:string};
TaskManager.defineTask(TASK,async({data,error})=>{const saved=await SecureStore.getItemAsync(KEY);if(!saved)return;const session:Session=JSON.parse(saved);if(error||Date.parse(session.expiresAt)<=Date.now()){await stopSharing();return;}const locations=(data as {locations:Location.LocationObject[]}|undefined)?.locations??[];const latest=locations.at(-1);if(!latest||latest.coords.accuracy===null||Date.now()-latest.timestamp>120000)return;const now=Date.now(),last=Number(await SecureStore.getItemAsync("surveynt-last-upload")??0);if(now-last<25000)return;try{const r=await fetch(`${session.endpoint}/api/mobile/tracking/${session.id}`,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${session.token}`},body:JSON.stringify({latitude:latest.coords.latitude,longitude:latest.coords.longitude,accuracyMetres:latest.coords.accuracy??0,observedAt:new Date(latest.timestamp).toISOString()})});if(r.status===401||r.status===409)await stopSharing();if(r.ok)await SecureStore.setItemAsync("surveynt-last-upload",String(now));}catch{/* Do not queue coordinates offline. Only a fresh subsequent sample may upload. */}});
export async function flushStoppedSessions(){const pending:Session[]=JSON.parse(await SecureStore.getItemAsync(STOP_KEY)??"[]"),remaining:Session[]=[];for(const session of pending){if(Date.parse(session.expiresAt)<=Date.now())continue;try{const response=await fetch(`${session.endpoint}/api/mobile/tracking/${session.id}`,{method:"DELETE",headers:{authorization:`Bearer ${session.token}`}});if(!response.ok&&response.status!==401)remaining.push(session);}catch{remaining.push(session);}}await SecureStore.setItemAsync(STOP_KEY,JSON.stringify(remaining.slice(-10)));}
export async function stopSharing(){const saved=await SecureStore.getItemAsync(KEY);if(await Location.hasStartedLocationUpdatesAsync(TASK))await Location.stopLocationUpdatesAsync(TASK);if(saved){const pending:Session[]=JSON.parse(await SecureStore.getItemAsync(STOP_KEY)??"[]");await SecureStore.setItemAsync(STOP_KEY,JSON.stringify([...pending,JSON.parse(saved)]));}await SecureStore.deleteItemAsync(KEY);await SecureStore.deleteItemAsync("surveynt-last-upload");await flushStoppedSessions();}
export async function startSharing(session:Session){await SecureStore.setItemAsync(KEY,JSON.stringify(session));try{const foreground=await Location.requestForegroundPermissionsAsync();if(foreground.status!=="granted")throw Error("Location permission was not granted.");const background=await Location.requestBackgroundPermissionsAsync();if(background.status!=="granted")throw Error("Background location permission was not granted. Enable it in your device settings.");await Location.startLocationUpdatesAsync(TASK,{accuracy:Location.Accuracy.Balanced,timeInterval:30000,distanceInterval:20,deferredUpdatesInterval:30000,pausesUpdatesAutomatically:true,showsBackgroundLocationIndicator:true,foregroundService:{notificationTitle:"Surveynt location sharing",notificationBody:"Your practice manager can see your workday location. Stop sharing in Surveynt.",killServiceOnDestroy:true}});}catch(e){await stopSharing();throw e;}}
