import { workspaceApiGuard } from "@/lib/workspace-api-guard";
import { z } from "zod";
import { and, desc, eq, sql } from "drizzle-orm";
import { auditEvents, createDatabase, serviceDefinitions, servicePricingVersions, withTenant } from "@surveynt/db";
import { isManagementRole } from "@surveynt/domain";
import { apiContext, canWriteWorkspace } from "@/lib/access";
import { ok, parseBody, problem } from "@/lib/api";

const schema = z.object({ name: z.string().trim().min(2).max(160), baseAmountMinor: z.number().int().min(0).max(100_000_000), vatBasisPoints: z.number().int().min(0).max(10_000), depositBasisPoints: z.number().int().min(0).max(10_000), durationMinutes: z.number().int().min(15).max(2880), validityDays: z.number().int().min(1).max(365), surcharges: z.record(z.string(), z.object({ label: z.string().max(120), amountMinor: z.number().int().min(0) })), recommendationRules: z.record(z.string(), z.unknown()), active: z.boolean() });

export async function PATCH(request: Request, route: RouteContext<"/api/v1/service-catalogue/[id]">) {
  const context = await apiContext(request); if (!context) return problem(401, "unauthorised", "Authentication is required."); if (!canWriteWorkspace(context)) return problem(402, "workspace_read_only", "Restore billing before changing services."); if (!isManagementRole(context.role)) return problem(403, "forbidden", "Only owners and administrators can change pricing.");
  const accessDenial = await workspaceApiGuard(request, context);
  if (accessDenial) return accessDenial;
  const { id } = await route.params; if (!z.uuid().safeParse(id).success) return problem(404, "not_found", "Service not found."); const parsed = await parseBody(request, schema); if (!parsed.success) return problem(400, "invalid_request", "The service pricing is invalid.", parsed.error.flatten()); if (context.demo) return ok({ id, version: 2, ...parsed.data }, { demo: true, persisted: false });
  const updated = await withTenant(createDatabase(), context.organisationId, async (tx) => { await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${`service-pricing:${id}`}))`); const [service] = await tx.select().from(serviceDefinitions).where(and(eq(serviceDefinitions.id, id), eq(serviceDefinitions.organisationId, context.organisationId))).limit(1); if (!service) return null; const [latest] = await tx.select().from(servicePricingVersions).where(and(eq(servicePricingVersions.serviceDefinitionId, id), eq(servicePricingVersions.organisationId, context.organisationId))).orderBy(desc(servicePricingVersions.version)).limit(1); await tx.update(servicePricingVersions).set({ active: false, updatedAt: new Date() }).where(and(eq(servicePricingVersions.serviceDefinitionId, id), eq(servicePricingVersions.active, true))); await tx.update(serviceDefinitions).set({ name: parsed.data.name, defaultFee: (parsed.data.baseAmountMinor / 100).toFixed(2), active: parsed.data.active, updatedAt: new Date() }).where(eq(serviceDefinitions.id, id)); const [pricing] = await tx.insert(servicePricingVersions).values({ organisationId: context.organisationId, serviceDefinitionId: id, version: (latest?.version ?? 0) + 1, currency: latest?.currency ?? "GBP", baseAmountMinor: parsed.data.baseAmountMinor, vatBasisPoints: parsed.data.vatBasisPoints, depositBasisPoints: parsed.data.depositBasisPoints, durationMinutes: parsed.data.durationMinutes, validityDays: parsed.data.validityDays, surcharges: parsed.data.surcharges, recommendationRules: parsed.data.recommendationRules, active: parsed.data.active, createdByUserId: context.internalUserId }).returning(); await tx.insert(auditEvents).values({ organisationId: context.organisationId, actorUserId: context.internalUserId, action: "service_pricing.version_created", resourceType: "service_definition", resourceId: id, metadata: { pricingVersionId: pricing.id, version: pricing.version } }); return pricing; });
  return updated ? ok(updated) : problem(404, "not_found", "Service not found.");
}

export async function DELETE(request: Request, route: RouteContext<"/api/v1/service-catalogue/[id]">) {
  const context = await apiContext(request); if (!context) return problem(401, "unauthorised", "Authentication is required."); if (!canWriteWorkspace(context)) return problem(402, "workspace_read_only", "Restore billing before changing services."); if (!isManagementRole(context.role)) return problem(403, "forbidden", "Only owners and administrators can change services."); const { id } = await route.params; if (!z.uuid().safeParse(id).success) return problem(404, "not_found", "Service not found."); if (context.demo) return ok({ archived: true }, { demo: true, persisted: false });
  const accessDenial = await workspaceApiGuard(request, context);
  if (accessDenial) return accessDenial;
  const archived = await withTenant(createDatabase(), context.organisationId, async (tx) => { const [service] = await tx.update(serviceDefinitions).set({ active: false, updatedAt: new Date() }).where(and(eq(serviceDefinitions.id, id), eq(serviceDefinitions.organisationId, context.organisationId))).returning({ id: serviceDefinitions.id }); if (!service) return null; await tx.update(servicePricingVersions).set({ active: false, updatedAt: new Date() }).where(and(eq(servicePricingVersions.serviceDefinitionId, id), eq(servicePricingVersions.organisationId, context.organisationId))); await tx.insert(auditEvents).values({ organisationId: context.organisationId, actorUserId: context.internalUserId, action: "service.archived", resourceType: "service_definition", resourceId: id }); return service; }); return archived ? ok({ archived: true }) : problem(404, "not_found", "Service not found.");
}
