import {workspaceAudit} from "@/lib/workspace-audit";
import {z} from "zod";
import {and,eq} from "drizzle-orm";
import {createDatabase,withTenant,jobs,clientCasePublications,auditEvents} from "@surveynt/db";
import {apiContext} from "@/lib/access";
import {ok,problem,parseBody} from "@/lib/api";
import {workspaceApiGuard} from "@/lib/workspace-api-guard";
const input=z.object({version:z.number().int().nonnegative(),propertyInformation:z.array(z.object({label:z.string().trim().min(1).max(200),value:z.string().trim().max(2000),source:z.string().trim().min(1).max(500),retrievedAt:z.iso.datetime().nullable()})).max(80),evidence:z.array(z.object({title:z.string().trim().min(1).max(200),summary:z.string().trim().max(4000),source:z.string().trim().min(1).max(500)})).max(50)});
export async function GET(r:Request,{params}:{params:Promise<{id:string}>}){return publication(r,(await params).id);}
export async function POST(r:Request,{params}:{params:Promise<{id:string}>}){return publication(r,(await params).id);}
async function publication(r:Request,id:string){const c=await apiContext(r);if(!c)return problem(401,"unauthorised","Sign in required.");const d=await workspaceApiGuard(r,c);if(d)return d;if(!["owner","administrator","manager"].includes(c.role))return problem(403,"forbidden","Management access required.");if(!z.uuid().safeParse(id).success)return problem(404,"not_found","Job unavailable.");if(c.demo)return r.method==="GET"?ok(null):ok(null,{persisted:false});const parsed=r.method==="POST"?await parseBody(r,input):null;if(parsed&&!parsed.success)return problem(422,"invalid_publication","Check client-visible excerpts and sources.");if(r.method==="POST"&&c.accessLevel!=="full")return problem(403,"read_only","An active workspace is required to release records.");return withTenant(createDatabase(),c.organisationId,async tx=>{const [job]=await tx.select().from(jobs).where(and(eq(jobs.id,id),eq(jobs.organisationId,c.organisationId))).for("update");if(!job)return problem(404,"not_found","Job unavailable.");const [current]=await tx.select().from(clientCasePublications).where(and(eq(clientCasePublications.organisationId,c.organisationId),eq(clientCasePublications.jobId,id)));if(r.method==="GET")return ok(current??null);if(!parsed?.success)return problem(422,"invalid_publication","Check publication.");if((current?.version??0)!==parsed.data.version)return problem(409,"conflict","Publication changed. Reload before releasing.");const value={...parsed.data,version:parsed.data.version+1,releasedByUserId:c.internalUserId!,releasedAt:new Date()};const [saved]=await tx.insert(clientCasePublications).values({organisationId:c.organisationId,jobId:id,...value}).onConflictDoUpdate({target:[clientCasePublications.organisationId,clientCasePublications.jobId],set:value}).returning();await tx.insert(auditEvents).values(workspaceAudit(c,{organisationId:c.organisationId,actorUserId:c.internalUserId,action:"case.client_records_released",resourceType:"job",resourceId:id,metadata:{version:saved.version,informationCount:value.propertyInformation.length,evidenceCount:value.evidence.length}}));return ok(saved);});}
