import { afterAll, beforeAll, describe, expect, it, vi } from "vitest";
import { and, eq } from "drizzle-orm";
import { auditEvents, clientPayments, invoices, manualPaymentReviews, organisationMemberships, organisations, settlementBatchItems, settlementBatches, settlementLedger, users, withTenant, type Database } from "@surveynt/db";
import { createTestDatabase, integrationEnabled, stopRelay, type TestDatabase } from "@surveynt/db/testing";
const state = vi.hoisted(() => ({ context: { organisationId: "", internalUserId: "", userId: "finance-test", role: "owner", demo: false, accessLevel: "full" }, writable: true }));
vi.mock("../src/lib/access", () => ({ apiContext: async () => state.context, canWriteWorkspace: () => state.writable }));
vi.mock("server-only", () => ({}));
import { POST as receipt } from "../src/app/api/v1/finance/invoices/[id]/manual-payments/route";
import { POST as refund } from "../src/app/api/v1/finance/payments/[id]/manual-refund/route";
import { GET as financialExport } from "../src/app/api/v1/finance/exports/route";
import { practiceInsights } from "../src/lib/insights";
import { GET as invoiceDetail } from "../src/app/api/v1/finance/invoices/[id]/route";

describe.skipIf(!integrationEnabled)("finance completion", () => {
  let database: TestDatabase, db: Database, organisationId: string, otherId: string, invoiceId: string;
  const request = (path: string, body?: unknown) => new Request(`http://surveynt.test${path}`, body ? { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) } : {});
  const route = (id: string) => ({ params: Promise.resolve({ id }) });
  const verification = (amountMinor = 600) => ({ requestId: crypto.randomUUID(), amountMinor, expectedOutstandingMinor: 1000, method: "bank_transfer", reference: `BANK-${crypto.randomUUID()}`, evidence: "Checked fictional bank statement entry", occurredAt: new Date(Date.now()-60000).toISOString(), confirmed: true });
  beforeAll(async () => {
    database = await createTestDatabase();
    vi.stubEnv("DATABASE_ADMIN_URL", database.adminUrl); vi.stubEnv("DATABASE_APP_URL", database.appUrl);
    db = database.connect(database.adminUrl);
    const practices = await db.insert(organisations).values([{ clerkOrganisationId: "finance-complete", slug: "finance-complete", name: "Finance completion", practiceType: "building_surveying", region: "Bristol", status: "active" }, { clerkOrganisationId: "finance-other", slug: "finance-other", name: "Other practice", practiceType: "building_surveying", region: "Bristol", status: "active" }]).returning();
    organisationId = practices[0].id; otherId = practices[1].id;
    const [owner] = await db.insert(users).values({ clerkUserId: "finance-owner", email: "finance-owner@example.test" }).returning();
    await db.insert(organisationMemberships).values({ organisationId, userId: owner.id, role: "owner", active: true });
    Object.assign(state.context, { organisationId, internalUserId: owner.id });
    const [invoice] = await db.insert(invoices).values({ organisationId, number: "MANUAL-TEST", status: "open", subtotalMinor: 1000, vatMinor: 0, totalMinor: 1000, issuedAt: new Date() }).returning();
    invoiceId = invoice.id;
  }, 120000);
  afterAll(async () => { vi.unstubAllEnvs(); await database?.drop(); await stopRelay(); });
  it("verifies a receipt exactly once and records evidence without a platform payout liability", async () => {
    const body = verification();
    const responses = await Promise.all([receipt(request("/api/v1/finance/invoices/id/manual-payments", body), route(invoiceId)), receipt(request("/api/v1/finance/invoices/id/manual-payments", body), route(invoiceId))]);
    expect(responses.map(r => r.status)).toEqual([200,200]);
    const reviews = await Promise.all(responses.map(r => r.json()));
    expect(reviews[0].data.id).toBe(reviews[1].data.id);
    expect(await db.select().from(manualPaymentReviews)).toHaveLength(1);
    const [invoice] = await db.select().from(invoices).where(eq(invoices.id, invoiceId));
    expect(invoice).toMatchObject({ status: "part_paid", totalMinor: 1000 });
    expect(await db.select().from(settlementLedger)).toHaveLength(0);
    expect((await receipt(request("/api/v1/finance/invoices/id/manual-payments", { ...body, amountMinor: 500 }), route(invoiceId))).status).toBe(409);
    expect((await receipt(request("/api/v1/finance/invoices/id/manual-payments", { ...body, requestId: crypto.randomUUID(), expectedOutstandingMinor: 400 }), route(invoiceId))).status).toBe(409);
    const detail = await (await invoiceDetail(request("/api/v1/finance/invoices/id"), route(invoiceId))).json();
    expect(detail.data).toMatchObject({ receivedMinor: 600, outstandingMinor: 400 });
    expect(detail.data.reviews).toHaveLength(1);
  });
  it("rejects stale amounts, overpayment, unconfirmed evidence, foreign invoices and restricted roles", async () => {
    const body = verification(500);
    expect((await receipt(request("/api/v1/finance/invoices/id/manual-payments", body), route(invoiceId))).status).toBe(409);
    expect((await receipt(request("/api/v1/finance/invoices/id/manual-payments", { ...body, expectedOutstandingMinor: 400 }), route(invoiceId))).status).toBe(409);
    expect((await receipt(request("/api/v1/finance/invoices/id/manual-payments", { ...body, confirmed: false }), route(invoiceId))).status).toBe(400);
    state.context.organisationId = otherId;
    expect((await receipt(request("/api/v1/finance/invoices/id/manual-payments", body), route(invoiceId))).status).toBe(404);
    state.context.organisationId = organisationId; state.context.role = "surveyor";
    expect((await receipt(request("/api/v1/finance/invoices/id/manual-payments", body), route(invoiceId))).status).toBe(403);
    state.context.role = "owner"; state.writable = false;
    expect((await receipt(request("/api/v1/finance/invoices/id/manual-payments", body), route(invoiceId))).status).toBe(403);
    state.writable = true;
  });
  it("verifies a completed external refund once and prevents refunds of Stripe payments", async () => {
    const [payment] = await db.select().from(clientPayments).where(eq(clientPayments.invoiceId, invoiceId));
    const body = verification(200);
    const responses = await Promise.all([refund(request("/api/v1/finance/payments/id/manual-refund", body), route(payment.id)), refund(request("/api/v1/finance/payments/id/manual-refund", body), route(payment.id))]);
    expect(responses.every(r => r.ok)).toBe(true);
    const [updated] = await db.select().from(clientPayments).where(eq(clientPayments.id, payment.id));
    expect(updated).toMatchObject({ refundedMinor: 200, status: "partially_refunded" });
    expect((await refund(request("/api/v1/finance/payments/id/manual-refund", verification(500)), route(payment.id))).status).toBe(409);
    const [stripe] = await db.insert(clientPayments).values({ organisationId, invoiceId, purpose: "balance", amountMinor: 100, status: "succeeded", stripePaymentIntentId: "pi_not_manual", succeededAt: new Date() }).returning();
    expect((await refund(request("/api/v1/finance/payments/id/manual-refund", verification(100)), route(stripe.id))).status).toBe(409);
    const insight = await practiceInsights(organisationId, new Date(Date.now()-86400000), new Date(Date.now()+86400000));
    expect(insight.money.find(row => row.currency === "GBP")?.refundedMinor).toBe(200);
    expect(await db.select().from(auditEvents).where(and(eq(auditEvents.resourceId, payment.id), eq(auditEvents.action, "manual_payment.refund_verified")))).toHaveLength(1);
  });
  it("makes verification evidence immutable and enforces database tenant ownership", async () => {
    const [review] = await db.select().from(manualPaymentReviews);
    await expect(db.update(manualPaymentReviews).set({ evidence: "changed" }).where(eq(manualPaymentReviews.id, review.id))).rejects.toThrow();
    await expect(db.delete(manualPaymentReviews).where(eq(manualPaymentReviews.id, review.id))).rejects.toThrow();
    const app = database.connect(database.appUrl);
    await expect(withTenant(app, organisationId, tx => tx.insert(manualPaymentReviews).values({ ...review, id: crypto.randomUUID(), requestId: crypto.randomUUID(), reference: "FALSE-VERIFICATION", amountMinor: 1 }))).rejects.toThrow();
    expect(await withTenant(app, otherId, tx => tx.select().from(manualPaymentReviews))).toHaveLength(0);
    await expect(withTenant(app, otherId, tx => tx.insert(manualPaymentReviews).values({ ...review, id: crypto.randomUUID(), organisationId: otherId, requestId: crypto.randomUUID() }))).rejects.toThrow();
  });
  it("streams complete financial datasets with tenant isolation, date filtering and spreadsheet escaping", async () => {
    await db.insert(invoices).values(Array.from({ length: 205 }, (_, index) => ({ organisationId, number: index === 0 ? '=HYPERLINK("untrusted")' : `EXPORT-${index}`, status: "open" as const, subtotalMinor: 10, vatMinor: 0, totalMinor: 10 })));
    await db.insert(invoices).values({ organisationId: otherId, number: "PRIVATE-OTHER-INVOICE", status: "open", subtotalMinor: 10, vatMinor: 0, totalMinor: 10 });
    const response = await financialExport(request("/api/v1/finance/exports?dataset=invoices"));
    expect(response.headers.get("cache-control")).toBe("private, no-store");
    const reader = response.body!.getReader();
    const first = await reader.read();
    expect(new TextDecoder().decode(first.value)).toContain('"number"');
    await db.insert(invoices).values({ organisationId, number: "INSERTED-AFTER-SNAPSHOT", status: "open", subtotalMinor: 10, vatMinor: 0, totalMinor: 10 });
    const chunks = [first.value!];
    while (true) { const next = await reader.read(); if (next.done) break; chunks.push(next.value); }
    const csv = chunks.map(chunk => new TextDecoder().decode(chunk)).join("");
    expect(csv.trim().split("\r\n")).toHaveLength(207);
    expect(csv).not.toContain("PRIVATE-OTHER-INVOICE");
    expect(csv).not.toContain("INSERTED-AFTER-SNAPSHOT");
    expect(csv).toContain("'=HYPERLINK");
    expect(csv.match(/EXPORT-/g)).toHaveLength(204);
    await db.insert(clientPayments).values(Array.from({ length: 205 }, () => ({ organisationId, invoiceId, purpose: "export-fixture", amountMinor: 1, status: "pending" as const })));
    const entries = await db.insert(settlementLedger).values(Array.from({ length: 205 }, () => ({ organisationId, entryType: "firm_liability", amountMinor: 1 }))).returning();
    const [batch] = await db.insert(settlementBatches).values({ organisationId, reference: "SETTLED-EXPORT", totalMinor: 1, settledAt: new Date() }).returning();
    await db.insert(settlementBatchItems).values({ organisationId, batchId: batch.id, ledgerEntryId: entries[0].id });
    const paymentCsv = await (await financialExport(request("/api/v1/finance/exports?dataset=payments"))).text();
    expect(paymentCsv.trim().split("\r\n")).toHaveLength(208);
    const ledgerCsv = await (await financialExport(request("/api/v1/finance/exports?dataset=reconciliation"))).text();
    expect(ledgerCsv.trim().split("\r\n")).toHaveLength(206);
    expect(ledgerCsv).toContain("SETTLED-EXPORT");
    const unsettled = await (await financialExport(request("/api/v1/finance/exports?dataset=reconciliation&unsettled=true"))).text();
    expect(unsettled.trim().split("\r\n")).toHaveLength(205);
    expect(unsettled).not.toContain("SETTLED-EXPORT");
    for (const dataset of ["payments", "reconciliation"]) expect((await (await financialExport(request(`/api/v1/finance/exports?dataset=${dataset}`))).text())).toContain('"currency"');
    const cancelled = await financialExport(request("/api/v1/finance/exports?dataset=invoices"));
    const cancelledReader = cancelled.body!.getReader();
    await cancelledReader.read();
    await cancelledReader.cancel();
    expect((await cancelledReader.read()).done).toBe(true);
    const filtered = await financialExport(request("/api/v1/finance/exports?dataset=invoices&from=2099-01-01T00%3A00%3A00Z"));
    expect((await filtered.text()).trim().split("\r\n")).toHaveLength(1);
    expect((await financialExport(request("/api/v1/finance/exports?dataset=unknown"))).status).toBe(400);
    state.context.role = "surveyor";
    expect((await financialExport(request("/api/v1/finance/exports?dataset=invoices"))).status).toBe(403);
    state.context.role = "owner";
  }, 30000);
});
