import { afterAll, beforeAll, describe, expect, it, vi } from "vitest";
vi.mock("server-only", () => ({}));
import { createHash } from "node:crypto";
import { createMemoryStorage } from "../src/lib/storage";
import { processSurveyFileOriginal } from "../src/lib/survey-file-removal-storage";
import { verifiedSurveyFileOriginalRemoval } from "../src/lib/survey-file-original-removal-status";
import { confirmDocumentWorks, downloadPreinspectionDocument, listPreinspectionDocuments } from "../src/lib/preinspection-documents";
import { and, eq, sql } from "drizzle-orm";
import { createTestDatabase, integrationEnabled, stopRelay, type TestDatabase } from "@surveynt/db/testing";
import { clientPayments, customerQuotes, invoices, jobs, jobStageEvents, organisations, organisationDocuments, organisationOperationalSettings, organisationMemberships, reportDeliveries, users, withTenant, createDatabase } from "@surveynt/db";
import { readSurveyFileRetention } from "../src/lib/survey-file-retention-register";
import { jobRetentionHolds } from "@surveynt/db";
import { evidenceLinks, mediaAssets, reportVersions, surveyElements, surveys } from "@surveynt/db";
import { preinspectionDocuments } from "@surveynt/db";
import { auditEvents } from "@surveynt/db";
import { prepareReviewedSurveyFileRemoval } from "../src/lib/survey-file-removal-prepare";
import { cancelReviewedSurveyFileRemoval, requestReviewedSurveyFileRemoval } from "../src/lib/survey-file-removal-request";
import { revalidateQueuedSurveyFileRemoval } from "../src/lib/survey-file-removal-revalidate";
import { claimQueuedSurveyFileRemoval } from "../src/lib/survey-file-removal-claim";
import { recordSurveyFileOriginalDispatch } from "../src/lib/survey-file-removal-object-dispatch";
import { disposeMediaAnalysis } from "../src/lib/survey-file-media-analysis-disposition";
import { disposeQuestionnaireAnalysis } from "../src/lib/survey-file-questionnaire-disposition";
import { surveyFileRemovalCanCancel } from "../src/lib/survey-file-removal-cancellation";
import { recordSurveyFilePreflightFailure } from "../src/lib/survey-file-removal-preflight-failure";
import { recordSurveyFileOriginalOutcome } from "../src/lib/survey-file-removal-object-outcome";
import { claimSurveyFileRemovalRecovery, observeInterruptedSurveyFileOriginal } from "../src/lib/survey-file-removal-recovery";
import { surveyFileRemovals } from "@surveynt/db";
import { assistantTasks, fieldProposals, mediaAnalyses } from "@surveynt/db";
import { readSurveyFileProvenance } from "../src/lib/survey-file-provenance-register";
import { readSurveyFileMedia } from "../src/lib/survey-file-media-register";
import { isFieldRequired, listFields, residentialTemplateV1, type FieldDefinition, type FieldValue, type SyncOperation } from "@surveynt/assistant";
import { syncSourceRegistry } from "@surveynt/property-data/importers";
import { seedStakeholderDemo } from "../src/lib/stakeholder-demo";
import { acceptQuoteAddress, createPublicQuote, readPublicQuote } from "../src/lib/firm-operations";
import { createSurvey, applySyncOperations, type SurveyContext } from "../src/lib/surveys";
import { composeSurveyReport, approveReportVersion } from "../src/lib/reports";
import { enforceStageGate } from "../src/lib/completion";
import { POST as checkout } from "../src/app/api/v1/public/quotes/[id]/checkout/route";
import { GET as slots, POST as book } from "../src/app/api/v1/public/quotes/[id]/appointments/route";
import { GET as reports, POST as confirmReportReceipt } from "../src/app/api/v1/public/quotes/[id]/reports/route";

function sample(field: FieldDefinition): FieldValue {
  switch(field.type){
    case "enum": return {state:"provided",value:["listed_status","conservation_area"].includes(field.key)?"no_record_found":field.options![0].value};
    case "integer": case "decimal": return {state:"provided",value:field.min??1};
    case "boolean": return {state:"provided",value:false};
    case "date": return {state:"provided",value:new Date().toISOString().slice(0,10)};
    default: return {state:"provided",value:`Fictional demonstration: ${field.key.replaceAll("_"," ")}.`};
  }
}
function inspectionFixture(): SyncOperation[] {
  const operations:SyncOperation[]=[];let count=0;const op=()=>`op_demo_journey_${String(++count).padStart(6,"0")}`;
  for(const section of residentialTemplateV1.sections)for(const element of section.elements)if(element.inspectable)operations.push({type:"set_element",operationId:op(),element:{sectionKey:section.key,elementKey:element.key,locationLabel:""},inspectionStatus:section.key==="outside"&&element.key==="roof_coverings"?"inspected":"not_applicable",limitationReason:null,baseVersion:null});
  for(const resolved of listFields(residentialTemplateV1))if(!resolved.element.inspectable&&isFieldRequired(resolved.field,{serviceLevel:"level_1"}))operations.push({type:"set_field",operationId:op(),fieldPath:resolved.path,value:sample(resolved.field),baseValueId:null});
  operations.push({type:"set_field",operationId:op(),fieldPath:"outside.roof_coverings.condition_rating",value:{state:"provided",value:"2"},baseValueId:null},{type:"set_field",operationId:op(),fieldPath:"outside.roof_coverings.construction",value:{state:"provided",value:"Fictional demo: pitched natural-slate roof."},baseValueId:null});
  return operations;
}

describe.skipIf(!integrationEnabled)("stakeholder staff and customer journey",()=>{
  let database:TestDatabase, context:SurveyContext;
  beforeAll(async()=>{
    database=await createTestDatabase();Object.assign(process.env,{DATABASE_ADMIN_URL:database.adminUrl,DATABASE_APP_URL:database.appUrl});
    const db=database.connect(database.adminUrl);await syncSourceRegistry(db);
    const [owner]=await db.insert(users).values({clerkUserId:"user_journey_owner",email:"owner@example.test"}).returning();
    const [org]=await db.insert(organisations).values({clerkOrganisationId:"org_journey_demo",slug:"journey-demo",name:"Journey demonstration",practiceType:"building_surveying",region:"Bristol",status:"active",isDemo:true,demoGeneration:1}).returning();
    // This test practitioner is explicitly granted both permissions; demo owners
    // created by the application retain false defaults.
    await db.insert(organisationMemberships).values({ organisationId: org.id, userId: owner.id, role: "owner", active: true, canRecordSurvey: true, canApproveReports: true });
    context={organisationId:org.id,internalUserId:owner.id,role:"owner",canRecordSurvey:true,canApproveReports:true};await seedStakeholderDemo(org.id,owner.id,db);
  },120000);
  afterAll(async()=>{vi.unstubAllGlobals();await database?.drop();await stopRelay();});
  it("persists quote, decline, exactly-once deposit, booking, explicit report approval, customer issue and balance",async()=>{
    const noExternal=vi.fn(()=>{throw new Error("Demo called an external service");});vi.stubGlobal("fetch",noExternal);
    const created=await createPublicQuote({organisationId:context.organisationId,actorUserId:context.internalUserId!,requestId:crypto.randomUUID(),firstName:"Featured",lastName:"Customer",email:"featured@example.test",answers:{purpose:"survey-only",propertyAge:"post-1990",propertyType:"house"}});
    const id=created.quote.id as string, route={params:Promise.resolve({id})};
    const request=(path:string,body?:unknown,token=created.token)=>new Request(`http://surveynt.test/api/v1/public/quotes/${id}${path}`,{method:body?"POST":"GET",headers:{"content-type":"application/json","x-quote-token":token},...(body?{body:JSON.stringify(body)}:{})});
    await acceptQuoteAddress(id,created.token,{line1:"1 Fictional Demo Street",city:"Bristol",postcode:"BS1 1AA"});
    expect((await checkout(request("/checkout",{scenario:"failure"}),route)).status).toBe(402);
    const deposits=await Promise.all([checkout(request("/checkout",{purpose:"deposit"}),route),checkout(request("/checkout",{purpose:"deposit"}),route)]);
    expect(deposits.every(response=>response.ok)).toBe(true);
    const found=(await readPublicQuote(id,created.token))!;expect(found.view.depositPaid).toBe(true);const jobId=found.row.jobId!;
    const available=await slots(request("/appointments"),route);const choices=(await available.json()).data;expect(choices.length).toBeGreaterThan(0);
    const first=await book(request("/appointments",{startsAt:choices[0].startsAt}),route),second=await book(request("/appointments",{startsAt:choices[0].startsAt}),route);
    expect((await first.json()).data.id).toBe((await second.json()).data.id);
    const capture=await createSurvey(context,jobId,{serviceLevel:"level_1"});if(capture.kind!=="created")throw new Error(capture.kind);
    expect((await applySyncOperations(context,capture.survey.id,inspectionFixture())).every(result=>result.status==="applied")).toBe(true);
    const draft=await composeSurveyReport(context,capture.survey.id);
    expect((await (await reports(request("/reports"),route)).json()).data).toEqual([]);
    await expect(approveReportVersion(context,capture.survey.id,draft.id,{confirm:false})).rejects.toMatchObject({code:"confirmation_required"});
    await approveReportVersion(context,capture.survey.id,draft.id,{confirm:true,note:"Explicit fictional stakeholder review in isolated test database."});
    await withTenant(createDatabase(),context.organisationId,async tx=>{expect(await enforceStageGate(tx,context,{jobId,targetStage:"issued",overrides:[]})).toMatchObject({kind:"passed"});await tx.update(jobs).set({stage:"issued"}).where(eq(jobs.id,jobId));});
    const issued=(await (await reports(request("/reports"),route)).json()).data;expect(issued).toHaveLength(1);expect(issued[0].content).toBeTruthy();expect(issued[0]).not.toHaveProperty("trace");
    const acknowledgements=await Promise.all([1,2].map(()=>confirmReportReceipt(request("/reports",{reportVersionId:issued[0].id,confirmed:true}),route)));
    expect(acknowledgements.every(response=>response.ok)).toBe(true);
    expect((await acknowledgements[0].json()).data.id).toBe((await acknowledgements[1].json()).data.id);
    const deliveryRows=await database.connect(database.adminUrl).select().from(reportDeliveries).where(eq(reportDeliveries.jobId,jobId));
    expect(deliveryRows).toHaveLength(1);expect(deliveryRows[0]).toMatchObject({status:"delivered",deliveryMethod:"customer_acknowledgement",reportVersionId:issued[0].id});
    expect(deliveryRows[0].deliveredAt).toBeInstanceOf(Date);
    expect((await confirmReportReceipt(request("/reports",{reportVersionId:issued[0].id,confirmed:true},"wrong-token"),route)).status).toBe(404);
    expect((await confirmReportReceipt(request("/reports",{reportVersionId:crypto.randomUUID(),confirmed:true}),route)).status).toBe(409);
    expect((await reports(request("/reports",undefined,"wrong-token"),route)).status).toBe(404);
    expect((await checkout(request("/checkout",{purpose:"balance"}),route)).ok).toBe(true);
    expect((await readPublicQuote(id,created.token))?.view.balanceMinor).toBe(0);
    const db=database.connect(database.adminUrl);const payments=await db.select().from(clientPayments).where(eq(clientPayments.quoteId,id));expect(payments).toHaveLength(2);expect(payments.every(payment=>payment.status==="succeeded")).toBe(true);
    const bills=await db.select().from(invoices).where(eq(invoices.quoteId,id));expect(bills).toHaveLength(2);expect(bills.reduce((sum,bill)=>sum+bill.totalMinor,0)).toBe(found.row.totalMinor);expect(bills.reduce((sum,bill)=>sum+bill.vatMinor,0)).toBe(found.row.vatMinor);
    await db.update(jobs).set({stage:"archived"}).where(eq(jobs.id,jobId));
    await db.delete(jobStageEvents).where(eq(jobStageEvents.jobId,jobId));
    await db.insert(jobStageEvents).values({organisationId:context.organisationId,jobId,fromStage:"paid",toStage:"archived",createdAt:new Date("2000-02-01T00:00:00Z")});
    await db.update(organisationOperationalSettings).set({surveyFileRetentionPolicy:{version:"survey-file-1-year-v2",revision:1,enabled:true,approvedAt:new Date().toISOString(),approvedByUserId:context.internalUserId!,reason:"Disposable test practice retention approval"}}).where(eq(organisationOperationalSettings.organisationId,context.organisationId));
    const register=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileRetention(tx,context.organisationId,jobId));
    expect(register?.assessment.reason).toBe("retention_active");
    await db.update(reportDeliveries).set({deliveredAt:new Date("2000-03-01T00:00:00Z")}).where(eq(reportDeliveries.jobId,jobId));
    const expired=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileRetention(tx,context.organisationId,jobId));
    expect(expired?.assessment.reason).toBe("manager_review_required");
    expect(expired?.assessment.retentionUntil?.toISOString()).toBe("2001-03-01T00:00:00.000Z");
    expect(expired?.assessment.reviewVersion).not.toBe(register?.assessment.reviewVersion);
    expect(expired?.removalAuthorised).toBe(false);
    const [retentionJob]=await db.select().from(jobs).where(eq(jobs.id,jobId));
    const originalQuestionnaireId=crypto.randomUUID(),replacementQuestionnaireId=crypto.randomUUID();
    const [questionnaireOriginal]=await db.insert(preinspectionDocuments).values({id:originalQuestionnaireId,organisationId:context.organisationId,jobId,propertyId:retentionJob.propertyId,requestId:crypto.randomUUID(),name:"Original certificate.pdf",contentType:"application/pdf",sizeBytes:4,checksum:"c".repeat(64),storageKey:`organisations/${context.organisationId}/preinspection/${jobId}/${originalQuestionnaireId}/original`,source:"customer",analysis:{privateText:"Fictional extracted text"}}).returning();
    await db.insert(preinspectionDocuments).values({id:replacementQuestionnaireId,organisationId:context.organisationId,jobId,propertyId:retentionJob.propertyId,requestId:crypto.randomUUID(),name:"Replacement certificate.pdf",contentType:"application/pdf",sizeBytes:4,checksum:"d".repeat(64),storageKey:`organisations/${context.organisationId}/preinspection/${jobId}/${replacementQuestionnaireId}/original`,source:"customer",replacesId:questionnaireOriginal.id});
    const questionnaireFile=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileRetention(tx,context.organisationId,jobId));
    expect(questionnaireFile?.questionnaireDocuments).toHaveLength(2);expect(questionnaireFile?.assessment.reviewVersion).not.toBe(expired?.assessment.reviewVersion);
    expect(questionnaireFile?.questionnaireDocuments[0]).not.toHaveProperty("analysis");
    await expect(withTenant(createDatabase(),context.organisationId,tx=>prepareReviewedSurveyFileRemoval(tx,context.organisationId,jobId,questionnaireFile!.assessment.reviewVersion))).rejects.toThrow("manager");
    await db.insert(auditEvents).values({organisationId:context.organisationId,actorUserId:context.internalUserId!,action:"job.retention_file_reviewed",resourceType:"job",resourceId:jobId,metadata:{reviewVersion:questionnaireFile!.assessment.reviewVersion,confirmed:true,noUnresolvedComplaintOrClaim:true}});
    const prepared=await withTenant(createDatabase(),context.organisationId,tx=>prepareReviewedSurveyFileRemoval(tx,context.organisationId,jobId,questionnaireFile!.assessment.reviewVersion));
    expect(prepared.manifest.objects).toHaveLength(2);expect(prepared.manifest.objects.every(object=>object.kind==="questionnaire")).toBe(true);
    await db.update(organisationMemberships).set({active:false}).where(eq(organisationMemberships.userId,context.internalUserId!));
    await expect(withTenant(createDatabase(),context.organisationId,tx=>prepareReviewedSurveyFileRemoval(tx,context.organisationId,jobId,questionnaireFile!.assessment.reviewVersion))).rejects.toThrow("manager");
    await db.update(organisationMemberships).set({active:true}).where(eq(organisationMemberships.userId,context.internalUserId!));
    await expect(withTenant(createDatabase(),context.organisationId,tx=>prepareReviewedSurveyFileRemoval(tx,context.organisationId,jobId,expired!.assessment.reviewVersion))).rejects.toThrow("changed");
    const removalRequest={requestId:crypto.randomUUID(),reviewVersion:questionnaireFile!.assessment.reviewVersion,reason:"Manager confirmed expiry and reviewed every retained original.",confirmed:true as const};
    const requested=await Promise.all([1,2].map(()=>withTenant(createDatabase(),context.organisationId,tx=>requestReviewedSurveyFileRemoval(tx,context.organisationId,jobId,context.internalUserId!,removalRequest))));
    expect(requested[0].id).toBe(requested[1].id);expect(requested.map(result=>result.duplicate).sort()).toEqual([false,true]);expect(requested.every(result=>result.storageRemoved===false)).toBe(true);
    await expect(withTenant(createDatabase(),context.organisationId,async tx=>{
      const claim=await claimQueuedSurveyFileRemoval(tx,context.organisationId,jobId,requested[0].id);
      const first=claim.manifest.objects[0];const key=`${first.kind}:${first.id}`;
      await expect(recordSurveyFilePreflightFailure(tx,context.organisationId,claim.id,crypto.randomUUID(),key,"unexpected_absence")).rejects.toThrow("replaced");
      await recordSurveyFilePreflightFailure(tx,context.organisationId,claim.id,claim.leaseToken,key,"unexpected_absence");
      const [failed]=await tx.select().from(surveyFileRemovals).where(eq(surveyFileRemovals.id,claim.id));
      expect(failed.status).toBe("verification_required");expect(failed.lockedUntil).toBeNull();expect(failed.progress).toEqual({});
      const [eligibility]=await tx.select({canCancel:surveyFileRemovalCanCancel}).from(surveyFileRemovals).where(eq(surveyFileRemovals.id,claim.id));expect(eligibility.canCancel).toBe(true);
      await expect(claimSurveyFileRemovalRecovery(tx,context.organisationId,claim.id)).rejects.toThrow("No recorded original dispatch");
      expect(await cancelReviewedSurveyFileRemoval(tx,context.organisationId,jobId,context.internalUserId!,{id:claim.id,manifestVersion:claim.manifest.manifestVersion,reason:"Cancel failed preflight to investigate missing original.",confirmed:true})).toMatchObject({status:"cancelled",duplicate:false});
      expect(await cancelReviewedSurveyFileRemoval(tx,context.organisationId,jobId,context.internalUserId!,{id:claim.id,manifestVersion:claim.manifest.manifestVersion,reason:"Cancel failed preflight to investigate missing original.",confirmed:true})).toMatchObject({status:"cancelled",duplicate:true});
      throw new Error("rollback preflight failure fixture");
    })).rejects.toThrow("rollback preflight failure fixture");
    const removalRows=await db.select().from(surveyFileRemovals).where(eq(surveyFileRemovals.jobId,jobId));expect(removalRows).toHaveLength(1);expect(removalRows[0].manifestVersion).toBe(prepared.manifest.manifestVersion);
    expect((await withTenant(createDatabase(),context.organisationId,tx=>revalidateQueuedSurveyFileRemoval(tx,context.organisationId,jobId,requested[0].id))).manifest.manifestVersion).toBe(prepared.manifest.manifestVersion);
    await expect(withTenant(createDatabase(),context.organisationId,async tx=>{
      const claim=await claimQueuedSurveyFileRemoval(tx,context.organisationId,jobId,requested[0].id);
      expect(claim.attempts).toBe(1);expect(claim.manifest.manifestVersion).toBe(prepared.manifest.manifestVersion);
      const [stored]=await tx.select().from(surveyFileRemovals).where(eq(surveyFileRemovals.id,claim.id));
      expect(stored.status).toBe("dispatched");expect(stored.leaseToken).toBe(claim.leaseToken);
      const first=claim.manifest.objects[0];const objectKey=`${first.kind}:${first.id}`;
      await tx.update(organisations).set({status:"suspended"}).where(eq(organisations.id,context.organisationId));
      await expect(recordSurveyFileOriginalDispatch(tx,context.organisationId,jobId,claim.id,claim.leaseToken,objectKey)).rejects.toThrow("active practice");
      await tx.update(organisations).set({status:"active"}).where(eq(organisations.id,context.organisationId));
      await tx.update(organisationMemberships).set({active:false}).where(eq(organisationMemberships.userId,context.internalUserId!));
      await expect(recordSurveyFileOriginalDispatch(tx,context.organisationId,jobId,claim.id,claim.leaseToken,objectKey)).rejects.toThrow("permission");
      await tx.update(organisationMemberships).set({active:true}).where(eq(organisationMemberships.userId,context.internalUserId!));
      expect(await recordSurveyFileOriginalDispatch(tx,context.organisationId,jobId,claim.id,claim.leaseToken,objectKey)).toMatchObject({dispatch:true,verificationRequired:false});
      expect(await recordSurveyFileOriginalDispatch(tx,context.organisationId,jobId,claim.id,claim.leaseToken,objectKey)).toEqual({dispatch:false,verificationRequired:true});
      await expect(recordSurveyFileOriginalOutcome(tx,context.organisationId,claim.id,crypto.randomUUID(),objectKey,{state:"removed"})).rejects.toThrow("replaced");
      expect(await recordSurveyFileOriginalOutcome(tx,context.organisationId,claim.id,claim.leaseToken,objectKey,{state:"removed"})).toEqual({duplicate:false,status:"dispatched"});
      expect(await recordSurveyFileOriginalOutcome(tx,context.organisationId,claim.id,claim.leaseToken,objectKey,{state:"removed"})).toEqual({duplicate:true,status:"dispatched"});
      await expect(claimSurveyFileRemovalRecovery(tx,context.organisationId,claim.id)).rejects.toThrow("still active");
      const second=claim.manifest.objects[1];const secondKey=`${second.kind}:${second.id}`;
      await recordSurveyFileOriginalDispatch(tx,context.organisationId,jobId,claim.id,claim.leaseToken,secondKey);
      await recordSurveyFileOriginalOutcome(tx,context.organisationId,claim.id,claim.leaseToken,secondKey,{state:"verification_required",reason:"uncertain_delete"});
      await expect(cancelReviewedSurveyFileRemoval(tx,context.organisationId,jobId,context.internalUserId!,{id:claim.id,manifestVersion:claim.manifest.manifestVersion,reason:"Attempt cancellation after an uncertain deletion.",confirmed:true})).rejects.toThrow("cannot be cancelled");
      const recovery=await claimSurveyFileRemovalRecovery(tx,context.organisationId,claim.id);
      expect(recovery.leaseToken).not.toBe(claim.leaseToken);expect(recovery.objects.map(object=>object.id)).toEqual([second.id]);
      throw new Error("Rollback dispatch claim fixture");
    }).catch((error: unknown) => {
      const cause = (error as { cause?: { message?: string } }).cause;
      if (cause?.message) throw new Error(`Removal workflow database guard: ${cause.message}`);
      throw error;
    })).rejects.toThrow("Rollback dispatch claim fixture");
    await expect(db.update(surveyFileRemovals).set({manifest:{objects:[]}}).where(eq(surveyFileRemovals.id,requested[0].id))).rejects.toThrow();
    await expect(db.delete(surveyFileRemovals).where(eq(surveyFileRemovals.id,requested[0].id))).rejects.toThrow();
    await expect(db.update(surveyFileRemovals).set({progress:{unknown:{state:"removed"}}}).where(eq(surveyFileRemovals.id,requested[0].id))).rejects.toThrow();
    const firstOriginal=prepared.manifest.objects[0];
    await expect(db.transaction(async tx=>{
      await tx.update(surveyFileRemovals).set({status:"dispatched",leaseToken:crypto.randomUUID(),lockedUntil:new Date(Date.now()+300000),attempts:1}).where(eq(surveyFileRemovals.id,requested[0].id));
      await tx.delete(surveyElements).where(eq(surveyElements.surveyId,capture.survey.id));
    })).rejects.toMatchObject({cause:{message:"Survey evidence under original removal cannot be added, changed, moved or deleted"}});
    await expect(db.transaction(async tx=>{
      await tx.update(surveyFileRemovals).set({status:"dispatched",leaseToken:crypto.randomUUID(),lockedUntil:new Date(Date.now()+300000),attempts:1}).where(eq(surveyFileRemovals.id,requested[0].id));
      await tx.update(surveys).set({version:999}).where(eq(surveys.id,capture.survey.id));
    })).rejects.toThrow();
    await expect(db.transaction(async tx=>{
      await tx.update(surveyFileRemovals).set({status:"dispatched",leaseToken:crypto.randomUUID(),lockedUntil:new Date(Date.now()+300000),attempts:1}).where(eq(surveyFileRemovals.id,requested[0].id));
      await tx.delete(preinspectionDocuments).where(eq(preinspectionDocuments.jobId,jobId));
    })).rejects.toThrow();
    await expect(db.transaction(async tx=>{
      await tx.update(surveyFileRemovals).set({status:"dispatched",leaseToken:crypto.randomUUID(),lockedUntil:new Date(Date.now()+300000),attempts:1}).where(eq(surveyFileRemovals.id,requested[0].id));
      await tx.update(jobs).set({stage:"instructed"}).where(eq(jobs.id,jobId));
    })).rejects.toThrow();
    await expect(db.update(surveyFileRemovals).set({status:"verification_required",progress:{[`${firstOriginal.kind}:${firstOriginal.id}`]:{state:"removed",attemptId:crypto.randomUUID(),removedAt:new Date().toISOString()}}}).where(eq(surveyFileRemovals.id,requested[0].id))).rejects.toThrow();
    await expect(db.transaction(async tx=>{
      await tx.update(surveyFileRemovals).set({status:"dispatched",leaseToken:crypto.randomUUID(),lockedUntil:new Date(Date.now()+300000),attempts:1}).where(eq(surveyFileRemovals.id,requested[0].id));
      await tx.update(surveyFileRemovals).set({attempts:0}).where(eq(surveyFileRemovals.id,requested[0].id));
    })).rejects.toThrow();
    for(const invalidEvidence of [{attemptId:"invalid",removedAt:new Date().toISOString()},{attemptId:crypto.randomUUID(),removedAt:"infinity"},{attemptId:crypto.randomUUID(),removedAt:"2999-01-01T00:00:00Z"}]) {
      await expect(db.transaction(async tx=>{
        await tx.update(surveyFileRemovals).set({status:"dispatched",leaseToken:crypto.randomUUID(),lockedUntil:new Date(Date.now()+300000),attempts:1,progress:{[`${firstOriginal.kind}:${firstOriginal.id}`]:{state:"removed",...invalidEvidence}}}).where(eq(surveyFileRemovals.id,requested[0].id));
      })).rejects.toThrow();
    }
    await expect(db.transaction(async tx=>{
      await tx.update(surveyFileRemovals).set({status:"dispatched",leaseToken:crypto.randomUUID(),lockedUntil:new Date(Date.now()+300000),attempts:1,progress:{[`${firstOriginal.kind}:${firstOriginal.id}`]:{state:"removed",attemptId:crypto.randomUUID(),removedAt:new Date().toISOString()}}}).where(eq(surveyFileRemovals.id,requested[0].id));
      await tx.update(surveyFileRemovals).set({progress:{}}).where(eq(surveyFileRemovals.id,requested[0].id));
    })).rejects.toThrow();
    await expect(db.update(surveyFileRemovals).set({status:"completed",completedAt:new Date()}).where(eq(surveyFileRemovals.id,requested[0].id))).rejects.toThrow();
    await expect(db.transaction(async tx=>{
      await tx.update(surveyFileRemovals).set({status:"dispatched",leaseToken:crypto.randomUUID(),lockedUntil:new Date(Date.now()+300000),attempts:1}).where(eq(surveyFileRemovals.id,requested[0].id));
      await tx.update(surveyFileRemovals).set({status:"completed",completedAt:new Date()}).where(eq(surveyFileRemovals.id,requested[0].id));
    })).rejects.toThrow();
    await expect(withTenant(createDatabase(),context.organisationId,tx=>requestReviewedSurveyFileRemoval(tx,context.organisationId,jobId,context.internalUserId!,{...removalRequest,reason:"Changed removal decision with reused identifier."}))).rejects.toThrow("different decision");
    await expect(withTenant(createDatabase(),context.organisationId,tx=>requestReviewedSurveyFileRemoval(tx,context.organisationId,jobId,context.internalUserId!,{...removalRequest,requestId:crypto.randomUUID()}))).rejects.toThrow("already exists");
    await expect(withTenant(createDatabase(),context.organisationId,async tx=>{
      const decision={id:requested[0].id,manifestVersion:prepared.manifest.manifestVersion,reason:"Manager stopped removal pending further file review.",confirmed:true as const};
      expect(await cancelReviewedSurveyFileRemoval(tx,context.organisationId,jobId,context.internalUserId!,decision)).toMatchObject({status:"cancelled",duplicate:false});
      expect(await cancelReviewedSurveyFileRemoval(tx,context.organisationId,jobId,context.internalUserId!,decision)).toMatchObject({status:"cancelled",duplicate:true});
      const replacement=await requestReviewedSurveyFileRemoval(tx,context.organisationId,jobId,context.internalUserId!,{...removalRequest,requestId:crypto.randomUUID()});
      expect(replacement.id).not.toBe(requested[0].id);
      throw new Error("Rollback cancellation fixture");
    })).rejects.toThrow("Rollback cancellation fixture");
    const [jobHold]=await db.insert(jobRetentionHolds).values({organisationId:context.organisationId,jobId,kind:"complaint",reason:"Unresolved customer complaint requires file retention.",reviewedByUserId:context.internalUserId!}).returning();
    const complaint=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileRetention(tx,context.organisationId,jobId));
    expect(complaint?.assessment.reason).toBe("protected");expect(complaint?.assessment.reviewVersion).not.toBe(expired?.assessment.reviewVersion);
    await expect(withTenant(createDatabase(),context.organisationId,tx=>revalidateQueuedSurveyFileRemoval(tx,context.organisationId,jobId,requested[0].id))).rejects.toThrow("changed");
    await db.update(jobRetentionHolds).set({kind:null,revision:2,reason:"Complaint resolved and manager authorised clearance."}).where(eq(jobRetentionHolds.id,jobHold.id));
    const clearedFile=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileRetention(tx,context.organisationId,jobId));
    expect(clearedFile?.assessment.reason).toBe("manager_review_required");expect(clearedFile?.assessment.reviewVersion).not.toBe(expired?.assessment.reviewVersion);
    const [jobRow]=await db.select().from(jobs).where(eq(jobs.id,jobId));
    const [original]=await db.insert(mediaAssets).values({organisationId:context.organisationId,propertyId:jobRow.propertyId,surveyId:capture.survey.id,kind:"photo",storageKey:`test/${jobId}/original`,contentType:"image/jpeg",byteSize:4,sha256:"a".repeat(64),clientGeneratedId:"retention-original-1",originalFilename:"inspection.jpg"}).returning();
    await expect(db.transaction(async tx=>{
      await tx.update(surveyFileRemovals).set({status:"dispatched",leaseToken:crypto.randomUUID(),lockedUntil:new Date(Date.now()+300000),attempts:1}).where(eq(surveyFileRemovals.id,requested[0].id));
      await tx.update(mediaAssets).set({surveyId:null}).where(eq(mediaAssets.id,original.id));
    })).rejects.toThrow();

    await db.insert(mediaAssets).values({organisationId:context.organisationId,propertyId:jobRow.propertyId,surveyId:null,kind:"photo",storageKey:`test/${jobId}/thumbnail`,contentType:"image/jpeg",byteSize:2,sha256:"b".repeat(64),clientGeneratedId:"retention-thumbnail-1",derivedFromId:original.id,derivation:"thumbnail"});
    const mediaFile=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileRetention(tx,context.organisationId,jobId));
    expect(mediaFile?.media).toHaveLength(2);expect(mediaFile?.assessment.reviewVersion).not.toBe(clearedFile?.assessment.reviewVersion);
    const [analysis]=await db.insert(mediaAnalyses).values({organisationId:context.organisationId,mediaId:original.id,surveyId:capture.survey.id,analyser:"retention-fixture-v1",status:"completed",result:{privateText:"Fictional extracted certificate text"}}).returning();
    const analysedFile=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileRetention(tx,context.organisationId,jobId));
    expect(analysedFile?.analysisCount).toBe(1);expect(analysedFile?.assessment.reviewVersion).not.toBe(mediaFile?.assessment.reviewVersion);
    const provenance=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileProvenance(tx,context.organisationId,jobId,[original.id],[]));
    expect(provenance.analyses[0]).not.toHaveProperty("result");expect(provenance.analyses[0].resultFingerprint).toMatch(/^[a-f0-9]{64}$/);
    const missingMedia=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileMedia(tx,context.organisationId,jobId,[{media:[crypto.randomUUID()]}]));
    expect(missingMedia.referenceReviewRequired).toBe(true);expect(missingMedia.unresolvedReferences).toHaveLength(1);
    const malformedTrace=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileMedia(tx,context.organisationId,jobId,[{media:"invalid"}]));expect(malformedTrace.referenceReviewRequired).toBe(true);
    const [otherJob]=await db.insert(jobs).values({organisationId:context.organisationId,clientId:jobRow.clientId,propertyId:jobRow.propertyId,reference:"RETENTION-SHARED",serviceName:"Survey"}).returning();
    const otherSurvey=await createSurvey(context,otherJob.id,{serviceLevel:"level_1"});if(otherSurvey.kind!=="created")throw new Error(otherSurvey.kind);
    const [sourceReport]=await db.select().from(reportVersions).where(eq(reportVersions.id,issued[0].id));
    await db.insert(reportVersions).values({...sourceReport,id:crypto.randomUUID(),surveyId:otherSurvey.survey.id,jobId:otherJob.id,versionNumber:1,trace:{...sourceReport.trace,media:[original.id]}});
    const sharedFile=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileRetention(tx,context.organisationId,jobId));
    expect(sharedFile?.externalEvidenceReferenceCount).toBe(1);expect(sharedFile?.assessment.reason).toBe("evidence_review_required");expect(sharedFile?.assessment.eligibleForManagerReview).toBe(false);
    const [otherElement]=await db.insert(surveyElements).values({organisationId:context.organisationId,surveyId:otherSurvey.survey.id,sectionKey:"outside",elementKey:"roof_coverings"}).returning();
    await expect(db.transaction(async tx=>{
      await tx.update(surveyFileRemovals).set({status:"dispatched",leaseToken:crypto.randomUUID(),lockedUntil:new Date(Date.now()+300000),attempts:1}).where(eq(surveyFileRemovals.id,requested[0].id));
      await tx.insert(assistantTasks).values({organisationId:context.organisationId,surveyId:otherSurvey.survey.id,kind:"discrepancy",dedupeKey:"blocked-questionnaire-removal",title:"Blocked shared questionnaire",evidence:{context:{id:questionnaireOriginal.id}}});
    })).rejects.toMatchObject({cause:{message:"Extracted references to originals under removal cannot be added or changed"}});

    await expect(db.transaction(async tx=>{
      await tx.update(surveyFileRemovals).set({status:"dispatched",leaseToken:crypto.randomUUID(),lockedUntil:new Date(Date.now()+300000),attempts:1}).where(eq(surveyFileRemovals.id,requested[0].id));
      await tx.insert(evidenceLinks).values({organisationId:context.organisationId,surveyId:otherSurvey.survey.id,targetType:"element",targetId:otherElement.id,evidenceType:"prior_survey",evidenceId:capture.survey.id,clientGeneratedId:"blocked-removal-prior-reference"});
    })).rejects.toMatchObject({cause:{message:"Evidence referring to a file under removal cannot be added or changed"}});

    await db.insert(evidenceLinks).values({organisationId:context.organisationId,surveyId:otherSurvey.survey.id,targetType:"element",targetId:otherElement.id,evidenceType:"prior_survey",evidenceId:capture.survey.id,clientGeneratedId:"retention-prior-reference"});
    const priorReferenced=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileRetention(tx,context.organisationId,jobId));
    expect(priorReferenced?.externalEvidenceReferenceCount).toBe(2);expect(priorReferenced?.assessment.reviewVersion).not.toBe(sharedFile?.assessment.reviewVersion);
    await db.insert(assistantTasks).values({organisationId:context.organisationId,surveyId:otherSurvey.survey.id,kind:"discrepancy",dedupeKey:"retention-shared-analysis",title:"Shared original reference",evidence:{type:"document_span",mediaId:original.id,analysisId:analysis.id}});
    const adviserReferenced=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileRetention(tx,context.organisationId,jobId));
    expect(adviserReferenced?.externalEvidenceReferenceCount).toBe(3);expect(adviserReferenced?.assessment.eligibleForManagerReview).toBe(false);
    await db.insert(fieldProposals).values({organisationId:context.organisationId,surveyId:otherSurvey.survey.id,fieldPath:"matters.legal.guarantees",proposedValue:{state:"provided",value:"Fictional document reference"},valueType:"text",evidenceRefs:[{type:"document_span",id:questionnaireOriginal.id,context:{mediaId:original.id}}],originClass:"document_extraction",inputVersion:"fixture-v1",generator:"retention-fixture",dedupeKey:"retention-questionnaire-reference"});
    const proposalReferenced=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileRetention(tx,context.organisationId,jobId));
    expect(proposalReferenced?.externalEvidenceReferenceCount).toBe(4);expect(proposalReferenced?.assessment.reviewVersion).not.toBe(adviserReferenced?.assessment.reviewVersion);
    const [foreignOrg]=await db.insert(organisations).values({clerkOrganisationId:"org_retention_foreign",slug:"retention-foreign",name:"Foreign fixture",practiceType:"residential",region:"Bristol",status:"active"}).returning();
    const foreignProvenance=await withTenant(createDatabase(),foreignOrg.id,tx=>readSurveyFileProvenance(tx,foreignOrg.id,jobId,[original.id],[]));
    expect(foreignProvenance.analyses).toEqual([]);expect(foreignProvenance.tasks).toEqual([]);expect(foreignProvenance.proposals).toEqual([]);
    expect(await withTenant(createDatabase(),foreignOrg.id,tx=>tx.select().from(surveyFileRemovals).where(eq(surveyFileRemovals.jobId,jobId)))).toEqual([]);
    await expect(withTenant(createDatabase(),foreignOrg.id,tx=>prepareReviewedSurveyFileRemoval(tx,foreignOrg.id,jobId,questionnaireFile!.assessment.reviewVersion))).rejects.toThrow("unavailable");
    const [heldOriginal]=await db.insert(organisationDocuments).values({organisationId:context.organisationId,jobId,name:"Held original",category:"legal",blobUrl:"https://example.test/held",blobPathname:"held",checksum:"held",contentType:"text/plain",sizeBytes:4,legalHold:false}).returning();
    await expect(db.transaction(async tx=>{
      await tx.update(surveyFileRemovals).set({status:"dispatched",leaseToken:crypto.randomUUID(),lockedUntil:new Date(Date.now()+300000),attempts:1}).where(eq(surveyFileRemovals.id,requested[0].id));
      const [held]=await tx.update(organisationDocuments).set({legalHold:true}).where(eq(organisationDocuments.id,heldOriginal.id)).returning();
      expect(held.legalHold).toBe(true);
      await tx.update(organisationDocuments).set({legalHold:false}).where(eq(organisationDocuments.id,heldOriginal.id));
    })).rejects.toMatchObject({cause:{message:"Documents under survey file removal cannot be changed or detached"}});
    await db.update(organisationDocuments).set({legalHold:true}).where(eq(organisationDocuments.id,heldOriginal.id));
    const held=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileRetention(tx,context.organisationId,jobId));
    expect(held?.assessment.reason).toBe("protected");expect(held?.assessment.reviewVersion).not.toBe(expired?.assessment.reviewVersion);
    expect((await confirmReportReceipt(request("/reports",{reportVersionId:issued[0].id,confirmed:true}),route)).status).toBe(409);
    await db.update(organisations).set({status:"suspended"}).where(eq(organisations.id,context.organisationId));
    expect((await confirmReportReceipt(request("/reports",{reportVersionId:issued[0].id,confirmed:true}),route)).status).toBe(404);
    await db.update(organisations).set({status:"active"}).where(eq(organisations.id,context.organisationId));
    await db.update(customerQuotes).set({tokenRevokedAt:new Date()}).where(eq(customerQuotes.id,id));
    expect((await confirmReportReceipt(request("/reports",{reportVersionId:issued[0].id,confirmed:true}),route)).status).toBe(404);
    expect(await db.select().from(reportDeliveries).where(eq(reportDeliveries.jobId,jobId))).toHaveLength(1);
    let releaseDispatch!:()=>void;let dispatchReady!:()=>void;
    const dispatchGate=new Promise<void>(resolve=>{releaseDispatch=resolve;});
    const ready=new Promise<void>(resolve=>{dispatchReady=resolve;});
    const dispatch=withTenant(createDatabase(),context.organisationId,async tx=>{
      await tx.select({id:jobs.id}).from(jobs).where(eq(jobs.id,jobId)).for("update");
      await tx.update(surveyFileRemovals).set({status:"dispatched",leaseToken:crypto.randomUUID(),lockedUntil:new Date(Date.now()+300000),attempts:1}).where(eq(surveyFileRemovals.id,requested[0].id));
      dispatchReady();await dispatchGate;
    });
    await ready;
    try {
      await expect(withTenant(createDatabase(),context.organisationId,async tx=>{
        await tx.execute(sql`set local lock_timeout='100ms'`);
        await tx.update(surveys).set({version:999}).where(eq(surveys.id,capture.survey.id));
      })).rejects.toMatchObject({cause:{code:"55P03"}});
    } finally {releaseDispatch();await dispatch;}
    await expect(withTenant(createDatabase(),context.organisationId,tx=>tx.update(surveys).set({version:999}).where(eq(surveys.id,capture.survey.id)))).rejects.toMatchObject({cause:{message:"A record bound to a file under original removal cannot be added, changed, moved or deleted"}});
    const [removalJob]=await db.insert(jobs).values({...retentionJob,id:crypto.randomUUID(),reference:"REMOVAL-STORAGE-FIXTURE",stage:"instructed"}).returning();
    const removalSurvey=await createSurvey(context,removalJob.id,{serviceLevel:"level_1"});if(removalSurvey.kind!=="created")throw new Error(removalSurvey.kind);
    await db.update(jobs).set({stage:"archived"}).where(eq(jobs.id,removalJob.id));
    await db.delete(jobStageEvents).where(eq(jobStageEvents.jobId,removalJob.id));
    await db.insert(jobStageEvents).values({organisationId:context.organisationId,jobId:removalJob.id,fromStage:null,toStage:"archived",createdAt:new Date("2000-03-01T00:00:00Z")});
    const [removalReport]=await db.insert(reportVersions).values({...sourceReport,id:crypto.randomUUID(),jobId:removalJob.id,surveyId:removalSurvey.survey.id,versionNumber:1,trace:{media:[]}}).returning();
    const deliveryOriginalId=crypto.randomUUID();const deliveryBytes=new TextEncoder().encode("file");
    const [deliveryOriginal]=await db.insert(organisationDocuments).values({id:deliveryOriginalId,organisationId:context.organisationId,name:"Fictional delivery-only original",category:"report",blobUrl:"https://example.test/fictional",blobPathname:`organisations/${context.organisationId}/documents/${deliveryOriginalId}/original`,checksum:createHash("sha256").update(deliveryBytes).digest("hex"),contentType:"text/plain",sizeBytes:deliveryBytes.length,deletedAt:new Date("2000-03-01T00:00:00Z"),retentionUntil:new Date("2001-03-01T00:00:00Z")}).returning();
    expect(deliveryOriginal.jobId).toBeNull();expect(deliveryOriginal.reportVersionId).toBeNull();
    await db.insert(reportDeliveries).values({organisationId:context.organisationId,jobId:removalJob.id,reportVersionId:removalReport.id,documentId:deliveryOriginal.id,recipient:"storage-fixture@example.test",status:"delivered",deliveredAt:new Date("2000-03-01T00:00:00Z")});
    const originalBytes=new TextEncoder().encode("file");const removalOriginalId=crypto.randomUUID();
    const [removalOriginal]=await db.insert(preinspectionDocuments).values({id:removalOriginalId,organisationId:context.organisationId,jobId:removalJob.id,propertyId:retentionJob.propertyId,requestId:crypto.randomUUID(),name:"Fictional storage original.txt",analysis:{status:"unavailable",reason:"Fictional extracted text retained for disposition testing."},contentType:"text/plain",sizeBytes:originalBytes.length,checksum:createHash("sha256").update(originalBytes).digest("hex"),storageKey:`organisations/${context.organisationId}/preinspection/${removalJob.id}/${removalOriginalId}/original`,source:"customer"}).returning();
    const removalMediaId=crypto.randomUUID();
    const [removalMedia]=await db.insert(mediaAssets).values({id:removalMediaId,organisationId:context.organisationId,propertyId:retentionJob.propertyId,surveyId:removalSurvey.survey.id,kind:"photo",storageKey:`organisations/${context.organisationId}/surveys/${removalSurvey.survey.id}/${removalMediaId}/original`,contentType:"image/jpeg",byteSize:originalBytes.length,sha256:createHash("sha256").update(originalBytes).digest("hex"),clientGeneratedId:crypto.randomUUID()}).returning();
    const [removalAnalysis]=await db.insert(mediaAnalyses).values({organisationId:context.organisationId,mediaId:removalMedia.id,surveyId:removalSurvey.survey.id,analyser:"fictional-retention",status:"completed",result:{fictionalText:"Fictional extracted media text for disposal."}}).returning();
    const removalFile=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileRetention(tx,context.organisationId,removalJob.id));expect(removalFile?.assessment.eligibleForManagerReview).toBe(true);
    await db.insert(auditEvents).values({organisationId:context.organisationId,actorUserId:context.internalUserId!,action:"job.retention_file_reviewed",resourceType:"job",resourceId:removalJob.id,metadata:{reviewVersion:removalFile!.assessment.reviewVersion,confirmed:true,noUnresolvedComplaintOrClaim:true}});
    const removalIntent=await withTenant(createDatabase(),context.organisationId,tx=>requestReviewedSurveyFileRemoval(tx,context.organisationId,removalJob.id,context.internalUserId!,{requestId:crypto.randomUUID(),reviewVersion:removalFile!.assessment.reviewVersion,reason:"Manager reviewed fictional storage integration original.",confirmed:true}));
    const storageClaim=await withTenant(createDatabase(),context.organisationId,tx=>claimQueuedSurveyFileRemoval(tx,context.organisationId,removalJob.id,removalIntent.id));
    const fixtureStorage=createMemoryStorage();await fixtureStorage.put(removalOriginal.storageKey,originalBytes.buffer,"text/plain");
    await fixtureStorage.put(deliveryOriginal.blobPathname,deliveryBytes.buffer,"text/plain");
    await fixtureStorage.put(removalMedia.storageKey,originalBytes.buffer,"image/jpeg");
    expect(await processSurveyFileOriginal(createDatabase(),context.organisationId,removalJob.id,storageClaim,`media:${removalMedia.id}`,fixtureStorage)).toEqual({removed:true,verificationRequired:false});
    expect(await processSurveyFileOriginal(createDatabase(),context.organisationId,removalJob.id,storageClaim,`document:${deliveryOriginal.id}`,fixtureStorage)).toEqual({removed:true,verificationRequired:false});
    await expect(withTenant(createDatabase(),context.organisationId,tx=>disposeQuestionnaireAnalysis(tx,context.organisationId,removalJob.id,context.internalUserId!,removalOriginal.id))).rejects.toThrow("Whole-file removal");
    await expect(withTenant(createDatabase(),context.organisationId,tx=>disposeMediaAnalysis(tx,context.organisationId,removalJob.id,context.internalUserId!,removalAnalysis.id))).rejects.toThrow("Whole-file removal");
    const removeOriginal=fixtureStorage.remove.bind(fixtureStorage);
    const deleteSpy=vi.spyOn(fixtureStorage,"remove").mockImplementation(async key=>{await removeOriginal(key);throw new Error("Fictional lost delete response");});
    expect(await processSurveyFileOriginal(createDatabase(),context.organisationId,removalJob.id,storageClaim,`questionnaire:${removalOriginal.id}`,fixtureStorage)).toEqual({removed:false,verificationRequired:true});
    const recoveryClaims=await Promise.allSettled([1,2].map(()=>withTenant(createDatabase(),context.organisationId,tx=>claimSurveyFileRemovalRecovery(tx,context.organisationId,removalIntent.id))));
    expect(recoveryClaims.filter(result=>result.status==="fulfilled")).toHaveLength(1);
    const deniedRecovery=recoveryClaims.find(result=>result.status==="rejected") as PromiseRejectedResult;
    expect(deniedRecovery.reason.message).toContain("still active");
    const firstRecovery=(recoveryClaims.find(result=>result.status==="fulfilled") as PromiseFulfilledResult<Awaited<ReturnType<typeof claimSurveyFileRemovalRecovery>>>).value;
    const readSpy=vi.spyOn(fixtureStorage,"get").mockRejectedValueOnce(new Error("Fictional unavailable storage"));
    expect(await observeInterruptedSurveyFileOriginal(createDatabase(),context.organisationId,firstRecovery,`questionnaire:${removalOriginal.id}`,fixtureStorage)).toEqual({removed:false,verificationRequired:true});
    const [failedObservation]=await db.select().from(surveyFileRemovals).where(eq(surveyFileRemovals.id,removalIntent.id));
    expect(failedObservation.status).toBe("verification_required");expect(failedObservation.error).toBe("storage_unavailable");expect(failedObservation.lockedUntil).toBeNull();
    readSpy.mockRestore();
    const secondRecovery=await withTenant(createDatabase(),context.organisationId,tx=>claimSurveyFileRemovalRecovery(tx,context.organisationId,removalIntent.id));
    expect(await observeInterruptedSurveyFileOriginal(createDatabase(),context.organisationId,secondRecovery,`questionnaire:${removalOriginal.id}`,fixtureStorage)).toEqual({removed:true,verificationRequired:false});
    expect(deleteSpy).toHaveBeenCalledOnce();
    expect(fixtureStorage.objects.size).toBe(0);
    const [completedRemoval]=await db.select().from(surveyFileRemovals).where(eq(surveyFileRemovals.id,removalIntent.id));expect(completedRemoval.status).toBe("completed");expect(completedRemoval.completedAt).not.toBeNull();
    await expect(withTenant(createDatabase(),context.organisationId,async tx=>{
      await tx.update(organisationDocuments).set({legalHold:true}).where(eq(organisationDocuments.id,deliveryOriginal.id));
      await tx.insert(auditEvents).values({organisationId:context.organisationId,actorUserId:context.internalUserId!,action:"job.questionnaire_analysis_disposed",resourceType:"preinspection_document",resourceId:removalOriginal.id,metadata:{removalId:removalIntent.id,originalChecksum:removalOriginal.checksum}});
      await tx.update(preinspectionDocuments).set({analysis:{retentionRemoved:true}}).where(eq(preinspectionDocuments.id,removalOriginal.id));
    })).rejects.toMatchObject({cause:{message:"A record bound to a file under original removal cannot be added, changed, moved or deleted"}});
    const retryRead=vi.spyOn(fixtureStorage,"get");
    expect(await processSurveyFileOriginal(createDatabase(),context.organisationId,removalJob.id,storageClaim,`questionnaire:${removalOriginal.id}`,fixtureStorage)).toEqual({removed:true,verificationRequired:false});
    expect(retryRead).not.toHaveBeenCalled();expect(deleteSpy).toHaveBeenCalledOnce();retryRead.mockRestore();
    const [dispositionHold]=await db.insert(jobRetentionHolds).values({organisationId:context.organisationId,jobId:removalJob.id,kind:"legal",reason:"Fictional legal hold blocks extracted content disposition.",reviewedByUserId:context.internalUserId!}).returning();
    await expect(withTenant(createDatabase(),context.organisationId,tx=>disposeQuestionnaireAnalysis(tx,context.organisationId,removalJob.id,context.internalUserId!,removalOriginal.id))).rejects.toThrow("protected");
    await expect(withTenant(createDatabase(),context.organisationId,tx=>disposeMediaAnalysis(tx,context.organisationId,removalJob.id,context.internalUserId!,removalAnalysis.id))).rejects.toThrow("protected");
    await db.delete(jobRetentionHolds).where(eq(jobRetentionHolds.id,dispositionHold.id));
    await expect(withTenant(createDatabase(),context.organisationId,tx=>disposeQuestionnaireAnalysis(tx,context.organisationId,removalJob.id,context.internalUserId!,removalOriginal.id,{id:removalIntent.id,manifestVersion:"0".repeat(64),reason:"Reviewed analysis cleanup with a stale removal manifest.",confirmed:true}))).rejects.toThrow("decision changed");
    const cleanupDecision={id:removalIntent.id,manifestVersion:completedRemoval.manifestVersion,reason:"Manager confirmed cleanup of the verified fictional questionnaire analysis.",confirmed:true as const};
    expect(await withTenant(createDatabase(),context.organisationId,tx=>disposeQuestionnaireAnalysis(tx,context.organisationId,removalJob.id,context.internalUserId!,removalOriginal.id,cleanupDecision))).toEqual({disposed:true,duplicate:false});
    expect(await withTenant(createDatabase(),context.organisationId,tx=>disposeQuestionnaireAnalysis(tx,context.organisationId,removalJob.id,context.internalUserId!,removalOriginal.id,{...cleanupDecision,reason:"A network retry must retain the original cleanup reason."}))).toEqual({disposed:true,duplicate:true});
    const [disposedOriginal]=await db.select().from(preinspectionDocuments).where(eq(preinspectionDocuments.id,removalOriginal.id));expect(disposedOriginal.analysis).toEqual({retentionRemoved:true});expect(disposedOriginal.checksum).toBe(removalOriginal.checksum);
    const dispositionEvents=await db.select().from(auditEvents).where(and(eq(auditEvents.organisationId,context.organisationId),eq(auditEvents.resourceId,removalOriginal.id),eq(auditEvents.action,"job.questionnaire_analysis_disposed")));
    expect(dispositionEvents).toHaveLength(1);
    expect(await withTenant(createDatabase(),context.organisationId,tx=>disposeMediaAnalysis(tx,context.organisationId,removalJob.id,context.internalUserId!,removalAnalysis.id,cleanupDecision))).toEqual({disposed:true,duplicate:false});
    expect(await withTenant(createDatabase(),context.organisationId,tx=>disposeMediaAnalysis(tx,context.organisationId,removalJob.id,context.internalUserId!,removalAnalysis.id,cleanupDecision))).toEqual({disposed:true,duplicate:true});
    const [disposedAnalysis]=await db.select().from(mediaAnalyses).where(eq(mediaAnalyses.id,removalAnalysis.id));expect(disposedAnalysis.result).toEqual({retentionRemoved:true});expect(disposedAnalysis.mediaId).toBe(removalMedia.id);
    const mediaDisposalEvents=await db.select().from(auditEvents).where(and(eq(auditEvents.organisationId,context.organisationId),eq(auditEvents.resourceId,removalAnalysis.id),eq(auditEvents.action,"job.media_analysis_disposed")));
    expect(mediaDisposalEvents).toHaveLength(1);expect(mediaDisposalEvents[0].actorUserId).toBe(context.internalUserId);
    expect(mediaDisposalEvents[0].metadata).toEqual({jobId:removalJob.id,removalId:removalIntent.id,mediaId:removalMedia.id,originalChecksum:removalMedia.sha256,analysisFingerprint:createHash("sha256").update(JSON.stringify(removalAnalysis.result)).digest("hex"),policyVersion:"survey-file-1-year-v2",reason:cleanupDecision.reason,confirmed:true});
    expect(JSON.stringify(mediaDisposalEvents[0].metadata)).not.toContain("Fictional extracted media text");
    await expect(withTenant(createDatabase(),foreignOrg.id,tx=>disposeMediaAnalysis(tx,foreignOrg.id,removalJob.id,context.internalUserId!,removalAnalysis.id,cleanupDecision))).rejects.toThrow("permission");
    await expect(withTenant(createDatabase(),context.organisationId,tx=>tx.update(mediaAnalyses).set({result:{restored:true}}).where(eq(mediaAnalyses.id,removalAnalysis.id)))).rejects.toMatchObject({cause:{message:"Media belonging to a file under removal cannot be changed or extended"}});
    const disposedRegister=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileRetention(tx,context.organisationId,removalJob.id));
    expect(disposedRegister!.mediaAnalyses.find(analysis=>analysis.id===removalAnalysis.id)?.analysisDisposed).toBe(true);
    expect(disposedRegister!.questionnaireDocuments.find(document=>document.id===removalOriginal.id)?.analysisDisposed).toBe(true);
    expect(dispositionEvents[0].metadata).toEqual({jobId:removalJob.id,removalId:removalIntent.id,originalChecksum:removalOriginal.checksum,analysisFingerprint:createHash("sha256").update(JSON.stringify(removalOriginal.analysis)).digest("hex"),policyVersion:"survey-file-1-year-v2",reason:cleanupDecision.reason,confirmed:true});
    expect(dispositionEvents[0].actorUserId).toBe(context.internalUserId);
    expect(JSON.stringify(dispositionEvents[0].metadata)).not.toContain("Fictional extracted text");
    await expect(withTenant(createDatabase(),foreignOrg.id,tx=>disposeQuestionnaireAnalysis(tx,foreignOrg.id,removalJob.id,context.internalUserId!,removalOriginal.id))).rejects.toThrow("permission");
    await expect(withTenant(createDatabase(),context.organisationId,tx=>tx.update(preinspectionDocuments).set({analysis:{restored:true}}).where(eq(preinspectionDocuments.id,removalOriginal.id)))).rejects.toMatchObject({cause:{message:"A record bound to a file under original removal cannot be added, changed, moved or deleted"}});
    expect(await withTenant(createDatabase(),context.organisationId,tx=>verifiedSurveyFileOriginalRemoval(tx,context.organisationId,"questionnaire",removalOriginal.id))).not.toBeNull();
    expect(await withTenant(createDatabase(),foreignOrg.id,tx=>verifiedSurveyFileOriginalRemoval(tx,foreignOrg.id,"questionnaire",removalOriginal.id))).toBeNull();
    await expect(withTenant(createDatabase(),context.organisationId,tx=>downloadPreinspectionDocument(tx,{organisationId:context.organisationId,jobId:removalJob.id,propertyId:retentionJob.propertyId,actorUserId:context.internalUserId!,source:"staff_transcribed_client",valuation:false},removalOriginal.id))).rejects.toMatchObject({status:410,code:"original_removed"});
    const removedRegister=await withTenant(createDatabase(),context.organisationId,tx=>listPreinspectionDocuments(tx,{organisationId:context.organisationId,jobId:removalJob.id,propertyId:retentionJob.propertyId,actorUserId:context.internalUserId!,source:"staff_transcribed_client",valuation:false}));
    expect(removedRegister[0].originalRemovedAt).not.toBeNull();expect(removedRegister[0].analysis).toBeNull();
    await expect(withTenant(createDatabase(),context.organisationId,tx=>confirmDocumentWorks(tx,{organisationId:context.organisationId,jobId:removalJob.id,propertyId:retentionJob.propertyId,actorUserId:context.internalUserId!,source:"staff_transcribed_client",valuation:false},context,removalOriginal.id,{worksKind:"extension",checksum:removalOriginal.checksum,reason:"Reviewed original association after retention removal.",confirm:true}))).rejects.toMatchObject({status:410,code:"original_removed"});
    expect(noExternal).not.toHaveBeenCalled();vi.unstubAllGlobals();
  },120000);
  it("allows only one concurrent customer claim for the same surveyor slot",async()=>{
    const created=await Promise.all(["First","Second"].map(firstName=>createPublicQuote({organisationId:context.organisationId,actorUserId:context.internalUserId!,requestId:crypto.randomUUID(),firstName,email:`${firstName.toLowerCase()}@example.test`,answers:{purpose:"survey-only",propertyAge:"post-1990",propertyType:"house"}})));
    const request=(index:number,path:string,body?:unknown)=>new Request(`http://surveynt.test/api/v1/public/quotes/${created[index].quote.id}${path}`,{method:body?"POST":"GET",headers:{"content-type":"application/json","x-quote-token":created[index].token},...(body?{body:JSON.stringify(body)}:{})});
    const routes=created.map(value=>({params:Promise.resolve({id:value.quote.id as string})}));
    await Promise.all(created.map(value=>acceptQuoteAddress(value.quote.id as string,value.token,{line1:"2 Fictional Demo Street",city:"Bristol",postcode:"BS1 1AA"})));
    await Promise.all(created.map((_,index)=>checkout(request(index,"/checkout",{purpose:"deposit"}),routes[index])));
    const available=(await (await slots(request(0,"/appointments"),routes[0])).json()).data;
    expect(available.length).toBeGreaterThan(0);
    const results=await Promise.all(created.map((_,index)=>book(request(index,"/appointments",{startsAt:available[0].startsAt}),routes[index])));
    expect(results.map(value=>value.status).sort()).toEqual([200,409]);
    const successful=results.find(value=>value.ok)!;
    expect((await successful.json()).data.surveyorId).toBe(context.internalUserId);
  },120000);
});
