import { afterAll, beforeAll, describe, expect, it, vi } from "vitest";
import { eq } from "drizzle-orm";
import { createTestDatabase, integrationEnabled, stopRelay, type TestDatabase } from "@surveynt/db/testing";
import { clientPayments, customerQuotes, invoices, jobs, jobStageEvents, organisations, organisationDocuments, organisationOperationalSettings, organisationMemberships, reportDeliveries, users, withTenant, createDatabase } from "@surveynt/db";
import { readSurveyFileRetention } from "../src/lib/survey-file-retention-register";
import { jobRetentionHolds } from "@surveynt/db";
import { evidenceLinks, mediaAssets, reportVersions, surveyElements } from "@surveynt/db";
import { preinspectionDocuments } from "@surveynt/db";
import { auditEvents } from "@surveynt/db";
import { prepareReviewedSurveyFileRemoval } from "../src/lib/survey-file-removal-prepare";
import { cancelReviewedSurveyFileRemoval, requestReviewedSurveyFileRemoval } from "../src/lib/survey-file-removal-request";
import { revalidateQueuedSurveyFileRemoval } from "../src/lib/survey-file-removal-revalidate";
import { surveyFileRemovals } from "@surveynt/db";
import { assistantTasks, fieldProposals, mediaAnalyses } from "@surveynt/db";
import { readSurveyFileProvenance } from "../src/lib/survey-file-provenance-register";
import { readSurveyFileMedia } from "../src/lib/survey-file-media-register";
import { isFieldRequired, listFields, residentialTemplateV1, type FieldDefinition, type FieldValue, type SyncOperation } from "@surveynt/assistant";
import { syncSourceRegistry } from "@surveynt/property-data/importers";
import { seedStakeholderDemo } from "../src/lib/stakeholder-demo";
import { acceptQuoteAddress, createPublicQuote, readPublicQuote } from "../src/lib/firm-operations";
import { createSurvey, applySyncOperations, type SurveyContext } from "../src/lib/surveys";
import { composeSurveyReport, approveReportVersion } from "../src/lib/reports";
import { enforceStageGate } from "../src/lib/completion";
import { POST as checkout } from "../src/app/api/v1/public/quotes/[id]/checkout/route";
import { GET as slots, POST as book } from "../src/app/api/v1/public/quotes/[id]/appointments/route";
import { GET as reports, POST as confirmReportReceipt } from "../src/app/api/v1/public/quotes/[id]/reports/route";

function sample(field: FieldDefinition): FieldValue {
  switch(field.type){
    case "enum": return {state:"provided",value:["listed_status","conservation_area"].includes(field.key)?"no_record_found":field.options![0].value};
    case "integer": case "decimal": return {state:"provided",value:field.min??1};
    case "boolean": return {state:"provided",value:false};
    case "date": return {state:"provided",value:new Date().toISOString().slice(0,10)};
    default: return {state:"provided",value:`Fictional demonstration: ${field.key.replaceAll("_"," ")}.`};
  }
}
function inspectionFixture(): SyncOperation[] {
  const operations:SyncOperation[]=[];let count=0;const op=()=>`op_demo_journey_${String(++count).padStart(6,"0")}`;
  for(const section of residentialTemplateV1.sections)for(const element of section.elements)if(element.inspectable)operations.push({type:"set_element",operationId:op(),element:{sectionKey:section.key,elementKey:element.key,locationLabel:""},inspectionStatus:section.key==="outside"&&element.key==="roof_coverings"?"inspected":"not_applicable",limitationReason:null,baseVersion:null});
  for(const resolved of listFields(residentialTemplateV1))if(!resolved.element.inspectable&&isFieldRequired(resolved.field,{serviceLevel:"level_1"}))operations.push({type:"set_field",operationId:op(),fieldPath:resolved.path,value:sample(resolved.field),baseValueId:null});
  operations.push({type:"set_field",operationId:op(),fieldPath:"outside.roof_coverings.condition_rating",value:{state:"provided",value:"2"},baseValueId:null},{type:"set_field",operationId:op(),fieldPath:"outside.roof_coverings.construction",value:{state:"provided",value:"Fictional demo: pitched natural-slate roof."},baseValueId:null});
  return operations;
}

describe.skipIf(!integrationEnabled)("stakeholder staff and customer journey",()=>{
  let database:TestDatabase, context:SurveyContext;
  beforeAll(async()=>{
    database=await createTestDatabase();Object.assign(process.env,{DATABASE_ADMIN_URL:database.adminUrl,DATABASE_APP_URL:database.appUrl});
    const db=database.connect(database.adminUrl);await syncSourceRegistry(db);
    const [owner]=await db.insert(users).values({clerkUserId:"user_journey_owner",email:"owner@example.test"}).returning();
    const [org]=await db.insert(organisations).values({clerkOrganisationId:"org_journey_demo",slug:"journey-demo",name:"Journey demonstration",practiceType:"building_surveying",region:"Bristol",status:"active",isDemo:true,demoGeneration:1}).returning();
    // This test practitioner is explicitly granted both permissions; demo owners
    // created by the application retain false defaults.
    await db.insert(organisationMemberships).values({ organisationId: org.id, userId: owner.id, role: "owner", active: true, canRecordSurvey: true, canApproveReports: true });
    context={organisationId:org.id,internalUserId:owner.id,role:"owner",canRecordSurvey:true,canApproveReports:true};await seedStakeholderDemo(org.id,owner.id,db);
  },120000);
  afterAll(async()=>{vi.unstubAllGlobals();await database?.drop();await stopRelay();});
  it("persists quote, decline, exactly-once deposit, booking, explicit report approval, customer issue and balance",async()=>{
    const noExternal=vi.fn(()=>{throw new Error("Demo called an external service");});vi.stubGlobal("fetch",noExternal);
    const created=await createPublicQuote({organisationId:context.organisationId,actorUserId:context.internalUserId!,requestId:crypto.randomUUID(),firstName:"Featured",lastName:"Customer",email:"featured@example.test",answers:{purpose:"survey-only",propertyAge:"post-1990",propertyType:"house"}});
    const id=created.quote.id as string, route={params:Promise.resolve({id})};
    const request=(path:string,body?:unknown,token=created.token)=>new Request(`http://surveynt.test/api/v1/public/quotes/${id}${path}`,{method:body?"POST":"GET",headers:{"content-type":"application/json","x-quote-token":token},...(body?{body:JSON.stringify(body)}:{})});
    await acceptQuoteAddress(id,created.token,{line1:"1 Fictional Demo Street",city:"Bristol",postcode:"BS1 1AA"});
    expect((await checkout(request("/checkout",{scenario:"failure"}),route)).status).toBe(402);
    const deposits=await Promise.all([checkout(request("/checkout",{purpose:"deposit"}),route),checkout(request("/checkout",{purpose:"deposit"}),route)]);
    expect(deposits.every(response=>response.ok)).toBe(true);
    const found=(await readPublicQuote(id,created.token))!;expect(found.view.depositPaid).toBe(true);const jobId=found.row.jobId!;
    const available=await slots(request("/appointments"),route);const choices=(await available.json()).data;expect(choices.length).toBeGreaterThan(0);
    const first=await book(request("/appointments",{startsAt:choices[0].startsAt}),route),second=await book(request("/appointments",{startsAt:choices[0].startsAt}),route);
    expect((await first.json()).data.id).toBe((await second.json()).data.id);
    const capture=await createSurvey(context,jobId,{serviceLevel:"level_1"});if(capture.kind!=="created")throw new Error(capture.kind);
    expect((await applySyncOperations(context,capture.survey.id,inspectionFixture())).every(result=>result.status==="applied")).toBe(true);
    const draft=await composeSurveyReport(context,capture.survey.id);
    expect((await (await reports(request("/reports"),route)).json()).data).toEqual([]);
    await expect(approveReportVersion(context,capture.survey.id,draft.id,{confirm:false})).rejects.toMatchObject({code:"confirmation_required"});
    await approveReportVersion(context,capture.survey.id,draft.id,{confirm:true,note:"Explicit fictional stakeholder review in isolated test database."});
    await withTenant(createDatabase(),context.organisationId,async tx=>{expect(await enforceStageGate(tx,context,{jobId,targetStage:"issued",overrides:[]})).toMatchObject({kind:"passed"});await tx.update(jobs).set({stage:"issued"}).where(eq(jobs.id,jobId));});
    const issued=(await (await reports(request("/reports"),route)).json()).data;expect(issued).toHaveLength(1);expect(issued[0].content).toBeTruthy();expect(issued[0]).not.toHaveProperty("trace");
    const acknowledgements=await Promise.all([1,2].map(()=>confirmReportReceipt(request("/reports",{reportVersionId:issued[0].id,confirmed:true}),route)));
    expect(acknowledgements.every(response=>response.ok)).toBe(true);
    expect((await acknowledgements[0].json()).data.id).toBe((await acknowledgements[1].json()).data.id);
    const deliveryRows=await database.connect(database.adminUrl).select().from(reportDeliveries).where(eq(reportDeliveries.jobId,jobId));
    expect(deliveryRows).toHaveLength(1);expect(deliveryRows[0]).toMatchObject({status:"delivered",deliveryMethod:"customer_acknowledgement",reportVersionId:issued[0].id});
    expect(deliveryRows[0].deliveredAt).toBeInstanceOf(Date);
    expect((await confirmReportReceipt(request("/reports",{reportVersionId:issued[0].id,confirmed:true},"wrong-token"),route)).status).toBe(404);
    expect((await confirmReportReceipt(request("/reports",{reportVersionId:crypto.randomUUID(),confirmed:true}),route)).status).toBe(409);
    expect((await reports(request("/reports",undefined,"wrong-token"),route)).status).toBe(404);
    expect((await checkout(request("/checkout",{purpose:"balance"}),route)).ok).toBe(true);
    expect((await readPublicQuote(id,created.token))?.view.balanceMinor).toBe(0);
    const db=database.connect(database.adminUrl);const payments=await db.select().from(clientPayments).where(eq(clientPayments.quoteId,id));expect(payments).toHaveLength(2);expect(payments.every(payment=>payment.status==="succeeded")).toBe(true);
    const bills=await db.select().from(invoices).where(eq(invoices.quoteId,id));expect(bills).toHaveLength(2);expect(bills.reduce((sum,bill)=>sum+bill.totalMinor,0)).toBe(found.row.totalMinor);expect(bills.reduce((sum,bill)=>sum+bill.vatMinor,0)).toBe(found.row.vatMinor);
    await db.update(jobs).set({stage:"archived"}).where(eq(jobs.id,jobId));
    await db.delete(jobStageEvents).where(eq(jobStageEvents.jobId,jobId));
    await db.insert(jobStageEvents).values({organisationId:context.organisationId,jobId,fromStage:"paid",toStage:"archived",createdAt:new Date("2000-02-01T00:00:00Z")});
    await db.update(organisationOperationalSettings).set({surveyFileRetentionPolicy:{version:"survey-file-1-year-v2",revision:1,enabled:true,approvedAt:new Date().toISOString(),approvedByUserId:context.internalUserId!,reason:"Disposable test practice retention approval"}}).where(eq(organisationOperationalSettings.organisationId,context.organisationId));
    const register=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileRetention(tx,context.organisationId,jobId));
    expect(register?.assessment.reason).toBe("retention_active");
    await db.update(reportDeliveries).set({deliveredAt:new Date("2000-03-01T00:00:00Z")}).where(eq(reportDeliveries.jobId,jobId));
    const expired=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileRetention(tx,context.organisationId,jobId));
    expect(expired?.assessment.reason).toBe("manager_review_required");
    expect(expired?.assessment.retentionUntil?.toISOString()).toBe("2001-03-01T00:00:00.000Z");
    expect(expired?.assessment.reviewVersion).not.toBe(register?.assessment.reviewVersion);
    expect(expired?.removalAuthorised).toBe(false);
    const [retentionJob]=await db.select().from(jobs).where(eq(jobs.id,jobId));
    const originalQuestionnaireId=crypto.randomUUID(),replacementQuestionnaireId=crypto.randomUUID();
    const [questionnaireOriginal]=await db.insert(preinspectionDocuments).values({id:originalQuestionnaireId,organisationId:context.organisationId,jobId,propertyId:retentionJob.propertyId,requestId:crypto.randomUUID(),name:"Original certificate.pdf",contentType:"application/pdf",sizeBytes:4,checksum:"c".repeat(64),storageKey:`organisations/${context.organisationId}/preinspection/${jobId}/${originalQuestionnaireId}/original`,source:"customer",analysis:{privateText:"Fictional extracted text"}}).returning();
    await db.insert(preinspectionDocuments).values({id:replacementQuestionnaireId,organisationId:context.organisationId,jobId,propertyId:retentionJob.propertyId,requestId:crypto.randomUUID(),name:"Replacement certificate.pdf",contentType:"application/pdf",sizeBytes:4,checksum:"d".repeat(64),storageKey:`organisations/${context.organisationId}/preinspection/${jobId}/${replacementQuestionnaireId}/original`,source:"customer",replacesId:questionnaireOriginal.id});
    const questionnaireFile=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileRetention(tx,context.organisationId,jobId));
    expect(questionnaireFile?.questionnaireDocuments).toHaveLength(2);expect(questionnaireFile?.assessment.reviewVersion).not.toBe(expired?.assessment.reviewVersion);
    expect(questionnaireFile?.questionnaireDocuments[0]).not.toHaveProperty("analysis");
    await expect(withTenant(createDatabase(),context.organisationId,tx=>prepareReviewedSurveyFileRemoval(tx,context.organisationId,jobId,questionnaireFile!.assessment.reviewVersion))).rejects.toThrow("manager");
    await db.insert(auditEvents).values({organisationId:context.organisationId,actorUserId:context.internalUserId!,action:"job.retention_file_reviewed",resourceType:"job",resourceId:jobId,metadata:{reviewVersion:questionnaireFile!.assessment.reviewVersion,confirmed:true,noUnresolvedComplaintOrClaim:true}});
    const prepared=await withTenant(createDatabase(),context.organisationId,tx=>prepareReviewedSurveyFileRemoval(tx,context.organisationId,jobId,questionnaireFile!.assessment.reviewVersion));
    expect(prepared.manifest.objects).toHaveLength(2);expect(prepared.manifest.objects.every(object=>object.kind==="questionnaire")).toBe(true);
    await db.update(organisationMemberships).set({active:false}).where(eq(organisationMemberships.userId,context.internalUserId!));
    await expect(withTenant(createDatabase(),context.organisationId,tx=>prepareReviewedSurveyFileRemoval(tx,context.organisationId,jobId,questionnaireFile!.assessment.reviewVersion))).rejects.toThrow("manager");
    await db.update(organisationMemberships).set({active:true}).where(eq(organisationMemberships.userId,context.internalUserId!));
    await expect(withTenant(createDatabase(),context.organisationId,tx=>prepareReviewedSurveyFileRemoval(tx,context.organisationId,jobId,expired!.assessment.reviewVersion))).rejects.toThrow("changed");
    const removalRequest={requestId:crypto.randomUUID(),reviewVersion:questionnaireFile!.assessment.reviewVersion,reason:"Manager confirmed expiry and reviewed every retained original.",confirmed:true as const};
    const requested=await Promise.all([1,2].map(()=>withTenant(createDatabase(),context.organisationId,tx=>requestReviewedSurveyFileRemoval(tx,context.organisationId,jobId,context.internalUserId!,removalRequest))));
    expect(requested[0].id).toBe(requested[1].id);expect(requested.map(result=>result.duplicate).sort()).toEqual([false,true]);expect(requested.every(result=>result.storageRemoved===false)).toBe(true);
    const removalRows=await db.select().from(surveyFileRemovals).where(eq(surveyFileRemovals.jobId,jobId));expect(removalRows).toHaveLength(1);expect(removalRows[0].manifestVersion).toBe(prepared.manifest.manifestVersion);
    expect((await withTenant(createDatabase(),context.organisationId,tx=>revalidateQueuedSurveyFileRemoval(tx,context.organisationId,jobId,requested[0].id))).manifest.manifestVersion).toBe(prepared.manifest.manifestVersion);
    await expect(db.update(surveyFileRemovals).set({manifest:{objects:[]}}).where(eq(surveyFileRemovals.id,requested[0].id))).rejects.toThrow();
    await expect(db.delete(surveyFileRemovals).where(eq(surveyFileRemovals.id,requested[0].id))).rejects.toThrow();
    await expect(db.update(surveyFileRemovals).set({progress:{unknown:{state:"removed"}}}).where(eq(surveyFileRemovals.id,requested[0].id))).rejects.toThrow();
    const firstOriginal=prepared.manifest.objects[0];
    await expect(db.update(surveyFileRemovals).set({status:"verification_required",progress:{[`${firstOriginal.kind}:${firstOriginal.id}`]:{state:"removed",attemptId:crypto.randomUUID(),removedAt:new Date().toISOString()}}}).where(eq(surveyFileRemovals.id,requested[0].id))).rejects.toThrow();
    await expect(db.transaction(async tx=>{
      await tx.update(surveyFileRemovals).set({status:"dispatched",leaseToken:crypto.randomUUID(),lockedUntil:new Date(Date.now()+300000),attempts:1}).where(eq(surveyFileRemovals.id,requested[0].id));
      await tx.update(surveyFileRemovals).set({attempts:0}).where(eq(surveyFileRemovals.id,requested[0].id));
    })).rejects.toThrow();
    for(const invalidEvidence of [{attemptId:"invalid",removedAt:new Date().toISOString()},{attemptId:crypto.randomUUID(),removedAt:"infinity"},{attemptId:crypto.randomUUID(),removedAt:"2999-01-01T00:00:00Z"}]) {
      await expect(db.transaction(async tx=>{
        await tx.update(surveyFileRemovals).set({status:"dispatched",leaseToken:crypto.randomUUID(),lockedUntil:new Date(Date.now()+300000),attempts:1,progress:{[`${firstOriginal.kind}:${firstOriginal.id}`]:{state:"removed",...invalidEvidence}}}).where(eq(surveyFileRemovals.id,requested[0].id));
      })).rejects.toThrow();
    }
    await expect(db.transaction(async tx=>{
      await tx.update(surveyFileRemovals).set({status:"dispatched",leaseToken:crypto.randomUUID(),lockedUntil:new Date(Date.now()+300000),attempts:1,progress:{[`${firstOriginal.kind}:${firstOriginal.id}`]:{state:"removed",attemptId:crypto.randomUUID(),removedAt:new Date().toISOString()}}}).where(eq(surveyFileRemovals.id,requested[0].id));
      await tx.update(surveyFileRemovals).set({progress:{}}).where(eq(surveyFileRemovals.id,requested[0].id));
    })).rejects.toThrow();
    await expect(db.update(surveyFileRemovals).set({status:"completed",completedAt:new Date()}).where(eq(surveyFileRemovals.id,requested[0].id))).rejects.toThrow();
    await expect(db.transaction(async tx=>{
      await tx.update(surveyFileRemovals).set({status:"dispatched",leaseToken:crypto.randomUUID(),lockedUntil:new Date(Date.now()+300000),attempts:1}).where(eq(surveyFileRemovals.id,requested[0].id));
      await tx.update(surveyFileRemovals).set({status:"completed",completedAt:new Date()}).where(eq(surveyFileRemovals.id,requested[0].id));
    })).rejects.toThrow();
    await expect(withTenant(createDatabase(),context.organisationId,tx=>requestReviewedSurveyFileRemoval(tx,context.organisationId,jobId,context.internalUserId!,{...removalRequest,reason:"Changed removal decision with reused identifier."}))).rejects.toThrow("different decision");
    await expect(withTenant(createDatabase(),context.organisationId,tx=>requestReviewedSurveyFileRemoval(tx,context.organisationId,jobId,context.internalUserId!,{...removalRequest,requestId:crypto.randomUUID()}))).rejects.toThrow("already exists");
    await expect(withTenant(createDatabase(),context.organisationId,async tx=>{
      const decision={id:requested[0].id,manifestVersion:prepared.manifest.manifestVersion,reason:"Manager stopped removal pending further file review.",confirmed:true as const};
      expect(await cancelReviewedSurveyFileRemoval(tx,context.organisationId,jobId,context.internalUserId!,decision)).toMatchObject({status:"cancelled",duplicate:false});
      expect(await cancelReviewedSurveyFileRemoval(tx,context.organisationId,jobId,context.internalUserId!,decision)).toMatchObject({status:"cancelled",duplicate:true});
      const replacement=await requestReviewedSurveyFileRemoval(tx,context.organisationId,jobId,context.internalUserId!,{...removalRequest,requestId:crypto.randomUUID()});
      expect(replacement.id).not.toBe(requested[0].id);
      throw new Error("Rollback cancellation fixture");
    })).rejects.toThrow("Rollback cancellation fixture");
    const [jobHold]=await db.insert(jobRetentionHolds).values({organisationId:context.organisationId,jobId,kind:"complaint",reason:"Unresolved customer complaint requires file retention.",reviewedByUserId:context.internalUserId!}).returning();
    const complaint=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileRetention(tx,context.organisationId,jobId));
    expect(complaint?.assessment.reason).toBe("protected");expect(complaint?.assessment.reviewVersion).not.toBe(expired?.assessment.reviewVersion);
    await expect(withTenant(createDatabase(),context.organisationId,tx=>revalidateQueuedSurveyFileRemoval(tx,context.organisationId,jobId,requested[0].id))).rejects.toThrow("changed");
    await db.update(jobRetentionHolds).set({kind:null,revision:2,reason:"Complaint resolved and manager authorised clearance."}).where(eq(jobRetentionHolds.id,jobHold.id));
    const clearedFile=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileRetention(tx,context.organisationId,jobId));
    expect(clearedFile?.assessment.reason).toBe("manager_review_required");expect(clearedFile?.assessment.reviewVersion).not.toBe(expired?.assessment.reviewVersion);
    const [jobRow]=await db.select().from(jobs).where(eq(jobs.id,jobId));
    const [original]=await db.insert(mediaAssets).values({organisationId:context.organisationId,propertyId:jobRow.propertyId,surveyId:capture.survey.id,kind:"photo",storageKey:`test/${jobId}/original`,contentType:"image/jpeg",byteSize:4,sha256:"a".repeat(64),clientGeneratedId:"retention-original-1",originalFilename:"inspection.jpg"}).returning();
    await db.insert(mediaAssets).values({organisationId:context.organisationId,propertyId:jobRow.propertyId,surveyId:null,kind:"photo",storageKey:`test/${jobId}/thumbnail`,contentType:"image/jpeg",byteSize:2,sha256:"b".repeat(64),clientGeneratedId:"retention-thumbnail-1",derivedFromId:original.id,derivation:"thumbnail"});
    const mediaFile=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileRetention(tx,context.organisationId,jobId));
    expect(mediaFile?.media).toHaveLength(2);expect(mediaFile?.assessment.reviewVersion).not.toBe(clearedFile?.assessment.reviewVersion);
    const [analysis]=await db.insert(mediaAnalyses).values({organisationId:context.organisationId,mediaId:original.id,surveyId:capture.survey.id,analyser:"retention-fixture-v1",status:"completed",result:{privateText:"Fictional extracted certificate text"}}).returning();
    const analysedFile=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileRetention(tx,context.organisationId,jobId));
    expect(analysedFile?.analysisCount).toBe(1);expect(analysedFile?.assessment.reviewVersion).not.toBe(mediaFile?.assessment.reviewVersion);
    const provenance=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileProvenance(tx,context.organisationId,jobId,[original.id],[]));
    expect(provenance.analyses[0]).not.toHaveProperty("result");expect(provenance.analyses[0].resultFingerprint).toMatch(/^[a-f0-9]{64}$/);
    const missingMedia=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileMedia(tx,context.organisationId,jobId,[{media:[crypto.randomUUID()]}]));
    expect(missingMedia.referenceReviewRequired).toBe(true);expect(missingMedia.unresolvedReferences).toHaveLength(1);
    const malformedTrace=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileMedia(tx,context.organisationId,jobId,[{media:"invalid"}]));expect(malformedTrace.referenceReviewRequired).toBe(true);
    const [otherJob]=await db.insert(jobs).values({organisationId:context.organisationId,clientId:jobRow.clientId,propertyId:jobRow.propertyId,reference:"RETENTION-SHARED",serviceName:"Survey"}).returning();
    const otherSurvey=await createSurvey(context,otherJob.id,{serviceLevel:"level_1"});if(otherSurvey.kind!=="created")throw new Error(otherSurvey.kind);
    const [sourceReport]=await db.select().from(reportVersions).where(eq(reportVersions.id,issued[0].id));
    await db.insert(reportVersions).values({...sourceReport,id:crypto.randomUUID(),surveyId:otherSurvey.survey.id,jobId:otherJob.id,versionNumber:1,trace:{...sourceReport.trace,media:[original.id]}});
    const sharedFile=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileRetention(tx,context.organisationId,jobId));
    expect(sharedFile?.externalEvidenceReferenceCount).toBe(1);expect(sharedFile?.assessment.reason).toBe("evidence_review_required");expect(sharedFile?.assessment.eligibleForManagerReview).toBe(false);
    const [otherElement]=await db.insert(surveyElements).values({organisationId:context.organisationId,surveyId:otherSurvey.survey.id,sectionKey:"outside",elementKey:"roof_coverings"}).returning();
    await db.insert(evidenceLinks).values({organisationId:context.organisationId,surveyId:otherSurvey.survey.id,targetType:"element",targetId:otherElement.id,evidenceType:"prior_survey",evidenceId:capture.survey.id,clientGeneratedId:"retention-prior-reference"});
    const priorReferenced=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileRetention(tx,context.organisationId,jobId));
    expect(priorReferenced?.externalEvidenceReferenceCount).toBe(2);expect(priorReferenced?.assessment.reviewVersion).not.toBe(sharedFile?.assessment.reviewVersion);
    await db.insert(assistantTasks).values({organisationId:context.organisationId,surveyId:otherSurvey.survey.id,kind:"discrepancy",dedupeKey:"retention-shared-analysis",title:"Shared original reference",evidence:{type:"document_span",mediaId:original.id,analysisId:analysis.id}});
    const adviserReferenced=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileRetention(tx,context.organisationId,jobId));
    expect(adviserReferenced?.externalEvidenceReferenceCount).toBe(3);expect(adviserReferenced?.assessment.eligibleForManagerReview).toBe(false);
    await db.insert(fieldProposals).values({organisationId:context.organisationId,surveyId:otherSurvey.survey.id,fieldPath:"matters.legal.guarantees",proposedValue:{state:"provided",value:"Fictional document reference"},valueType:"text",evidenceRefs:[{type:"document_span",id:questionnaireOriginal.id,context:{mediaId:original.id}}],originClass:"document_extraction",inputVersion:"fixture-v1",generator:"retention-fixture",dedupeKey:"retention-questionnaire-reference"});
    const proposalReferenced=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileRetention(tx,context.organisationId,jobId));
    expect(proposalReferenced?.externalEvidenceReferenceCount).toBe(4);expect(proposalReferenced?.assessment.reviewVersion).not.toBe(adviserReferenced?.assessment.reviewVersion);
    const [foreignOrg]=await db.insert(organisations).values({clerkOrganisationId:"org_retention_foreign",slug:"retention-foreign",name:"Foreign fixture",practiceType:"residential",region:"Bristol",status:"active"}).returning();
    const foreignProvenance=await withTenant(createDatabase(),foreignOrg.id,tx=>readSurveyFileProvenance(tx,foreignOrg.id,jobId,[original.id],[]));
    expect(foreignProvenance.analyses).toEqual([]);expect(foreignProvenance.tasks).toEqual([]);expect(foreignProvenance.proposals).toEqual([]);
    expect(await withTenant(createDatabase(),foreignOrg.id,tx=>tx.select().from(surveyFileRemovals).where(eq(surveyFileRemovals.jobId,jobId)))).toEqual([]);
    await expect(withTenant(createDatabase(),foreignOrg.id,tx=>prepareReviewedSurveyFileRemoval(tx,foreignOrg.id,jobId,questionnaireFile!.assessment.reviewVersion))).rejects.toThrow("unavailable");
    await db.insert(organisationDocuments).values({organisationId:context.organisationId,jobId,name:"Held original",category:"legal",blobUrl:"https://example.test/held",blobPathname:"held",checksum:"held",contentType:"text/plain",sizeBytes:4,legalHold:true});
    const held=await withTenant(createDatabase(),context.organisationId,tx=>readSurveyFileRetention(tx,context.organisationId,jobId));
    expect(held?.assessment.reason).toBe("protected");expect(held?.assessment.reviewVersion).not.toBe(expired?.assessment.reviewVersion);
    expect((await confirmReportReceipt(request("/reports",{reportVersionId:issued[0].id,confirmed:true}),route)).status).toBe(409);
    await db.update(organisations).set({status:"suspended"}).where(eq(organisations.id,context.organisationId));
    expect((await confirmReportReceipt(request("/reports",{reportVersionId:issued[0].id,confirmed:true}),route)).status).toBe(404);
    await db.update(organisations).set({status:"active"}).where(eq(organisations.id,context.organisationId));
    await db.update(customerQuotes).set({tokenRevokedAt:new Date()}).where(eq(customerQuotes.id,id));
    expect((await confirmReportReceipt(request("/reports",{reportVersionId:issued[0].id,confirmed:true}),route)).status).toBe(404);
    expect(await db.select().from(reportDeliveries).where(eq(reportDeliveries.jobId,jobId))).toHaveLength(1);
    expect(noExternal).not.toHaveBeenCalled();vi.unstubAllGlobals();
  },120000);
  it("allows only one concurrent customer claim for the same surveyor slot",async()=>{
    const created=await Promise.all(["First","Second"].map(firstName=>createPublicQuote({organisationId:context.organisationId,actorUserId:context.internalUserId!,requestId:crypto.randomUUID(),firstName,email:`${firstName.toLowerCase()}@example.test`,answers:{purpose:"survey-only",propertyAge:"post-1990",propertyType:"house"}})));
    const request=(index:number,path:string,body?:unknown)=>new Request(`http://surveynt.test/api/v1/public/quotes/${created[index].quote.id}${path}`,{method:body?"POST":"GET",headers:{"content-type":"application/json","x-quote-token":created[index].token},...(body?{body:JSON.stringify(body)}:{})});
    const routes=created.map(value=>({params:Promise.resolve({id:value.quote.id as string})}));
    await Promise.all(created.map(value=>acceptQuoteAddress(value.quote.id as string,value.token,{line1:"2 Fictional Demo Street",city:"Bristol",postcode:"BS1 1AA"})));
    await Promise.all(created.map((_,index)=>checkout(request(index,"/checkout",{purpose:"deposit"}),routes[index])));
    const available=(await (await slots(request(0,"/appointments"),routes[0])).json()).data;
    expect(available.length).toBeGreaterThan(0);
    const results=await Promise.all(created.map((_,index)=>book(request(index,"/appointments",{startsAt:available[0].startsAt}),routes[index])));
    expect(results.map(value=>value.status).sort()).toEqual([200,409]);
    const successful=results.find(value=>value.ok)!;
    expect((await successful.json()).data.surveyorId).toBe(context.internalUserId);
  },120000);
});
