import {workspaceAudit} from "@/lib/workspace-audit";
import "server-only";
import {and,eq,sql,notInArray,gt,isNull} from "drizzle-orm";
import {createDatabase,withTenant,staffCapabilities,businessLocations,serviceDefinitions,memberWorkProfiles,organisationMemberships,organisationOperationalSettings,users,jobs,properties,appointments,availabilityBlocks,calendarConnections,auditEvents,jobAssignments,backgroundJobs,latestStaffLocations,trackingSessions,type TenantTransaction} from "@surveynt/db";
import {allocationReasons,directKm} from "./assignment-eligibility";
import {enabledConnection} from "./platform-connections";
import {connectionJson} from "./connection-network";
import {normaliseRoadRoute} from "./fieldwork";
import {GovernanceError} from "./ai-governance";
import {hasProfessionalPermission} from "@surveynt/domain";
import {withinWorkingHours} from "./booking-slots";
import type {OperationsContext} from "./staff-operations";
async function candidates(tx:TenantTransaction,org:string,jobId:string,start:Date,end:Date){
const [record]=await tx.select({job:jobs,property:properties}).from(jobs).innerJoin(properties,and(eq(properties.id,jobs.propertyId),eq(properties.organisationId,jobs.organisationId))).where(and(eq(jobs.id,jobId),eq(jobs.organisationId,org))).limit(1);if(!record)throw new GovernanceError(404,"not_found","Job unavailable.");
const [staff,services,work,visits,blocks,calendars,live,sites,[settings]]=await Promise.all([tx.select({membership:organisationMemberships,user:users,capability:staffCapabilities,base:businessLocations,workProfile:memberWorkProfiles}).from(organisationMemberships).innerJoin(users,eq(users.id,organisationMemberships.userId)).leftJoin(staffCapabilities,and(eq(staffCapabilities.userId,users.id),eq(staffCapabilities.organisationId,org))).leftJoin(businessLocations,and(eq(businessLocations.id,staffCapabilities.primaryLocationId),eq(businessLocations.organisationId,org))).leftJoin(memberWorkProfiles,and(eq(memberWorkProfiles.userId,users.id),eq(memberWorkProfiles.organisationId,org))).where(and(eq(organisationMemberships.organisationId,org),eq(organisationMemberships.active,true))),tx.select().from(serviceDefinitions).where(and(eq(serviceDefinitions.organisationId,org),eq(serviceDefinitions.active,true),eq(serviceDefinitions.name,record.job.serviceName))),tx.select({userId:jobs.assignedSurveyorId,id:jobs.id}).from(jobs).where(and(eq(jobs.organisationId,org),notInArray(jobs.stage,["paid","archived"]))),tx.select().from(appointments).where(and(eq(appointments.organisationId,org),notInArray(appointments.status,["cancelled"]))),tx.select().from(availabilityBlocks).where(eq(availabilityBlocks.organisationId,org)),tx.select().from(calendarConnections).where(eq(calendarConnections.organisationId,org)),tx.select({userId:latestStaffLocations.userId,latitude:latestStaffLocations.latitude,longitude:latestStaffLocations.longitude,accuracy:latestStaffLocations.accuracyMetres}).from(latestStaffLocations).innerJoin(trackingSessions,and(eq(trackingSessions.id,latestStaffLocations.sessionId),eq(trackingSessions.organisationId,org))).where(and(eq(latestStaffLocations.organisationId,org),gt(latestStaffLocations.observedAt,new Date(Date.now()-120000)),gt(trackingSessions.expiresAt,new Date()),isNull(trackingSessions.stoppedAt))),tx.select().from(businessLocations).where(and(eq(businessLocations.organisationId,org),eq(businessLocations.active,true))),tx.select().from(organisationOperationalSettings).where(eq(organisationOperationalSettings.organisationId,org)).limit(1)]);
const buffer=(settings?.travelBufferMinutes??30)*60000;return staff.map(({membership,user,capability:c,base,workProfile:p})=>{const coveredSites=sites.filter(site=>c?.locationIds.includes(site.id)&&site.latitude!=null&&site.longitude!=null);const distance=base?.active&&base.latitude!=null&&base.longitude!=null&&record.property.latitude!=null&&record.property.longitude!=null&&coveredSites.length?Math.min(...coveredSites.map(site=>directKm({latitude:site.latitude!,longitude:site.longitude!},{latitude:record.property.latitude!,longitude:record.property.longitude!}))):null;const activeJobs=work.filter(j=>j.userId===user.id&&j.id!==jobId).length;const conflicts=visits.some(a=>a.jobId!==jobId&&a.surveyorId===user.id&&a.startsAt.getTime()<end.getTime()+buffer&&a.endsAt.getTime()>start.getTime()-buffer)||blocks.some(b=>(b.userId===null||b.userId===user.id)&&b.startsAt<end&&b.endsAt>start);const fresh=calendars.filter(c=>c.userId===user.id).every(c=>c.status==="active"&&c.lastSyncedAt&&Date.now()-c.lastSyncedAt.getTime()<15*60000);const reasons=allocationReasons({active:membership.active,recordingPermitted:hasProfessionalPermission(membership.role,"record_survey",membership.canRecordSurvey),serviceQualified:services.some(s=>c?.serviceIds.includes(s.id)),coverageRadiusKm:c?.coverageRadiusKm??null,distanceKm:distance,capacity:c?.capacityJobs??null,activeJobs,workingHours:p?.workingHours??{},timezone:p?.timezone??settings?.timezone??"Europe/London",startsAt:start,endsAt:end,busy:conflicts,calendarFresh:fresh,siteCovered:Boolean(base?.active&&coveredSites.length)});if(!settings||!withinWorkingHours(start,end,settings))reasons.push("Outside practice working days, holidays or booking horizon");const position=live.find(l=>l.userId===user.id&&l.accuracy<=500);return {userId:user.id,name:[user.firstName,user.lastName].filter(Boolean).join(" ")||user.email,eligible:!reasons.length,reasons,activeJobs,distanceKm:distance,travelOrigin:position?"Current shared position":"Operating base",origin:position?{latitude:position.latitude,longitude:position.longitude}:base?.latitude!=null&&base.longitude!=null?{latitude:base.latitude,longitude:base.longitude}:null,destination:record.property.latitude!=null&&record.property.longitude!=null?{latitude:record.property.latitude,longitude:record.property.longitude}:null,travelMinutes:null as number|null};});
}
export async function allocationRecommendations(context:OperationsContext,jobId:string,start:Date,end:Date){const rows=await withTenant(createDatabase(),context.organisationId,tx=>candidates(tx,context.organisationId,jobId,start,end));let routing=null;try{routing=await enabledConnection(context.organisationId,"routing");}catch{}if(routing)await Promise.all(rows.filter(r=>r.eligible&&r.origin&&r.destination).slice(0,20).map(async row=>{try{const c=routing.connection;const raw=await connectionJson(c.endpoint,`/route/v1/driving/${row.origin!.longitude},${row.origin!.latitude};${row.destination!.longitude},${row.destination!.latitude}`,{secret:c.credentialEnv?process.env[c.credentialEnv]:undefined,query:{overview:"full",geometries:"geojson"}});const result=normaliseRoadRoute(raw,1);row.travelMinutes=result?.durationSeconds?Math.ceil(result.durationSeconds/60):null;}catch{}}));return rows.sort((a,b)=>Number(b.eligible)-Number(a.eligible)||(a.travelMinutes??Infinity)-(b.travelMinutes??Infinity)||a.activeJobs-b.activeJobs||(a.distanceKm??Infinity)-(b.distanceKm??Infinity)).map(row=>({userId:row.userId,name:row.name,eligible:row.eligible,reasons:row.reasons,activeJobs:row.activeJobs,distanceKm:row.distanceKm,travelMinutes:row.travelMinutes,travelOrigin:row.travelOrigin}));}
export async function confirmAllocation(context:OperationsContext,jobId:string,input:{userId:string;startsAt:string;endsAt:string;version:number}){return withTenant(createDatabase(),context.organisationId,async tx=>{
// Same tenant calendar lock is used by booking; lock the target job as well.
await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${`${context.organisationId}:scheduling`}))`);const [job]=await tx.select().from(jobs).where(and(eq(jobs.organisationId,context.organisationId),eq(jobs.id,jobId))).for("update");if(!job||job.version!==input.version)throw new GovernanceError(409,"assignment_conflict","Job changed. Reload recommendations.");const staff=await tx.select().from(organisationMemberships).where(and(eq(organisationMemberships.organisationId,context.organisationId),eq(organisationMemberships.userId,input.userId),eq(organisationMemberships.active,true))).for("update");if(!staff.length)throw new GovernanceError(409,"staff_unavailable","Staff access changed.");const rows=await candidates(tx,context.organisationId,jobId,new Date(input.startsAt),new Date(input.endsAt));const selected=rows.find(r=>r.userId===input.userId);if(!selected?.eligible)throw new GovernanceError(409,"ineligible",selected?.reasons.join(". ")??"Staff unavailable.");const [visit]=await tx.select().from(appointments).where(and(eq(appointments.organisationId,context.organisationId),eq(appointments.jobId,jobId),eq(appointments.status,"confirmed"))).for("update");if(visit&&(visit.startsAt.toISOString()!==input.startsAt||visit.endsAt.toISOString()!==input.endsAt))throw new GovernanceError(409,"appointment_changed","Use the existing confirmed appointment time.");if(!visit)throw new GovernanceError(409,"appointment_required","Book a confirmed appointment before allocating this job.");await tx.update(jobs).set({assignedSurveyorId:input.userId,version:job.version+1,updatedAt:new Date()}).where(eq(jobs.id,jobId));await tx.update(appointments).set({surveyorId:input.userId,version:visit.version+1,updatedAt:new Date()}).where(eq(appointments.id,visit.id));await tx.delete(jobAssignments).where(and(eq(jobAssignments.organisationId,context.organisationId),eq(jobAssignments.jobId,jobId),eq(jobAssignments.responsibility,"primary")));await tx.insert(jobAssignments).values({organisationId:context.organisationId,jobId,userId:input.userId,responsibility:"primary"});const connections=await tx.select().from(calendarConnections).where(and(eq(calendarConnections.organisationId,context.organisationId),eq(calendarConnections.status,"active")));for(const c of connections.filter(c=>c.userId===input.userId||c.userId===visit.surveyorId))await tx.insert(backgroundJobs).values({organisationId:context.organisationId,queue:"calendar",type:"calendar_reconcile",deduplicationKey:`allocation:${visit.id}:${visit.version+1}:${c.id}`,payload:{connectionId:c.id}}).onConflictDoNothing();await tx.insert(auditEvents).values(workspaceAudit(context,{organisationId:context.organisationId,actorUserId:context.internalUserId,action:"job.allocation_confirmed",resourceType:"job",resourceId:jobId,metadata:{userId:input.userId,appointmentId:visit.id,eligibilityRechecked:true}}));return {assignedSurveyorId:input.userId};});}
