import {createCipheriv} from "node:crypto";
import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import {calendarEncryptionKeyVersion,calendarSecretUsesActiveKey,decryptCalendarSecret,encryptCalendarSecret} from "./calendar-oauth";
const oldKey=Buffer.alloc(32,5),newKey=Buffer.alloc(32,9),tokens={access_token:"fictional-private-token"};
function legacy(){const iv=Buffer.alloc(12,3),cipher=createCipheriv("aes-256-gcm",oldKey,iv);const body=Buffer.concat([cipher.update(JSON.stringify(tokens)),cipher.final()]);return ["v1",iv.toString("base64url"),cipher.getAuthTag().toString("base64url"),body.toString("base64url")].join(".");}
beforeEach(()=>{vi.stubEnv("CALENDAR_TOKEN_ENCRYPTION_KEY",oldKey.toString("base64"));vi.stubEnv("CALENDAR_TOKEN_ENCRYPTION_KEY_VERSION","1");vi.stubEnv("CALENDAR_TOKEN_ENCRYPTION_PREVIOUS_KEYS","{}");});
afterEach(()=>vi.unstubAllEnvs());
describe("calendar credential key rotation",()=>{
 it("reads legacy credentials and writes authenticated versioned ciphertext",()=>{expect(decryptCalendarSecret(legacy())).toEqual(tokens);const encrypted=encryptCalendarSecret(tokens);expect(encrypted).toMatch(/^v2\.1\./);expect(calendarSecretUsesActiveKey(encrypted)).toBe(true);expect(decryptCalendarSecret(encrypted)).toEqual(tokens);expect(encrypted).not.toContain(tokens.access_token);});
 it("retains both old formats while encrypting with the new key",()=>{const oldModern=encryptCalendarSecret(tokens),oldLegacy=legacy();vi.stubEnv("CALENDAR_TOKEN_ENCRYPTION_KEY_VERSION","2");vi.stubEnv("CALENDAR_TOKEN_ENCRYPTION_KEY",newKey.toString("base64"));vi.stubEnv("CALENDAR_TOKEN_ENCRYPTION_PREVIOUS_KEYS",JSON.stringify({1:oldKey.toString("base64")}));expect(calendarEncryptionKeyVersion()).toBe(2);for(const old of [oldModern,oldLegacy]){expect(decryptCalendarSecret(old)).toEqual(tokens);expect(calendarSecretUsesActiveKey(old)).toBe(false);}expect(encryptCalendarSecret(tokens)).toMatch(/^v2\.2\./);});
 it("rejects key identity tampering even if two configured keys contain the same bytes",()=>{vi.stubEnv("CALENDAR_TOKEN_ENCRYPTION_KEY_VERSION","2");vi.stubEnv("CALENDAR_TOKEN_ENCRYPTION_PREVIOUS_KEYS",JSON.stringify({1:oldKey.toString("base64")}));const encrypted=encryptCalendarSecret(tokens);expect(()=>decryptCalendarSecret(encrypted.replace(/^v2\.2\./,"v2.1."))).toThrow();});
 it("fails closed for missing previous keys and malformed ciphertext",()=>{const encrypted=encryptCalendarSecret(tokens);vi.stubEnv("CALENDAR_TOKEN_ENCRYPTION_KEY_VERSION","2");expect(()=>decryptCalendarSecret(encrypted)).toThrow();for(const invalid of [encrypted+".extra","v2.1.bad.bad.bad","v2.0.bad.bad.bad"])expect(()=>decryptCalendarSecret(invalid)).toThrow();});
 it("rejects invalid active version and malformed retained keys",()=>{vi.stubEnv("CALENDAR_TOKEN_ENCRYPTION_KEY_VERSION","0");expect(()=>encryptCalendarSecret(tokens)).toThrow();vi.stubEnv("CALENDAR_TOKEN_ENCRYPTION_KEY_VERSION","2");vi.stubEnv("CALENDAR_TOKEN_ENCRYPTION_PREVIOUS_KEYS","not-json");expect(()=>decryptCalendarSecret(legacy())).toThrow("previous calendar encryption keys");});
});
