import { and, asc, eq, gt, inArray, lte, or } from "drizzle-orm";
import { appointments, availabilityBlocks, backgroundJobs, calendarConflicts, calendarConnections, calendarEventLinks, createDatabase } from "@surveynt/db";
import { decryptCalendarSecret, encryptCalendarSecret, type CalendarProvider } from "./calendar-oauth";
import { isDemoOrganisation } from "./stakeholder-demo";

type Tokens = { access_token: string; refresh_token?: string; expires_in?: number; obtained_at?: number; token_type?: string; scope?: string };
type ExternalEvent = { id: string; start: Date; end: Date; version: string | null; surveyntAppointmentId: string | null; cancelled: boolean };

async function validTokens(connection: typeof calendarConnections.$inferSelect) {
  let tokens = decryptCalendarSecret<Tokens>(connection.encryptedCredentials);
  if (!tokens.refresh_token || !tokens.expires_in || !tokens.obtained_at || tokens.obtained_at + tokens.expires_in * 1000 > Date.now() + 60_000) return tokens;
  const google = connection.provider === "google"; const body = new URLSearchParams({ client_id: google ? process.env.GOOGLE_CALENDAR_CLIENT_ID ?? "" : process.env.MICROSOFT_CALENDAR_CLIENT_ID ?? "", client_secret: google ? process.env.GOOGLE_CALENDAR_CLIENT_SECRET ?? "" : process.env.MICROSOFT_CALENDAR_CLIENT_SECRET ?? "", grant_type: "refresh_token", refresh_token: tokens.refresh_token }); if (!google) body.set("scope", "openid email offline_access User.Read Calendars.ReadWrite");
  const response = await fetch(google ? "https://oauth2.googleapis.com/token" : "https://login.microsoftonline.com/common/oauth2/v2.0/token", { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body }); const refreshed = await response.json() as Partial<Tokens>;
  if (!response.ok || !refreshed.access_token) throw new Error("Calendar access could not be refreshed."); tokens = { ...tokens, ...refreshed, refresh_token: refreshed.refresh_token ?? tokens.refresh_token, obtained_at: Date.now() };
  await createDatabase(process.env.DATABASE_ADMIN_URL).update(calendarConnections).set({ encryptedCredentials: encryptCalendarSecret(tokens), updatedAt: new Date() }).where(eq(calendarConnections.id, connection.id)); return tokens;
}

async function externalEvents(provider: CalendarProvider, accessToken: string) {
  const min = new Date(Date.now() - 30 * 86_400_000).toISOString(); const max = new Date(Date.now() + 120 * 86_400_000).toISOString();
  const url = provider === "google" ? `https://www.googleapis.com/calendar/v3/calendars/primary/events?singleEvents=true&maxResults=2500&timeMin=${encodeURIComponent(min)}&timeMax=${encodeURIComponent(max)}` : `https://graph.microsoft.com/v1.0/me/calendarView?startDateTime=${encodeURIComponent(min)}&endDateTime=${encodeURIComponent(max)}&$top=999&$select=id,start,end,isCancelled,categories,changeKey`;
  const response = await fetch(url, { headers: { authorization: `Bearer ${accessToken}`, prefer: 'outlook.timezone="UTC"' } }); const body = await response.json() as Record<string, unknown>; if (!response.ok) throw new Error("Calendar events could not be read.");
  const rows = provider === "google" ? body.items : body.value; if (!Array.isArray(rows)) return [];
  return rows.flatMap((raw): ExternalEvent[] => { const event = raw as Record<string, unknown>; const startObject = event.start as Record<string, unknown> | undefined; const endObject = event.end as Record<string, unknown> | undefined; const startValue = String(startObject?.dateTime ?? startObject?.date ?? ""); const endValue = String(endObject?.dateTime ?? endObject?.date ?? ""); const start = new Date(startValue); const end = new Date(endValue); if (!String(event.id) || Number.isNaN(start.getTime()) || Number.isNaN(end.getTime())) return []; const privateProperties = (event.extendedProperties as Record<string, Record<string, string>> | undefined)?.private; const categories = Array.isArray(event.categories) ? event.categories.map(String) : []; return [{ id: String(event.id), start, end, version: String(event.etag ?? event.changeKey ?? "") || null, surveyntAppointmentId: privateProperties?.surveyntAppointmentId ?? categories.find((item) => item.startsWith("surveynt:"))?.slice(9) ?? null, cancelled: event.status === "cancelled" || event.isCancelled === true }]; });
}

async function createExternalEvent(provider: CalendarProvider, accessToken: string, appointment: typeof appointments.$inferSelect) {
  const google = provider === "google"; const url = google ? "https://www.googleapis.com/calendar/v3/calendars/primary/events" : "https://graph.microsoft.com/v1.0/me/events";
  const payload = google ? { summary: "Surveynt property inspection", description: `Surveynt appointment ${appointment.id}`, start: { dateTime: appointment.startsAt.toISOString() }, end: { dateTime: appointment.endsAt.toISOString() }, extendedProperties: { private: { surveyntAppointmentId: appointment.id } } } : { subject: "Surveynt property inspection", body: { contentType: "text", content: `Surveynt appointment ${appointment.id}` }, start: { dateTime: appointment.startsAt.toISOString(), timeZone: "UTC" }, end: { dateTime: appointment.endsAt.toISOString(), timeZone: "UTC" }, categories: [`surveynt:${appointment.id}`] };
  const response = await fetch(url, { method: "POST", headers: { authorization: `Bearer ${accessToken}`, "content-type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json() as Record<string, unknown>; if (!response.ok || typeof body.id !== "string") throw new Error("Appointment could not be exported to the calendar."); return { id: body.id, version: String(body.etag ?? body.changeKey ?? "") || null };
}

async function updateExternalEvent(provider: CalendarProvider, accessToken: string, appointment: typeof appointments.$inferSelect, externalEventId: string) {
  const google = provider === "google"; const url = google ? `https://www.googleapis.com/calendar/v3/calendars/primary/events/${encodeURIComponent(externalEventId)}` : `https://graph.microsoft.com/v1.0/me/events/${encodeURIComponent(externalEventId)}`;
  const payload = google ? { summary: "Surveynt property inspection", description: `Surveynt appointment ${appointment.id}`, start: { dateTime: appointment.startsAt.toISOString() }, end: { dateTime: appointment.endsAt.toISOString() }, extendedProperties: { private: { surveyntAppointmentId: appointment.id } } } : { subject: "Surveynt property inspection", body: { contentType: "text", content: `Surveynt appointment ${appointment.id}` }, start: { dateTime: appointment.startsAt.toISOString(), timeZone: "UTC" }, end: { dateTime: appointment.endsAt.toISOString(), timeZone: "UTC" }, categories: [`surveynt:${appointment.id}`] };
  const response = await fetch(url, { method: "PATCH", headers: { authorization: `Bearer ${accessToken}`, "content-type": "application/json" }, body: JSON.stringify(payload) }); const body = response.status === 204 ? {} : await response.json() as Record<string, unknown>; if (!response.ok) throw new Error("Calendar appointment update failed."); return String(body.etag ?? body.changeKey ?? "") || null;
}

export async function reconcileCalendarConnection(connectionId: string) {
  if (process.env.DATABASE_ADMIN_URL) {
    const demoDb=createDatabase(process.env.DATABASE_ADMIN_URL);
    const [record]=await demoDb.select({organisationId:calendarConnections.organisationId}).from(calendarConnections).where(eq(calendarConnections.id,connectionId)).limit(1);
    if(record&&await isDemoOrganisation(record.organisationId,demoDb))return {importedBusy:0,exported:0,updated:0,simulated:true};
  }
  if (!process.env.DATABASE_ADMIN_URL) throw new Error("DATABASE_ADMIN_URL is required."); const db = createDatabase(process.env.DATABASE_ADMIN_URL); const [connection] = await db.select().from(calendarConnections).where(and(eq(calendarConnections.id, connectionId), eq(calendarConnections.status, "active"))).limit(1); if (!connection || (connection.provider !== "google" && connection.provider !== "microsoft")) throw new Error("Active calendar connection not found."); const tokens = await validTokens(connection); const remote = await externalEvents(connection.provider, tokens.access_token); const links = await db.select().from(calendarEventLinks).where(eq(calendarEventLinks.connectionId, connection.id)); const linkByExternal = new Map(links.map((link) => [link.externalEventId, link])); const linkedAppointmentIds = links.map((link) => link.appointmentId); const linkedAppointments = linkedAppointmentIds.length ? await db.select().from(appointments).where(inArray(appointments.id, linkedAppointmentIds)) : []; const appointmentById = new Map(linkedAppointments.map((item) => [item.id, item]));
  await db.transaction(async (tx) => { const source = `calendar:${connection.id}`; await tx.delete(availabilityBlocks).where(and(eq(availabilityBlocks.organisationId, connection.organisationId), eq(availabilityBlocks.source, source))); const busy = remote.filter((event) => !event.cancelled && !event.surveyntAppointmentId); if (busy.length) await tx.insert(availabilityBlocks).values(busy.map((event) => ({ organisationId: connection.organisationId, userId: connection.userId, startsAt: event.start, endsAt: event.end, kind: "external_busy", source, externalEventId: event.id })));
    for (const event of remote) { const link = linkByExternal.get(event.id); const appointment = link ? appointmentById.get(link.appointmentId) : null; if (!link || !appointment) continue; const changed = event.cancelled || Math.abs(event.start.getTime() - appointment.startsAt.getTime()) > 1000 || Math.abs(event.end.getTime() - appointment.endsAt.getTime()) > 1000; if (changed) { const [existing] = await tx.select({ id: calendarConflicts.id }).from(calendarConflicts).where(and(eq(calendarConflicts.connectionId, connection.id), eq(calendarConflicts.appointmentId, appointment.id), eq(calendarConflicts.status, "open"))).limit(1); if (!existing) await tx.insert(calendarConflicts).values({ organisationId: connection.organisationId, appointmentId: appointment.id, connectionId: connection.id, kind: event.cancelled ? "external_cancelled" : "external_time_changed", details: { externalStart: event.start.toISOString(), externalEnd: event.end.toISOString(), surveyntStart: appointment.startsAt.toISOString(), surveyntEnd: appointment.endsAt.toISOString() } }); } }
  });
  const toExport = await db.select().from(appointments).where(and(eq(appointments.organisationId, connection.organisationId), eq(appointments.surveyorId, connection.userId), neCancelled(), gt(appointments.endsAt, new Date()))).orderBy(asc(appointments.startsAt)).limit(250);
  const linkByAppointment = new Map(links.map((item) => [item.appointmentId, item])); let exported = 0; let updated = 0; for (const appointment of toExport) { const link = linkByAppointment.get(appointment.id); if (!link) { const external = await createExternalEvent(connection.provider, tokens.access_token, appointment); await db.insert(calendarEventLinks).values({ organisationId: connection.organisationId, connectionId: connection.id, appointmentId: appointment.id, externalEventId: external.id, externalVersion: external.version, lastSyncedAppointmentVersion: appointment.version }); exported += 1; continue; } if (appointment.version > link.lastSyncedAppointmentVersion) { const externalVersion = await updateExternalEvent(connection.provider, tokens.access_token, appointment, link.externalEventId); await db.update(calendarEventLinks).set({ externalVersion, lastSyncedAppointmentVersion: appointment.version, updatedAt: new Date() }).where(eq(calendarEventLinks.id, link.id)); updated += 1; } }
  await db.update(calendarConnections).set({ lastSyncedAt: new Date(), lastError: null, updatedAt: new Date() }).where(eq(calendarConnections.id, connection.id)); return { importedBusy: remote.filter((item) => !item.cancelled && !item.surveyntAppointmentId).length, exported, updated };
}

function neCancelled() { return or(eq(appointments.status, "provisional"), eq(appointments.status, "confirmed"), eq(appointments.status, "conflict"))!; }
export async function processCalendarQueue(limit = 10) {
  if (!process.env.DATABASE_ADMIN_URL) throw new Error("DATABASE_ADMIN_URL is required."); const db = createDatabase(process.env.DATABASE_ADMIN_URL); const candidates = await db.select().from(backgroundJobs).where(and(eq(backgroundJobs.queue, "calendar"), eq(backgroundJobs.status, "queued"), lte(backgroundJobs.availableAt, new Date()))).orderBy(asc(backgroundJobs.availableAt)).limit(limit); const results = [];
  for (const candidate of candidates) { const [job] = await db.update(backgroundJobs).set({ status: "processing", attempts: candidate.attempts + 1, updatedAt: new Date() }).where(and(eq(backgroundJobs.id, candidate.id), eq(backgroundJobs.status, "queued"))).returning(); if (!job) continue; try { const result = await reconcileCalendarConnection(String(job.payload.connectionId)); await db.update(backgroundJobs).set({ status: "completed", completedAt: new Date(), error: null, updatedAt: new Date() }).where(eq(backgroundJobs.id, job.id)); results.push({ id: job.id, ok: true, ...result }); } catch (error) { const exhausted = job.attempts >= 5; await db.update(backgroundJobs).set(exhausted ? { status: "failed", failedAt: new Date(), error: (error as Error).message, updatedAt: new Date() } : { status: "queued", availableAt: new Date(Date.now() + Math.min(2 ** job.attempts, 60) * 60_000), error: (error as Error).message, updatedAt: new Date() }).where(eq(backgroundJobs.id, job.id)); results.push({ id: job.id, ok: false }); } }
  return { claimed: results.length, results };
}
export async function enqueueCalendarReconciliation(now = new Date()) {
  if (!process.env.DATABASE_ADMIN_URL) throw new Error("DATABASE_ADMIN_URL is required."); const db = createDatabase(process.env.DATABASE_ADMIN_URL); const rows = await db.select({ id: calendarConnections.id, organisationId: calendarConnections.organisationId }).from(calendarConnections).where(eq(calendarConnections.status, "active")); const day = now.toISOString().slice(0, 10); let queued = 0; for (const connection of rows) { const [job] = await db.insert(backgroundJobs).values({ organisationId: connection.organisationId, queue: "calendar", type: "calendar_reconcile", deduplicationKey: `calendar-reconcile:${connection.id}:${day}`, payload: { connectionId: connection.id } }).onConflictDoNothing().returning({ id: backgroundJobs.id }); if (job) queued += 1; } return { eligible: rows.length, queued };
}
