import { describe, expect, it } from "vitest";
import { validDay, validCoordinate, normaliseRoadRoute, interpolateRoad, legForVisit, plannedArrival, journeySections, boundedFieldContext, type FieldworkRoute } from "./fieldwork";
describe("fieldwork route evidence",()=>{
 it("validates actual dates, ranges and missing coordinates",()=>{expect(validDay("2026-02-30")).toBe(false);expect(validDay("2026-10-05")).toBe(true);expect(validCoordinate({latitude:91,longitude:0})).toBe(false);expect(validCoordinate(null)).toBe(false);});
 const road={routes:[{distance:1000,duration:240,legs:[{distance:1000,duration:240}],geometry:{type:"LineString",coordinates:[[-2.6,51.4],[-2.61,51.41]]}}]};
 it("only accepts validated road geometry and exact leg parity",()=>{expect(normaliseRoadRoute(road,1)?.durationSeconds).toBe(240);expect(normaliseRoadRoute(road,2)).toBe(null);expect(normaliseRoadRoute({routes:[{...road.routes[0],duration:NaN}]},1)).toBe(null);expect(normaliseRoadRoute({routes:[{...road.routes[0],geometry:{type:"LineString",coordinates:[[400,51],[-2,51]]}}]},1)).toBe(null);});
 it("never shifts an originless leg onto the first visit",()=>{const route={origin:null,provider:{legs:[{durationSeconds:20,distanceMetres:100}]}} as FieldworkRoute;expect(legForVisit(route,0)).toBeUndefined();expect(legForVisit(route,1)?.durationSeconds).toBe(20);});
 it("uses the previous scheduled finish, not a fabricated live ETA",()=>{const route={origin:null,stops:[{endsAt:"2026-10-05T10:00:00Z"},{endsAt:"2026-10-05T12:00:00Z"}],provider:{legs:[{durationSeconds:600,distanceMetres:100}]}} as FieldworkRoute;expect(plannedArrival(route,0)).toBeNull();expect(plannedArrival(route,1)).toBe("2026-10-05T10:10:00.000Z");});
 it("splits paced previews in appointment order",()=>{const route={origin:null,stops:[{id:"a",coordinates:{longitude:0,latitude:0}},{id:"b",coordinates:{longitude:1,latitude:0}},{id:"c",coordinates:{longitude:1,latitude:1}}],provider:{geometry:{type:"LineString",coordinates:[[0,0],[1,0],[1,1]]}}} as FieldworkRoute;expect(journeySections(route).map(s=>s.stopId)).toEqual(["b","c"]);expect(journeySections(route)[0].points).toEqual([[0,0],[1,0]]);});
 it("interpolates road geometry without GPS or straight-line shortcuts",()=>{const points:[number,number][]=[[0,0],[1,0],[1,1]];expect(interpolateRoad(points,0)).toEqual([0,0]);expect(interpolateRoad(points,1)).toEqual([1,1]);expect(interpolateRoad([],0)).toBe(null);});
 it("requires attributed WGS84 context and excludes unrelated features",()=>{const tree=(lon:number)=>({type:"Feature",properties:{kind:"tree"},geometry:{type:"Point",coordinates:[lon,51.45]}});const data={attribution:"OSM",featureCollection:{type:"FeatureCollection",features:[tree(-2.6),tree(0)]}};expect(boundedFieldContext(data,[{latitude:51.45,longitude:-2.6}])?.featureCollection.features).toHaveLength(1);expect(boundedFieldContext({...data,crs:"EPSG:27700"},[{latitude:51.45,longitude:-2.6}])).toBeNull();expect(boundedFieldContext({...data,attribution:""},[{latitude:51.45,longitude:-2.6}])).toBeNull();});
});
