import "server-only";
import {z} from "zod";
import {and,eq} from "drizzle-orm";
import {createDatabase,platformConnections,tenantConnections,organisations,auditEvents,withTenant} from "@surveynt/db";
import {allowedEndpoint,connectionJson} from "./connection-network";
export const connectionInput=z.object({id:z.uuid().optional(),name:z.string().trim().min(2).max(120),kind:z.enum(["routing","weather","traffic","ai"]),endpoint:z.url().max(500),credentialEnv:z.string().regex(/^SURVEYNT_CONNECTION_SECRET_[A-Z0-9_]{1,80}$/).nullable(),modelId:z.string().trim().max(120).nullable(),providerKey:z.string().trim().regex(/^[a-z0-9_-]{2,40}$/).nullable(),enabled:z.boolean(),evaluationOnly:z.boolean()});
export const tenantConnectionInput=z.object({connectionId:z.uuid(),enabled:z.boolean(),monthlyMessageLimit:z.number().int().min(0).max(1_000_000),modelId:z.string().trim().max(120).nullable()});
export const connectionDb=()=>{if(!process.env.DATABASE_ADMIN_URL)throw Error("Platform connection storage is unavailable.");return createDatabase(process.env.DATABASE_ADMIN_URL);};
export const safeConnection=(c:typeof platformConnections.$inferSelect)=>({id:c.id,name:c.name,kind:c.kind,endpoint:c.endpoint,modelId:c.modelId,providerKey:c.providerKey,enabled:c.enabled,evaluationOnly:c.evaluationOnly,credentialConfigured:Boolean(c.credentialEnv&&process.env[c.credentialEnv]),lastCheckedAt:c.lastCheckedAt?.toISOString()??null,checkStatus:c.checkStatus});
export async function listConnections(){return (await connectionDb().select().from(platformConnections)).map(safeConnection);}
export async function saveConnection(actor:string,input:z.infer<typeof connectionInput>){allowedEndpoint(input.endpoint);if(input.kind==="weather"&&new URL(input.endpoint).hostname==="api.open-meteo.com"&&!input.evaluationOnly)throw Error("The hosted free Open-Meteo endpoint must remain evaluation-only.");if(input.kind==="ai"&&(!input.modelId||!input.providerKey))throw Error("AI connections require the approved model and provider identifiers.");const {id,...value}=input;const db=connectionDb();if(id&&!value.credentialEnv){const [old]=await db.select({credentialEnv:platformConnections.credentialEnv}).from(platformConnections).where(eq(platformConnections.id,id));value.credentialEnv=old?.credentialEnv??null;}const [row]=id?await db.update(platformConnections).set({...value,checkStatus:"unchecked",updatedAt:new Date()}).where(eq(platformConnections.id,id)).returning():await db.insert(platformConnections).values(value).returning();if(!row)throw Error("Connection not found.");await db.insert(auditEvents).values({platformStaffId:actor,action:"platform.connection_saved",resourceType:"platform_connection",resourceId:row.id,metadata:{kind:input.kind,enabled:input.enabled}});return safeConnection(row);}
export async function checkConnection(id:string,actor:string){const db=connectionDb();const [c]=await db.select().from(platformConnections).where(eq(platformConnections.id,id));if(!c)throw Error("Connection not found.");let status="unavailable";try{const secret=c.credentialEnv?process.env[c.credentialEnv]:undefined;if(c.credentialEnv&&!secret)throw Error("Credential missing.");await connectionJson(c.endpoint,c.kind==="ai"?"/models":c.kind==="routing"?"/route/v1/driving/-0.12,51.5;-0.13,51.51":c.kind==="weather"?"/v1/forecast":"/Road/All/Disruption",{secret:c.kind==="weather"||c.kind==="traffic"?undefined:secret,query:c.kind==="weather"?{latitude:"51.5",longitude:"-0.12",current:"temperature_2m",...(secret?{apikey:secret}:{})}:c.kind==="traffic"&&secret?{app_key:secret}:undefined});status="available";}catch{status="unavailable";}await db.update(platformConnections).set({checkStatus:status,lastCheckedAt:new Date()}).where(eq(platformConnections.id,id));await db.insert(auditEvents).values({platformStaffId:actor,action:"platform.connection_checked",resourceType:"platform_connection",resourceId:id,metadata:{status}});return {status,checkedAt:new Date().toISOString()};}
export async function enabledConnection(org:string,kind:string){const db=connectionDb();const [row]=await db.select({connection:platformConnections,selection:tenantConnections,demo:organisations.isDemo}).from(tenantConnections).innerJoin(platformConnections,eq(platformConnections.id,tenantConnections.connectionId)).innerJoin(organisations,eq(organisations.id,tenantConnections.organisationId)).where(and(eq(tenantConnections.organisationId,org),eq(tenantConnections.enabled,true),eq(platformConnections.enabled,true),eq(platformConnections.kind,kind),eq(organisations.status,"active"))).limit(1);if(!row||row.connection.evaluationOnly&&!row.demo)return null;return row;}
export async function tenantConnectionStatuses(org:string){const rows=await connectionDb().select({c:platformConnections,t:tenantConnections}).from(tenantConnections).innerJoin(platformConnections,eq(platformConnections.id,tenantConnections.connectionId)).where(eq(tenantConnections.organisationId,org));return rows.map(({c,t})=>({...safeConnection(c),tenantEnabled:t.enabled,monthlyMessageLimit:t.monthlyMessageLimit,selectedModelId:t.modelId}));}
export async function selectConnection(org:string,actor:string,input:z.infer<typeof tenantConnectionInput>){const db=connectionDb();const [c]=await db.select().from(platformConnections).where(eq(platformConnections.id,input.connectionId));const [o]=await db.select().from(organisations).where(eq(organisations.id,org));if(!c||!o)throw Error("Practice or connection not found.");if(input.enabled&&(!c.enabled||c.evaluationOnly&&!o.isDemo))throw Error("Enable an approved production connection for a production practice.");if(input.modelId&&input.modelId!==c.modelId)throw Error("Choose the approved connection model.");return withTenant(db,org,async tx=>{await tx.execute((await import("drizzle-orm")).sql`select pg_advisory_xact_lock(hashtext(${org+c.kind}))`);if(input.enabled){const same=await db.select({id:platformConnections.id}).from(platformConnections).where(eq(platformConnections.kind,c.kind));for(const other of same)await tx.update(tenantConnections).set({enabled:false}).where(and(eq(tenantConnections.organisationId,org),eq(tenantConnections.connectionId,other.id)));}await tx.insert(tenantConnections).values({organisationId:org,...input}).onConflictDoUpdate({target:[tenantConnections.organisationId,tenantConnections.connectionId],set:{...input,updatedAt:new Date()}});await tx.insert(auditEvents).values({organisationId:org,platformStaffId:actor,action:"platform.tenant_connection_selected",resourceType:"organisation",resourceId:org,metadata:{connectionId:input.connectionId,enabled:input.enabled}});});}
