import { suggestedServiceScope } from "./service-scope";
import { createHash, randomBytes } from "node:crypto";
import { and, eq, sql } from "drizzle-orm";
import { appointments, auditEvents, availabilityBlocks, calendarConnections, calendarConflicts, clients, clientContacts, clientPayments, createDatabase, customerQuotes, entitlements, invoices, invoiceLineItems, jobs, jobStageEvents, organisationDocuments, organisationOperationalSettings, organisations, properties, quoteSnapshots, reportVersions, serviceDefinitions, servicePricingVersions, settlementLedger, surveys, withTenant, type Database } from "@surveynt/db";
import { composeReport, composerInputFingerprint, defaultTemplate, templateFingerprint, COMPOSER, type ComposerInput } from "@surveynt/assistant";
import { localDayRange } from "./scheduling";

export async function isDemoOrganisation(id:string,db:Database=createDatabase()){const [org]=await db.select({isDemo:organisations.isDemo,status:organisations.status}).from(organisations).where(eq(organisations.id,id)).limit(1);return org?.isDemo===true&&org.status==="active";}
export const demoCustomerNames=["Elizabeth Harrington","Whitmore Property Group","Daniel Okafor","Sophie Bennett","James Carter","Amelia Brooks"];
export const demoDocumentText = "Surveynt stakeholder demonstration\nFictional practice terms and inspection checklist.\nThis example is not a legal agreement, a completed survey or a RICS-issued report.\nNo real customer or property information is contained in this document.\n";
const addresses=["18 Royal York Crescent","Westgate House, Park Street","42 Sydenham Road","7 Willowbank Close","12 Meadow View","6 Station Road","9 The Orchard","55 Park Lane"];
const stages=["enquiry","quoted","instructed","scheduled","scheduled","scheduled","inspection_complete","report_drafting","internal_review","issued","paid","report_drafting"] as const;
function visitTime(days:number,hour=9){const date=new Date(`${new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/London"}).format(new Date())}T12:00:00Z`);date.setUTCDate(date.getUTCDate()+days);while([0,6].includes(date.getUTCDay()))date.setUTCDate(date.getUTCDate()+1);return new Date(localDayRange(date.toISOString().slice(0,10)).start.getTime()+hour*3600000);}
/** All records are normal tenant records; external side effects are blocked by the persisted demo marker. */
export async function seedStakeholderDemo(organisationId:string,ownerUserId:string,db:Database=createDatabase(process.env.DATABASE_ADMIN_URL)){
  return withTenant(db,organisationId,async(tx)=>{
    await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${`demo-seed:${organisationId}`}))`);
    const [org]=await tx.select().from(organisations).where(eq(organisations.id,organisationId)).limit(1);if(!org?.isDemo||org.status!=="active")throw new Error("DEMO_ORGANISATION_REQUIRED");if(org.demoSeededAt)return {seeded:false};
    await tx.insert(entitlements).values({organisationId,key:"billing_exempt",enabled:true}).onConflictDoNothing();
    await tx.insert(organisationOperationalSettings).values({organisationId,timezone:"Europe/London",workingHours:Object.fromEntries(["monday","tuesday","wednesday","thursday","friday"].map((d)=>[d,{start:"09:00",end:"17:30"}])),officeAddress:"Bristol demo office",officeLatitude:51.4545,officeLongitude:-2.5879,publicQuotesEnabled:true,clientPaymentsEnabled:false,customerBranding:{displayName:"Surveynt Demo Practice"}}).onConflictDoNothing();
    await tx.insert(organisationDocuments).values({organisationId,name:"Demo practice terms and checklist.txt",category:"compliance",accessClass:"firm",blobUrl:"demo://practice-checklist",blobPathname:"demo://practice-checklist",checksum:createHash("sha256").update(demoDocumentText).digest("hex"),contentType:"text/plain",sizeBytes:Buffer.byteLength(demoDocumentText),uploadedByUserId:ownerUserId,retentionUntil:new Date(Date.now()+365*86400000)});
    const serviceRows=[];
    for(const [name,fee,duration] of [["RICS Level 1 Survey",35000,120],["RICS Level 2 Survey",45000,180],["RICS Level 2 Survey Only",40000,180],["RICS Level 3 Survey",75000,240],["Drone Survey",25000,90],["Valuation Report",30000,120]] as const){const [service]=await tx.insert(serviceDefinitions).values({organisationId,name,defaultFee:(fee/100).toFixed(2)}).returning();const [pricing]=await tx.insert(servicePricingVersions).values({organisationId,serviceDefinitionId:service.id,version:1,baseAmountMinor:fee,vatBasisPoints:2000,depositBasisPoints:1000,durationMinutes:duration,validityDays:7,recommendationRules:{source:"clifton_adviser_v1"},surcharges:{"loft-conversion":{label:"Loft conversion",amountMinor:8000},"single-storey-extension":{label:"Single-storey extension",amountMinor:8000}}}).returning();serviceRows.push({service,pricing});}
    const customers=[];for(let i=0;i<demoCustomerNames.length;i++){const [client]=await tx.insert(clients).values({organisationId,kind:i===1?"company":"individual",displayName:demoCustomerNames[i],email:`customer${i+1}@example.test`,phone:`07700 90010${i}`}).returning();await tx.insert(clientContacts).values({organisationId,clientId:client.id,name:client.displayName,email:client.email,primary:true});customers.push(client);}
    const propertyRows=[];for(let i=0;i<addresses.length;i++){const [property]=await tx.insert(properties).values({organisationId,clientId:customers[i%6].id,line1:addresses[i],city:"Bristol",postcode:i===0?"BS8 4JX":"BS1 5PB",propertyType:i%2?"Detached house":"Victorian terrace",country:"ENG",addressSource:"demo_fixture",latitude:51.45+i*.002,longitude:-2.60+i*.002,locationConfidence:"approximate",locationResolutionMethod:"illustrative_demo"}).returning();propertyRows.push(property);}
    const templateHash=await templateFingerprint(defaultTemplate);
    for(let i=0;i<12;i++){const property=propertyRows[i%8];const customer=customers.find(c=>c.id===property.clientId)!;const startsAt=visitTime(i>=3&&i<=5?0:i-5,i===4?13.5:i===5?15.5:9);const [job]=await tx.insert(jobs).values({organisationId,clientId:customer.id,propertyId:property.id,reference:`SVY-${1048-i}`,serviceName:serviceRows[i%serviceRows.length].service.name,stage:stages[i],assignedSurveyorId:ownerUserId,targetDate:startsAt.toISOString().slice(0,10),fee:(serviceRows[i%serviceRows.length].pricing.baseAmountMinor*1.2/100).toFixed(2),priority:i===0||i===8?"high":"normal",notes:"Fictional stakeholder scenario. No real inspection or client transaction."}).returning();await tx.insert(jobStageEvents).values({organisationId,jobId:job.id,toStage:stages[i],changedByUserId:ownerUserId,reason:"Demo seed"});
      if(i>=3&&i<=5)await tx.insert(appointments).values({organisationId,jobId:job.id,surveyorId:ownerUserId,status:"confirmed",startsAt,endsAt:new Date(startsAt.getTime()+serviceRows[i%serviceRows.length].pricing.durationMinutes*60000),notes:"Demo visit — illustrative coordinates"});
      if(i>=6){const [survey]=await tx.insert(surveys).values({organisationId,jobId:job.id,propertyId:property.id,templateKey:defaultTemplate.key,templateVersion:defaultTemplate.version,templateFingerprint:templateHash,serviceLevel:suggestedServiceScope(job.serviceName) ?? "bespoke",jurisdiction:"ENG",createdByUserId:ownerUserId}).returning();if(i>=7){const input:ComposerInput={template:defaultTemplate,serviceLevel:suggestedServiceScope(job.serviceName) ?? "bespoke",jurisdiction:"ENG",job:{reference:job.reference},property:{line1:property.line1,city:property.city,postcode:property.postcode},values:[],elements:[],observations:[],evidence:[],media:[],clauses:[]};const composed=composeReport(input);await tx.insert(reportVersions).values({organisationId,surveyId:survey.id,jobId:job.id,versionNumber:1,composer:COMPOSER,templateKey:defaultTemplate.key,templateVersion:defaultTemplate.version,templateFingerprint:templateHash,inputFingerprint:await composerInputFingerprint(input),content:composed.report as unknown as Record<string,unknown>,trace:composed.trace as unknown as Record<string,unknown>,contentSha256:createHash("sha256").update(JSON.stringify(composed.report)).digest("hex"),createdByUserId:ownerUserId});}}
      const pricing=serviceRows[i%serviceRows.length];const total=Math.round(Number(job.fee)*100);const rawToken=randomBytes(32).toString("base64url");const [quote]=await tx.insert(customerQuotes).values({organisationId,clientId:customer.id,propertyId:property.id,jobId:i>1?job.id:null,reference:`SVQ-${1048-i}`,publicRequestId:crypto.randomUUID(),serviceDefinitionId:pricing.service.id,pricingVersionId:pricing.pricing.id,status:i>1?"converted":i===1?"issued":"draft",firstName:customer.displayName.split(" ")[0],lastName:customer.displayName.split(" ").slice(1).join(" "),email:customer.email,propertyAddress:i>1?`${property.line1}, Bristol, ${property.postcode}`:null,city:"Bristol",postcode:property.postcode,pricingSnapshot:{service:pricing.service.name,durationMinutes:pricing.pricing.durationMinutes,demo:true},answers:{purpose:"survey-only",propertyAge:"pre-1950",propertyType:"terrace"},subtotalMinor:Math.round(total/1.2),vatMinor:total-Math.round(total/1.2),totalMinor:total,depositMinor:Math.round(total*.1),accessTokenHash:createHash("sha256").update(rawToken).digest("hex"),expiresAt:new Date(Date.now()+7*86400000),issuedAt:new Date()}).returning();await tx.insert(quoteSnapshots).values({organisationId,quoteId:quote.id,event:"demo_seed",snapshot:{reference:quote.reference,totalMinor:total,demo:true}});
      if(i>=3&&i<=5)await tx.update(appointments).set({quoteId:quote.id}).where(and(eq(appointments.jobId,job.id),eq(appointments.organisationId,organisationId)));
      if(i>1){
        const amount=quote.depositMinor;
        const [invoice]=await tx.insert(invoices).values({organisationId,jobId:job.id,quoteId:quote.id,number:`${quote.reference}-D`,status:i===11?"part_paid":"paid",currency:"GBP",subtotalMinor:Math.round(amount/1.2),vatMinor:amount-Math.round(amount/1.2),totalMinor:amount,issuedAt:new Date(),paidAt:i===11?null:new Date()}).returning();
        await tx.insert(invoiceLineItems).values({organisationId,invoiceId:invoice.id,description:"Simulated demo deposit",unitAmountMinor:invoice.subtotalMinor,vatBasisPoints:2000});
        const [payment]=await tx.insert(clientPayments).values({organisationId,invoiceId:invoice.id,quoteId:quote.id,purpose:"deposit",amountMinor:amount,status:i===11?"partially_refunded":"succeeded",refundedMinor:i===11?1000:0,succeededAt:new Date(),stripeCheckoutSessionId:`demo_seed_${invoice.id}`}).returning();
        await tx.insert(settlementLedger).values({organisationId,paymentId:payment.id,entryType:"firm_liability",amountMinor:amount,metadata:{demo:true}});
        if(i===11)await tx.insert(settlementLedger).values({organisationId,paymentId:payment.id,entryType:"refund",amountMinor:-1000,metadata:{demo:true}});
        const balance=total-amount;
        const [balanceInvoice]=await tx.insert(invoices).values({organisationId,jobId:job.id,quoteId:quote.id,number:`${quote.reference}-B`,status:i===10?"paid":i===9?"overdue":"open",subtotalMinor:Math.round(balance/1.2),vatMinor:balance-Math.round(balance/1.2),totalMinor:balance,dueAt:new Date(Date.now()+(i===9?-2:14)*86400000),issuedAt:new Date(),paidAt:i===10?new Date():null}).returning();
        await tx.insert(invoiceLineItems).values({organisationId,invoiceId:balanceInvoice.id,description:"Simulated survey balance",unitAmountMinor:balanceInvoice.subtotalMinor,vatBasisPoints:2000});
        if(i===10){const [balancePayment]=await tx.insert(clientPayments).values({organisationId,invoiceId:balanceInvoice.id,quoteId:quote.id,purpose:"balance",amountMinor:balance,status:"succeeded",succeededAt:new Date(),stripeCheckoutSessionId:`demo_seed_${balanceInvoice.id}`}).returning();await tx.insert(settlementLedger).values({organisationId,paymentId:balancePayment.id,entryType:"firm_liability",amountMinor:balance,metadata:{demo:true}});}
      }
    }
    const [connection]=await tx.insert(calendarConnections).values({organisationId,userId:ownerUserId,provider:"demo",providerAccountId:`demo:${organisationId}`,encryptedCredentials:"DEMO_NO_CREDENTIALS",status:"demo"}).returning();await tx.insert(calendarConflicts).values({organisationId,connectionId:connection.id,kind:"external_time_changed",details:{demo:true,message:"An external calendar moved a visit into blocked time. Keep Surveynt time or reschedule."}});await tx.insert(availabilityBlocks).values({organisationId,userId:ownerUserId,startsAt:visitTime(2,12),endsAt:visitTime(2,13),source:"demo",kind:"external_busy",reason:"Simulated external busy period"});
    await tx.update(organisations).set({demoSeededAt:new Date()}).where(eq(organisations.id,organisationId));await tx.insert(auditEvents).values({organisationId,actorUserId:ownerUserId,action:"demo.seeded",resourceType:"organisation",resourceId:organisationId,metadata:{customers:6,properties:8,jobs:12,generation:org.demoGeneration}});return{seeded:true};
  });
}

export async function issueDemoCustomerLink(organisationId:string,quoteId:string,actor:string|null){return withTenant(createDatabase(),organisationId,async(tx)=>{const [org]=await tx.select().from(organisations).where(eq(organisations.id,organisationId)).limit(1);if(!org?.isDemo||org.status!=="active")throw new Error("DEMO_ORGANISATION_REQUIRED");const [quote]=await tx.select().from(customerQuotes).where(and(eq(customerQuotes.id,quoteId),eq(customerQuotes.organisationId,organisationId))).for("update").limit(1);if(!quote)throw new Error("QUOTE_NOT_FOUND");const token=randomBytes(32).toString("base64url");await tx.update(customerQuotes).set({accessTokenHash:createHash("sha256").update(token).digest("hex"),tokenRevokedAt:null,version:quote.version+1,updatedAt:new Date()}).where(eq(customerQuotes.id,quote.id));await tx.insert(auditEvents).values({organisationId,actorUserId:actor,action:"demo.customer_link_issued",resourceType:"quote",resourceId:quote.id});return{url:`/quote/${quote.id}#${token}`};});}
