import { createHash } from "node:crypto";
import { and, asc, eq, inArray, or, sql } from "drizzle-orm";
import { assistantTasks, fieldProposals, mediaAnalyses, observations, surveyFieldValues, surveys, type TenantTransaction } from "@surveynt/db";

const limit = 5000;
function complete<T>(rows: T[]) { if (rows.length > limit) throw new Error("The provenance records exceed the review register limit."); return rows; }
function fingerprint(value: unknown) { return createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
export async function readSurveyFileProvenance(tx: TenantTransaction, organisationId: string, jobId: string, mediaIdentities: string[], questionnaireIds: string[]) {
  const surveyRows = complete(await tx.select({ id: surveys.id }).from(surveys).where(and(eq(surveys.organisationId, organisationId), eq(surveys.jobId, jobId))).orderBy(asc(surveys.id)).limit(limit + 1));
  const surveyIds = surveyRows.map(survey => survey.id);
  const analyses = mediaIdentities.length ? complete(await tx.select({ id: mediaAnalyses.id, mediaId: mediaAnalyses.mediaId, surveyId: mediaAnalyses.surveyId, status: mediaAnalyses.status, result: mediaAnalyses.result }).from(mediaAnalyses).where(and(eq(mediaAnalyses.organisationId, organisationId), sql`${mediaAnalyses.mediaId}::text = any(array[${sql.join(mediaIdentities.map(id => sql`${id}::text`), sql`, `)}])`)).orderBy(asc(mediaAnalyses.id)).limit(limit + 1)) : [];
  const identities = [...new Set([...mediaIdentities, ...analyses.map(analysis => analysis.id), ...questionnaireIds])];
  if (identities.length > limit) throw new Error("The provenance identities exceed the review register limit.");
  const identityArray = sql`array[${sql.join(identities.map(id => sql`${id}::text`), sql`, `)}]`;
  const embeddedReference = (payload: ReturnType<typeof sql>, sourceRef: typeof surveyFieldValues.sourceRef | typeof observations.sourceRef) => sql`jsonb_path_query_array(${payload}, '$.**.mediaId') ?| ${identityArray} or jsonb_path_query_array(${payload}, '$.**.analysisId') ?| ${identityArray} or jsonb_path_query_array(${payload}, '$.**.id') ?| ${identityArray} or ${sourceRef} = any(${identityArray})`;
  const values = surveyIds.length || identities.length ? complete(await tx.select().from(surveyFieldValues).where(and(eq(surveyFieldValues.organisationId, organisationId), or(surveyIds.length ? inArray(surveyFieldValues.surveyId, surveyIds) : undefined, identities.length ? embeddedReference(sql`${surveyFieldValues.value}`, surveyFieldValues.sourceRef) : undefined))).orderBy(asc(surveyFieldValues.id)).limit(limit + 1)) : [];
  const observationRows = surveyIds.length || identities.length ? complete(await tx.select().from(observations).where(and(eq(observations.organisationId, organisationId), or(surveyIds.length ? inArray(observations.surveyId, surveyIds) : undefined, identities.length ? embeddedReference(sql`${observations.structured}`, observations.sourceRef) : undefined))).orderBy(asc(observations.id)).limit(limit + 1)) : [];
  const tasks = surveyIds.length || identities.length ? complete(await tx.select({ id: assistantTasks.id, surveyId: assistantTasks.surveyId, status: assistantTasks.status, title: assistantTasks.title, detail: assistantTasks.detail, resolutionNote: assistantTasks.resolutionNote, evidence: assistantTasks.evidence, updatedAt: assistantTasks.updatedAt }).from(assistantTasks).where(and(eq(assistantTasks.organisationId, organisationId), or(surveyIds.length ? inArray(assistantTasks.surveyId, surveyIds) : undefined, identities.length ? sql`jsonb_path_query_array(${assistantTasks.evidence}, '$.**.mediaId') ?| ${identityArray} or jsonb_path_query_array(${assistantTasks.evidence}, '$.**.analysisId') ?| ${identityArray} or jsonb_path_query_array(${assistantTasks.evidence}, '$.**.id') ?| ${identityArray}` : undefined))).orderBy(asc(assistantTasks.id)).limit(limit + 1)) : [];
  const proposals = surveyIds.length || identities.length ? complete(await tx.select({ id: fieldProposals.id, surveyId: fieldProposals.surveyId, reviewStatus: fieldProposals.reviewStatus, proposedValue: fieldProposals.proposedValue, limitations: fieldProposals.limitations, reviewNote: fieldProposals.reviewNote, evidenceRefs: fieldProposals.evidenceRefs, inputVersion: fieldProposals.inputVersion, reviewedAt: fieldProposals.reviewedAt }).from(fieldProposals).where(and(eq(fieldProposals.organisationId, organisationId), or(surveyIds.length ? inArray(fieldProposals.surveyId, surveyIds) : undefined, identities.length ? sql`jsonb_path_query_array(jsonb_build_array(${fieldProposals.evidenceRefs}, ${fieldProposals.proposedValue}), '$.**.mediaId') ?| ${identityArray} or jsonb_path_query_array(jsonb_build_array(${fieldProposals.evidenceRefs}, ${fieldProposals.proposedValue}), '$.**.analysisId') ?| ${identityArray} or jsonb_path_query_array(jsonb_build_array(${fieldProposals.evidenceRefs}, ${fieldProposals.proposedValue}), '$.**.id') ?| ${identityArray}` : undefined))).orderBy(asc(fieldProposals.id)).limit(limit + 1)) : [];
  const externalReferences = [...tasks, ...proposals, ...values, ...observationRows].filter(record => !surveyIds.includes(record.surveyId)).map(record => ({ id: record.id, surveyId: record.surveyId }));
  return { values: values.map(({ value, sourceRef, correctionReason, ...record }) => ({ ...record, contentFingerprint: fingerprint({ value, sourceRef, correctionReason }) })), observations: observationRows.map(({ text, structured, locationLabel, sourceRef, ...record }) => ({ ...record, contentFingerprint: fingerprint({ text, structured, locationLabel, sourceRef }) })), analyses: analyses.map(({ result, ...analysis }) => ({ ...analysis, resultFingerprint: fingerprint(result) })), tasks: tasks.map(({ title, detail, resolutionNote, evidence, ...task }) => ({ ...task, evidenceFingerprint: fingerprint(evidence), contentFingerprint: fingerprint({ title, detail, resolutionNote }) })), proposals: proposals.map(({ proposedValue, limitations, reviewNote, evidenceRefs, ...proposal }) => ({ ...proposal, evidenceFingerprint: fingerprint(evidenceRefs), contentFingerprint: fingerprint({ proposedValue, limitations, reviewNote }) })), externalReferences,
    referenceReviewRequired: externalReferences.length > 0 || analyses.some(analysis => analysis.surveyId !== null && !surveyIds.includes(analysis.surveyId)) };
}
