import { createSurveyFileRemovalManifest, type SurveyFileRemovalManifestInput } from "./survey-file-removal-manifest";
import { z } from "zod";
import { createHash } from "node:crypto";
import { and, eq, sql } from "drizzle-orm";
import { isManagementRole } from "@surveynt/domain";
import { mediaAssets, auditEvents, jobs, organisations, organisationMemberships, surveyFileRemovals, type TenantTransaction } from "@surveynt/db";
import { readSurveyFileRetention } from "./survey-file-retention-register";
const decisionInput = z.object({ id: z.uuid(), manifestVersion: z.string().regex(/^[a-f0-9]{64}$/), reason: z.string().trim().min(10).max(2000), confirmed: z.literal(true) }).strict();
export async function disposeMediaMetadata(tx: TenantTransaction, organisationId: string, jobId: string, userId: string, mediaId: string, decision: z.infer<typeof decisionInput>) {
  const approved = decisionInput.parse(decision);
  await tx.execute(sql`select pg_advisory_xact_lock(hashtextextended(${`retention-policy:${organisationId}`},0))`);
  const [practice] = await tx.select({ status: organisations.status }).from(organisations).where(eq(organisations.id, organisationId)).for("share");
  const [member] = await tx.select().from(organisationMemberships).where(and(eq(organisationMemberships.organisationId, organisationId), eq(organisationMemberships.userId, userId), eq(organisationMemberships.active, true))).for("share");
  if (practice?.status !== "active" || !member || !isManagementRole(member.role)) throw new Error("Current active practice management permission is required.");
  const [job] = await tx.select({ id: jobs.id }).from(jobs).where(and(eq(jobs.organisationId, organisationId), eq(jobs.id, jobId))).for("update");
  if (!job) throw new Error("The survey file is unavailable.");
  const file = await readSurveyFileRetention(tx, organisationId, jobId);
  if (!file?.assessment.eligibleForManagerReview) throw new Error("The current file is protected or requires retention review.");
  const [request] = await tx.select().from(surveyFileRemovals).where(and(eq(surveyFileRemovals.organisationId, organisationId), eq(surveyFileRemovals.jobId, jobId), eq(surveyFileRemovals.status, "completed"))).for("update");
  if (!request || request.id !== approved.id || request.manifestVersion !== approved.manifestVersion) throw new Error("The completed removal decision changed.");
  const [recorded] = await tx.select().from(mediaAssets).where(and(eq(mediaAssets.organisationId, organisationId), eq(mediaAssets.id, mediaId))).for("update");
  if (!recorded) throw new Error("The media original is unavailable.");
  const { manifestVersion: storedVersion, ...manifestInput } = request.manifest;
  const manifest = createSurveyFileRemovalManifest(manifestInput as SurveyFileRemovalManifestInput);
  if (manifest.organisationId !== organisationId || manifest.jobId !== jobId || manifest.manifestVersion !== request.manifestVersion || storedVersion !== request.manifestVersion) throw new Error("The completed removal decision changed.");
  const object = manifest.objects.find(object => object.kind === "media" && object.id === mediaId);
  if (!object || object.storagePath !== recorded.storageKey || object.checksum !== recorded.sha256 || object.sizeBytes !== recorded.byteSize || request.progress[`media:${mediaId}`]?.state !== "removed") throw new Error("Whole-file removal has not been verified for this original.");
  if (recorded.captureContext.retentionRemoved === true && Object.keys(recorded.captureContext).length === 1 && recorded.originalFilename === null) return { disposed: true, duplicate: true };
  const contentFingerprint = createHash("sha256").update(JSON.stringify({ captureContext: recorded.captureContext, originalFilename: recorded.originalFilename })).digest("hex");
  await tx.insert(auditEvents).values({ organisationId, actorUserId: userId, action: "job.media_metadata_disposed", resourceType: "media_asset", resourceId: mediaId, metadata: { jobId, removalId: request.id, originalChecksum: recorded.sha256, contentFingerprint, policyVersion: request.manifest.policyVersion, reason: approved.reason, confirmed: true } });
  await tx.update(mediaAssets).set({ captureContext: { retentionRemoved: true }, originalFilename: null }).where(eq(mediaAssets.id, mediaId));
  return { disposed: true, duplicate: false };
}
