import "server-only";
import {createHash,randomBytes,timingSafeEqual} from "node:crypto";
import {and,eq,sql,gt,isNull,desc} from "drizzle-orm";
import {createDatabase,withTenant,trackingSessions,latestStaffLocations,organisationOperationalSettings,memberWorkProfiles,organisationMemberships,organisations,users,auditEvents} from "@surveynt/db";
import {hasProfessionalPermission} from "@surveynt/domain";
import {localParts,localDayRange} from "./scheduling";
import {validLocationUpdate,trackingEnd,trackingFresh} from "./tracking-policy";
import {GovernanceError} from "./ai-governance";
const hash=(token:string)=>createHash("sha256").update(token).digest("hex");
export async function startTracking(context:{organisationId:string;userId:string}){return withTenant(createDatabase(),context.organisationId,async tx=>{await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${context.organisationId+context.userId+":tracking"}))`);const [[setting],[profile]]=await Promise.all([tx.select().from(organisationOperationalSettings).where(eq(organisationOperationalSettings.organisationId,context.organisationId)).limit(1),tx.select().from(memberWorkProfiles).where(and(eq(memberWorkProfiles.organisationId,context.organisationId),eq(memberWorkProfiles.userId,context.userId))).limit(1)]);const now=new Date(),timezone=profile?.timezone??setting?.timezone??"Europe/London",local=localParts(now,timezone),hours=profile?.workingHours[local.weekday]??setting?.workingHours[local.weekday];if(!hours||"closed" in hours&&hours.closed)throw new GovernanceError(409,"hours_required","Configure working hours before starting location sharing.");let end=new Date(localDayRange(local.date,timezone).start.getTime()+17*3600000);const desired=Number(hours.end.split(":")[0])*60+Number(hours.end.split(":")[1]);for(let i=0;i<3;i++)end=new Date(end.getTime()+(desired-localParts(end,timezone).minutes)*60000);if(end<=now)throw new GovernanceError(409,"workday_ended","Location sharing is unavailable after your configured workday.");await tx.update(trackingSessions).set({stoppedAt:now}).where(and(eq(trackingSessions.organisationId,context.organisationId),eq(trackingSessions.userId,context.userId),isNull(trackingSessions.stoppedAt)));await tx.delete(latestStaffLocations).where(and(eq(latestStaffLocations.organisationId,context.organisationId),eq(latestStaffLocations.userId,context.userId)));const token=randomBytes(32).toString("base64url"),expiresAt=trackingEnd(now,end);const [session]=await tx.insert(trackingSessions).values({organisationId:context.organisationId,userId:context.userId,tokenHash:hash(token),expiresAt}).returning();await tx.insert(auditEvents).values({organisationId:context.organisationId,actorUserId:context.userId,action:"tracking.sharing_started",resourceType:"tracking_session",resourceId:session.id,metadata:{expiresAt:expiresAt.toISOString()}});return {id:session.id,token,expiresAt:expiresAt.toISOString()};});}
export async function trackingTokenContext(id:string,token:string){if(!process.env.DATABASE_ADMIN_URL||token.length<30||token.length>100)return null;const db=createDatabase(process.env.DATABASE_ADMIN_URL);const [session]=await db.select().from(trackingSessions).where(eq(trackingSessions.id,id)).limit(1);if(!session||session.stoppedAt||session.expiresAt<=new Date())return null;const actual=Buffer.from(hash(token)),expected=Buffer.from(session.tokenHash);if(actual.length!==expected.length||!timingSafeEqual(actual,expected))return null;const [member]=await db.select({active:organisationMemberships.active,role:organisationMemberships.role,canRecordSurvey:organisationMemberships.canRecordSurvey,status:organisations.status}).from(organisationMemberships).innerJoin(organisations,eq(organisations.id,organisationMemberships.organisationId)).where(and(eq(organisationMemberships.organisationId,session.organisationId),eq(organisationMemberships.userId,session.userId),eq(organisationMemberships.active,true))).limit(1);return member?.status==="active"&&hasProfessionalPermission(member.role,"record_survey",member.canRecordSurvey)?session:null;}
export async function uploadLocation(session:typeof trackingSessions.$inferSelect,input:{latitude:number;longitude:number;accuracyMetres:number;observedAt:string}){return withTenant(createDatabase(),session.organisationId,async tx=>{const [current]=await tx.select().from(trackingSessions).where(eq(trackingSessions.id,session.id)).for("update");const now=new Date(),observedAt=new Date(input.observedAt);if(!current||!validLocationUpdate(observedAt,current.createdAt,current.expiresAt,current.stoppedAt,now))throw new GovernanceError(409,"sharing_ended","Sharing ended or the offline location update is stale. Start a new sharing session.");const [previous]=await tx.select().from(latestStaffLocations).where(and(eq(latestStaffLocations.organisationId,session.organisationId),eq(latestStaffLocations.userId,session.userId)));if(previous&&previous.observedAt>=observedAt)return {accepted:false};await tx.insert(latestStaffLocations).values({organisationId:session.organisationId,userId:session.userId,sessionId:session.id,...input,observedAt,receivedAt:now}).onConflictDoUpdate({target:[latestStaffLocations.organisationId,latestStaffLocations.userId],set:{...input,sessionId:session.id,observedAt,receivedAt:now}});return {accepted:true};});}
export async function stopTracking(session:typeof trackingSessions.$inferSelect){return withTenant(createDatabase(),session.organisationId,async tx=>{await tx.update(trackingSessions).set({stoppedAt:new Date()}).where(and(eq(trackingSessions.id,session.id),eq(trackingSessions.organisationId,session.organisationId)));await tx.delete(latestStaffLocations).where(and(eq(latestStaffLocations.organisationId,session.organisationId),eq(latestStaffLocations.sessionId,session.id)));await tx.insert(auditEvents).values({organisationId:session.organisationId,actorUserId:session.userId,action:"tracking.sharing_stopped",resourceType:"tracking_session",resourceId:session.id});});}
export async function latestLocations(org:string){return withTenant(createDatabase(),org,async tx=>{await tx.execute(sql`delete from latest_staff_locations l using tracking_sessions s where l.organisation_id=${org} and s.id=l.session_id and (s.stopped_at is not null or s.expires_at <= now())`);const rows=await tx.select({location:latestStaffLocations,name:users.firstName,lastName:users.lastName,expiresAt:trackingSessions.expiresAt}).from(latestStaffLocations).innerJoin(trackingSessions,and(eq(trackingSessions.id,latestStaffLocations.sessionId),eq(trackingSessions.organisationId,org))).innerJoin(organisationMemberships,and(eq(organisationMemberships.userId,latestStaffLocations.userId),eq(organisationMemberships.organisationId,org),eq(organisationMemberships.active,true))).innerJoin(users,eq(users.id,latestStaffLocations.userId)).where(and(eq(latestStaffLocations.organisationId,org),isNull(trackingSessions.stoppedAt),gt(trackingSessions.expiresAt,new Date()))).orderBy(desc(latestStaffLocations.observedAt));return rows.map(r=>({...r.location,name:[r.name,r.lastName].filter(Boolean).join(" "),sharingStatus:trackingFresh(r.location.observedAt)?"sharing":"stale",expiresAt:r.expiresAt}));});}

/** Scheduled cleanup retains session consent/audit, never historical coordinates. */
export async function purgeExpiredLocations(){if(!process.env.DATABASE_ADMIN_URL)return {removed:0};const db=createDatabase(process.env.DATABASE_ADMIN_URL);const result=await db.execute(sql`delete from latest_staff_locations l using tracking_sessions s where s.organisation_id=l.organisation_id and s.id=l.session_id and (s.stopped_at is not null or s.expires_at<=now()) returning l.user_id`);return {removed:result.rows.length};}
