import {describe,it,expect} from "vitest";
import {availableWorkspaces,resolveWorkspace,workspaceRoute,workspaceHref,rememberedWorkspaceHref,workspaceApiHref} from "./workspace-mode";
import {canRecord,canApprove} from "./professional-access";
import {workspaceAudit} from "./workspace-audit";
const identity={slug:"practice",actorRole:"owner" as const,workspaceMode:"surveyor" as const};
describe("workspace role projection and routes",()=>{
 it("offers exactly the agreed instances",()=>{expect(availableWorkspaces("owner")).toEqual(["administration","manager","surveyor"]);expect(availableWorkspaces("administrator")).toHaveLength(3);expect(availableWorkspaces("manager")).toEqual(["manager","surveyor"]);expect(availableWorkspaces("surveyor")).toEqual(["surveyor"]);});
 it("uses the native workspace and caps alternative permissions",()=>{expect(resolveWorkspace("owner")).toMatchObject({workspaceMode:"administration",effectiveRole:"owner"});expect(resolveWorkspace("manager")).toMatchObject({workspaceMode:"manager",effectiveRole:"manager"});expect(resolveWorkspace("owner","manager")).toEqual({actorRole:"owner",workspaceMode:"manager",effectiveRole:"manager"});expect(resolveWorkspace("administrator","surveyor")?.effectiveRole).toBe("surveyor");for(const role of ["manager","surveyor","finance"] as const)expect(resolveWorkspace(role,"administration")).toBeNull();expect(resolveWorkspace("owner","platform")).toBeNull();});
 it("does not inherit recording or approval grants from presentation mode",()=>{const context={role:"surveyor" as const,actorRole:"owner" as const,canRecordSurvey:false,canApproveReports:false};expect(canRecord(context)).toBe(false);expect(canApprove(context)).toBe(false);expect(canRecord({...context,canRecordSurvey:true})).toBe(true);expect(canRecord({role:"surveyor"})).toBe(true);});
 it("normalises aliases and preserves links, queries and external scope",()=>{expect(workspaceRoute("/app/practice/surveyor/jobs/abc")).toEqual({canonical:"/app/practice/jobs/abc",requested:"surveyor"});expect(workspaceRoute("/api/v1/workspaces/manager/team")).toEqual({canonical:"/api/v1/team",requested:"manager"});expect(workspaceHref("/app/practice/jobs?a=1#case",identity)).toBe("/app/practice/surveyor/jobs?a=1#case");expect(workspaceHref("/app/practice/manager/jobs",identity)).toBe("/app/practice/surveyor/jobs");for(const url of ["/app/other/jobs","/platform/tenants","https://elsewhere.test/app/practice/jobs"])expect(workspaceHref(url,identity)).toBe(url);expect(workspaceHref("/app/practice/routes",{...identity,actorRole:"surveyor"})).toBe("/app/practice/routes");});
 it("rejects remembered pages outside the user’s permitted scope",()=>{const fallback="/app/practice/surveyor/overview";for(const value of [null,"/app/other/jobs","//external.test","/app/practice/settings/billing","/app/practice/staff","/app/practice/../other/jobs","/app/practice/%2e%2e/jobs","/app/practice/jobs%2f..%2fsettings","/app/practice/jobs\\else"])expect(rememberedWorkspaceHref(value,identity)).toBe(fallback);expect(rememberedWorkspaceHref("/app/practice/surveyor/jobs?view=active",identity)).toBe("/app/practice/surveyor/jobs?view=active");expect(rememberedWorkspaceHref("/app/practice/settings/billing",{...identity,workspaceMode:"manager"})).toBe("/app/practice/manager/overview");});
 it("scopes native download and OAuth links without touching public or platform endpoints",()=>{expect(workspaceApiHref("/api/v1/documents/own/download","surveyor")).toBe("/api/v1/workspaces/surveyor/documents/own/download");expect(workspaceApiHref("/api/v1/calendar/oauth/connect?provider=google","administration")).toBe("/api/v1/workspaces/administration/calendar/oauth/connect?provider=google");expect(workspaceApiHref("/api/v1/public/quotes","surveyor")).toBe("/api/v1/public/quotes");});
 it("adds mode metadata without changing the real actor or existing evidence",()=>{expect(workspaceAudit({organisationId:"tenant",actorRole:"owner",role:"manager",workspaceMode:"manager"},{actorUserId:"real-owner",metadata:{reason:"Reviewed"}})).toEqual({actorUserId:"real-owner",metadata:{reason:"Reviewed",actorRole:"owner",workspaceMode:"manager"}});});
});
