import {afterEach,describe,it,expect,vi} from "vitest";
import {workspaceFetch,pendingWorkspaceSaves,createWorkspaceReadScope} from "./workspace-request";
afterEach(()=>vi.unstubAllGlobals());
const tab=(mode:string)=>vi.stubGlobal("window",{location:{href:`https://app.test/app/practice/${mode}/jobs`,origin:"https://app.test",pathname:`/app/practice/${mode}/jobs`}});
describe("tab scoped request adapter",()=>{
 it("aborts reads and ignores late answers when an instance changes",()=>{const scope=createWorkspaceReadScope(),previous=scope.start();expect(previous.isCurrent()).toBe(true);scope.cancel();const next=scope.start();expect(previous.signal.aborted).toBe(true);expect(previous.isCurrent()).toBe(false);expect(next.isCurrent()).toBe(true);scope.cancel();expect(next.isCurrent()).toBe(false);});
 it("uses the current tab URL and preserves request credentials and body",async()=>{tab("manager");const fetch=vi.fn().mockResolvedValue(new Response("{}"));vi.stubGlobal("fetch",fetch);await workspaceFetch("/api/v1/jobs?active=1",{credentials:"same-origin"});expect(String(fetch.mock.calls[0][0])).toBe("https://app.test/api/v1/workspaces/manager/jobs?active=1");expect(fetch.mock.calls[0][1].credentials).toBe("same-origin");await workspaceFetch("/api/billing/portal",{method:"POST"});expect(String(fetch.mock.calls[1][0])).toBe("https://app.test/api/v1/workspaces/manager/billing/portal");tab("surveyor");await workspaceFetch("/api/v1/jobs");expect(String(fetch.mock.calls[2][0])).toContain("/workspaces/surveyor/jobs");});
 it("does not add mode to platform, public or other-origin requests",async()=>{tab("surveyor");const fetch=vi.fn().mockResolvedValue(new Response("{}"));vi.stubGlobal("fetch",fetch);for(const path of ["/api/platform/tenants","/api/v1/public/quotes","https://external.test/api/v1/jobs"])await workspaceFetch(path);expect(fetch.mock.calls.map(c=>String(c[0]))).toEqual(["https://app.test/api/platform/tenants","https://app.test/api/v1/public/quotes","https://external.test/api/v1/jobs"]);});
 it("blocks switching while a mutation is in flight and releases failures",async()=>{tab("manager");let reject!:(e:Error)=>void;vi.stubGlobal("fetch",vi.fn(()=>new Promise((_r,j)=>{reject=j;})));const save=workspaceFetch("/api/v1/jobs",{method:"POST"});expect(pendingWorkspaceSaves()).toBe(1);reject(Error("Unavailable"));await expect(save).rejects.toThrow();expect(pendingWorkspaceSaves()).toBe(0);});
});
