import { invoiceBalance } from "@/lib/invoice-balance";
import { workspaceApiGuard } from "@/lib/workspace-api-guard";
import { and,asc,eq } from "drizzle-orm";
import { auditEvents,clientPayments,createDatabase,manualPaymentReviews,invoices,invoiceLineItems,withTenant } from "@surveynt/db";
import { z } from "zod";
import { canManageFinance } from "@surveynt/domain";
import { apiContext,canWriteWorkspace } from "@/lib/access";
import { ok,parseBody,problem } from "@/lib/api";
export async function GET(request:Request,route:RouteContext<"/api/v1/finance/invoices/[id]">){const c=await apiContext(request);if(!c)return problem(401,"unauthorised","Sign in to view invoices.");const accessDenial=await workspaceApiGuard(request,c);if(accessDenial)return accessDenial;if(!canManageFinance(c.role))return problem(403,"forbidden","Finance access is required.");const {id}=await route.params;if(!z.uuid().safeParse(id).success)return problem(404,"not_found","Invoice not found.");if(c.demo)return problem(404,"not_found","Sign in to view a persistent invoice.");return withTenant(createDatabase(),c.organisationId,async tx=>{const [invoice]=await tx.select().from(invoices).where(and(eq(invoices.id,id),eq(invoices.organisationId,c.organisationId))).limit(1);if(!invoice)return problem(404,"not_found","Invoice not found.");const [payments,lines,reviews]=await Promise.all([tx.select().from(clientPayments).where(and(eq(clientPayments.invoiceId,id),eq(clientPayments.organisationId,c.organisationId))).orderBy(asc(clientPayments.createdAt)),tx.select().from(invoiceLineItems).where(and(eq(invoiceLineItems.invoiceId,id),eq(invoiceLineItems.organisationId,c.organisationId))),tx.select().from(manualPaymentReviews).where(and(eq(manualPaymentReviews.invoiceId,id),eq(manualPaymentReviews.organisationId,c.organisationId))).orderBy(asc(manualPaymentReviews.createdAt))]);const balance=await invoiceBalance(tx,invoice);return ok({invoice,payments,lines,reviews,...balance});});}
const schema=z.object({action:z.enum(["issue","void"])});
export async function POST(request:Request,route:RouteContext<"/api/v1/finance/invoices/[id]">){const c=await apiContext(request);if(!c)return problem(401,"unauthorised","Sign in to manage invoices.");const accessDenial=await workspaceApiGuard(request,c);if(accessDenial)return accessDenial;if(!canWriteWorkspace(c)||!canManageFinance(c.role))return problem(403,"forbidden","Only owners and administrators manage invoices.");const p=await parseBody(request,schema);if(!p.success)return problem(400,"invalid_request","Choose an invoice action.");const {id}=await route.params;if(!z.uuid().safeParse(id).success)return problem(404,"not_found","Invoice not found.");return withTenant(createDatabase(),c.organisationId,async tx=>{const [invoice]=await tx.select().from(invoices).where(and(eq(invoices.id,id),eq(invoices.organisationId,c.organisationId))).for("update").limit(1);if(!invoice)return problem(404,"not_found","Invoice not found.");const balance=await invoiceBalance(tx,invoice);if(p.data.action==="void"&&balance.creditedMinor>0)return problem(409,"credit_issued","An invoice with an issued credit note cannot be voided.");const payments=await tx.select().from(clientPayments).where(and(eq(clientPayments.invoiceId,id),eq(clientPayments.organisationId,c.organisationId)));if(p.data.action==="void"&&payments.some(v=>v.succeededAt))return problem(409,"credit_required","A paid invoice requires a refund or credit adjustment, not voiding.");if(p.data.action==="issue"&&invoice.status!=="draft")return problem(409,"already_issued","Only a draft invoice may be issued.");const [updated]=await tx.update(invoices).set({status:p.data.action==="void"?"void":"open",issuedAt:p.data.action==="issue"?new Date():invoice.issuedAt,updatedAt:new Date()}).where(and(eq(invoices.id,id),eq(invoices.organisationId,c.organisationId))).returning();await tx.insert(auditEvents).values({organisationId:c.organisationId,actorUserId:c.internalUserId,action:`invoice.${p.data.action}`,resourceType:"invoice",resourceId:id});return ok(updated);});}
